### ISSUE TITLE
Use pass-by-value instead of two overloads for copy and move

### ISSUE THREAD

**Issue by rcurtin** [mlpack/mlpack#1021]
Instead of doing the following:

```
void Method(const arma::mat& data); // makes copy of data
void Method(arma::mat&& data); // doesn't copy data, just moves it
```

we should instead do this:

```
void Method(arma::mat data);
```

In this way, a user can choose whether they want to copy data by calling `Method(data)` or avoid a copy by calling `Method(std::move(data))`, and it allows us to reduce the size of the codebase (sometimes significantly).

More information here:
http://cpptruths.blogspot.com/2012/03/rvalue-references-in-constructor-when.html
and this issue comes out of the discussion for #1014 so there is some more discussion there too.

We can close this issue when we have found and replaced all instances of the pattern, and when we have provided good documentation for how to use these methods and avoid copies.  I would suggest that we add some phrase like `be sure to pass the parameters with std::move() to avoid copies when possible` to the documentation of every function like this, since I don't necessarily expect the C++ users to be familiar with rvalue references in C++11, but that isn't the only option for providing good documentation.

**Comment by ShangtongZhang** [comment]
I suddenly have a new concern. Assume user has a `arma::mat data` and two models `m1`, `m2`, then user wants to call `m1.Predict(data)` then `m2.Predict(data)`. (Assume the logic within Predict can actually work well with `const mat&` and won't lead to any extra copy). In this case user can't use `m1.Predict(std::move(data))` then `m2.Predict(std::move(data))`. If user wants to call `Predict` of several different models `n` times, there would be at least `n-1` copies. But actually there can be no copy. Should we worry about this case? Or should the pass-by-value only be applied to constructor? As we have decided not to store reference in class so at least one copy in constructor is necessary.

**Comment by rcurtin** [comment]
There is only a need to pass-by-value in instances where the method actually modifies the data.  So if we have a method `Predict()` which doesn't need to modify the input data, then its signature should be

```
Predict(const MatType&);
```

but if you have a method that's actually going to modify the input data, then you need to copy it.  i.e. when we build kd-trees, we modify the ordering of the dataset and thus we can do pass-by-value there.  But when we build cover trees, the dataset on which the tree is built is not modified, so there we can do pass-by-const-reference.

**Comment by ShangtongZhang** [comment]
As we can't have `Predict(const mat&)` and `Predict(mat)` together, so I guess we still need old  `Predict(const mat&)` and `Predict(mat&&)` and don't need to make further changes. The only thing is that we don't want `Predict(mat&)`, we need to replace it if it exists somewhere.

**Comment by rcurtin** [comment]
I'm not sure I understand the difference.  There are two possibilities:

 - If the model can do predictions without modifying the data, we provide only `Predict(const mat&)`.
 - If the model must modify the data when doing predictions, we provide only `Predict(mat)` and the user chooses whether they want to copy their data (by just passing their matrix) or avoid a copy (by using `std:move()`).

Did I overlook anything?

**Comment by ShangtongZhang** [comment]
Oh I got it. That makes sense.

**Comment by deepanshugarg257** [comment]
If anyone already isn't, I'd like to work on this.

**Comment by rcurtin** [comment]
Yes, go ahead---but I would suggest doing small pieces at a time instead of the entire thing at once, to make reviewing easier.

**Comment by KrUciFieR-Jr** [comment]
Is this issue open if yes I would like to work on it

**Comment by rcurtin** [comment]
Yes, it is (it would be closed if it was done), but like I wrote in a previous response, I'd suggest doing small pieces at a time.  Feel free to go ahead and work on it.

**Comment by amanmehta-maniac** [comment]
@rcurtin I have tried to reduce some copy overhead. I read the blog included in the description and applied similar tactics in #1291. Please verify my PR.

**Comment by hassan-mahmood** [comment]
Hello! I would like to work on this issue.
From the description and your comments, this is what I have understood:
For the functions which do not change the passed data, we provide 'const lvalue reference' function to users.
For the functions which change the passed data, we provide rvalue reference function to users. For this, they can choose to copy or move the data.

So for a function which modifies an object O1, we have following scenario:
___________________________________________
void f1(Obj O1);

Object ob;
f1(ob);     //copy
f1(std::move(ob))  //move
__________________________________________

And for a function which doesn't modify the object, we have following scenario:

void f1(const Obj &O1);

Object ob;
f1(ob);
_______________________________________

Please correct me if I am wrong.
Thanks.

**Comment by rcurtin** [comment]
Hi @hassan-mahmood, that is correct.  If you'd like to work on this and open a PR, I would be happy to review and merge it.  Thanks!

**Comment by anky2936** [comment]
I would like to work on this issue. Is there anything that I should know before before start working on as this will be my first work on open source?

**Comment by rcurtin** [comment]
Hi @anky2936, this is a good issue to start on.  Try to follow the style guide with your modifications, and be sure to build the code and run the tests locally before opening a PR.  (Otherwise the Travis build will fail on the PR.)  We have a pretty good system in place, so don't worry too much---if there's a problem with the code, either the tools or a reviewer can help point it out so that you can address what's wrong, and then we can eventually get it merged in. :+1:

**Comment by wannabeOG** [comment]
Since this issue is open, can I work on it? I have gone through the blog post that you attached in the description and think this is a good first task considering my limited exposure to open source

**Comment by riaash04** [comment]
Hi, could I work on this? (this seems a nice way to get familiar with the source code). I went through the comments and the blog post and I think I have an understanding of the issue.

**Comment by rcurtin** [comment]
@riaash04 sure, anyone is welcome to work on this. :+1:

**Comment by abernauer** [comment]
@rcurtin  I' am going to tackle this issue this weekend. Does this to-do look good to you? 

- [ ] Make list of methods where pass-by-value change is implemented.
- [ ] Review codebase/methods where pass-by-value is relevant
- [ ] Convert to pass-by-value where parameters are always copied and moves are cheap.

**Comment by rcurtin** [comment]
@abernauer that seems like a reasonable approach to me.  You can take a look through the existing PRs that have already been merged to help identify any situations where the change should be made.

**Comment by abernauer** [comment]
Yeah I looked at the PR for decision tree. As a reference it was helpful.

**Comment by y2s82** [comment]
@rcurtin Can I take a crack at this?  Seems like a good reason to go through the code and study it.

**Comment by rcurtin** [comment]
Sure, feel free; if you open a PR, I'd suggest picking only one small bit of the code at a time (to make the review quicker).

**Comment by vipul-maheshwari** [comment]
Hi @rcurtin. After going through the documentation aand getting the gist of the proper and valid methods through the codebase, I came to this conclusion, let me know if I am wrong..

- The arma library is a kind of linear algebra library for C++ that provides functions for performing mathematical operations on matrices, vectors, and other types of data. In our  case, the code is defining methods that take in data of type `arma::mat` which is a matrix data type from the arma library.

- The first two methods, `Method(const arma::mat& data)` and `Method(arma::mat&& data)` are the old approaches, both methods take in a matrix data as input but the first one makes a copy of the data and the second one moves the data.

- The third method, `Method(arma::mat data)` is the refrained and proposed new approach which  allows the user to decide whether they want to make a copy of the data or move the data. If the user wants to make a copy of the data, they can call the function like this: `Method(data)`, but if they want to move the data instead of making a copy, they can call the function like this: `Method(std::move(data))`. This approach allows the user to have more control over the data and it also makes the codebase more efficient.

- For the sake of understanding it, let's take an example, let's say you have a matrix A and you want to pass it to the function 'Method()', with the old approach you have to decide whether to make a copy of the data or move it, with the new approach, you can call the function like this: 

`Method(A); // this will make a copy of the data`
`Method(std::move(A)); // this will move the data`

**Comment by shrit** [comment]
I disagree with why `const arma::mat& data` is making a copy of the data. it is passing it by reference, using the exact memory location.
Try to use `arma::mat data` on a huge dataset and good luck with the performance drawback that you will see.

**Comment by vipul-maheshwari** [comment]
Oh Sorry for the confusion,  The method const `arma::mat& data` is not creating a copy of the data instead it is passing it by reference, so it certainly means that it is using the same memory location as the original data, so it doesn't consume extra memory and also no performance drawback.

The method `arma::mat&& data `is also passing the data by reference but using rvalue references. After reading about it, I came to know that it is  C++11 feature, which allows to move resources instead of copying them, this method is used to optimize the performance of the code when dealing with large datasets.

**Comment by vipul-maheshwari** [comment]
> I disagree with why `const arma::mat& data` is making a copy of the data. it is passing it by reference, using the exact memory location. Try to use `arma::mat data` on a huge dataset and good luck with the performance drawback that you will see.

I am changing the previous response..

**Comment by vipul-maheshwari** [comment]
@shrit Is it correct now?

**Comment by shrit** [comment]
Not necessarily, rvalue reference is not a replacement or an improvement for lvalue reference.
Moving the ownership can result in a dangerous situation, this depends on the application.

**Comment by vipul-maheshwari** [comment]
> Not necessarily, rvalue reference is not a replacement or an improvement for lvalue reference. Moving the ownership can result in a dangerous situation, this depends on the application.

Yeah I mean Rvalue references are not a replacement or improvement for lvalue references. They are fairly used to optimize the performance of the code when dealing with large datasets, but it is not always the best choice I guess. Moving ownership of data can be dangerous in some situations as you mentioned, such as when the data is shared between multiple objects or when the data needs to be accessed after it has been moved.

So In this specific user cases, the new approach of `Method(arma::mat data)` which allows the user to decide whether they want to make a copy of the data or move the data, provides more flexibility and control over the data and it also makes the codebase more efficient but it is not always the best choice for sure, it depends on the application and the context.

It is important to consider the specific use case and the requirements of the application before choosing whether to use a lvalue reference, rvalue reference, or a copy of the data.

**Comment by vipul-maheshwari** [comment]
@shrit @matiu2  Is there anything I can do in the codebase? I will be more than happy to make the necessary changes! I don't know if this is already closed or still needs the proper changes?

**Comment by shrit** [comment]
@vipul-maheshwari would you explain to me what are you trying to optimize here? what is the performance gain? and how it is going to affect the code base?

**Comment by vipul-maheshwari** [comment]
> @vipul-maheshwari would you explain to me what are you trying to optimize here? what is the performance gain? and how it is going to affect the code base?

It might sound absurd why'd you asked in that way but ok, so the new approach of `Method(arma::mat data)` allows the user to decide whether to make a copy of the data or move the data. When the user decides to move the data using `std::move(data)`, it uses move semantics to transfer the ownership of the data from the original location to the function, this way, the data is not copied, and the original data is left in an unspecified state, it can't be used again. This can optimize the performance of the code when dealing with large datasets, because it avoids the time and memory overhead of copying the data.

**Comment by vipul-maheshwari** [comment]
> @vipul-maheshwari Our main focus currently is to work on making the documentation better, we have done a huge refactoring recently, and I would not encourage doing more refactoring for the sake of it, since you do not propose any performance gain I do not see it as important at this stage.

Sure, I will be happy to work on the Documentation if you want!! Let me know if I can

**Comment by lumi232** [comment]
Hey, why is this issue still open? If some changes are still required I'll be happy to make them.

**Comment by Roman-smokestack** [comment]
> Is this issue open if yes I would like to work on it





https://stackdev.space/questions/do-rvalue-references-receive-optimization-when-passed-through-functions
