### ISSUE TITLE
Compiling mlpack-2.2.3 on Arch Linux fails mlpackTest

### ISSUE THREAD

**Issue by vishalbelsare** [mlpack/mlpack#1025]
Compiling mlpack-2.2.3 on Arch Linux fails mlpackTest

```
[100%] Building CXX object src/mlpack/tests/CMakeFiles/mlpack_test.dir/timer_test.cpp.o
[100%] Linking CXX executable ../../../bin/mlpack_test
[100%] Built target mlpack_test
==> Starting check()...
[  1%] Updating gitversion.hpp (if necessary)
-- Found Git: /usr/bin/git (found version "2.13.1") 
-- gitversion.hpp is already up to date.
[  1%] Built target mlpack_gitversion
Moving header files to include/mlpack/
[  1%] Built target mlpack_headers
[  3%] Updating arma_config.hpp (if necessary)
[  3%] Built target mlpack_arma_config
[ 38%] Built target mlpack
[100%] Built target mlpack_test
Running 761 test cases...
/home/vishal/aur/mlpack/src/mlpack-mlpack-2.2.3/src/mlpack/tests/adaboost_test.cpp(113): fatal error: in "AdaBoostTest/WeakLearnerErrorIris": critical check error <= weakLearnerErrorRate has failed [0.040000000000000001 > 0.033333333333333333]

*** 1 failure is detected in the test module "mlpackTest"
==> ERROR: A failure occurred in check().
    Aborting...
```

**Comment by vishalbelsare** [comment]
After setting TEST_VERBOSE=ON

```
[100%] Building CXX object src/mlpack/tests/CMakeFiles/mlpack_test.dir/timer_test.cpp.o
[100%] Linking CXX executable ../../../bin/mlpack_test
[100%] Built target mlpack_test
==> Starting check()...
Running 761 test cases...
/home/vishal/aur/mlpack/src/mlpack-mlpack-2.2.3/src/mlpack/tests/adaboost_test.cpp(113): fatal error: in "AdaBoostTest/WeakLearnerErrorIris": critical check error <= weakLearnerErrorRate has failed [0.040000000000000001 > 0.033333333333333333]
[WARN ] RANN-RS: RANN guarantee fails on 0 queries.
[WARN ] RANN-TSS: RANN guarantee fails on 0 queries.
[WARN ] RANN-TSD: RANN guarantee fails on 0 queries.
[WARN ] RANN-TSS (cover tree): RANN guarantee fails on 0 queries.
[WARN ] RANN-TSD (cover tree): RANN guarantee fails on 0 queries.
[WARN ] Encountered singularity when adding variable 1 to active set; permanently removing.
[WARN ] Encountered singularity when adding variable 1 to active set; permanently removing.
[WARN ] Encountered singularity when adding variable 1 to active set; permanently removing.
[WARN ] Encountered singularity when adding variable 1 to active set; permanently removing.
[WARN ] Encountered singularity when adding variable 1 to active set; permanently removing.
[WARN ] Encountered singularity when adding variable 1 to active set; permanently removing.
[WARN ] Encountered singularity when adding variable 1 to active set; permanently removing.
[WARN ] Encountered singularity when adding variable 1 to active set; permanently removing.
[WARN ] Encountered singularity when adding variable 1 to active set; permanently removing.
[WARN ] Encountered singularity when adding variable 1 to active set; permanently removing.
[WARN ] Encountered singularity when adding variable 1 to active set; permanently removing.
[WARN ] Cannot open file 'noextension'; load failed.
[WARN ] No extension given with filename 'noextension'; type unknown.  Save failed.
[WARN ] Cannot open file 'nonexistentfile_______________.csv'; load failed.
[WARN ] 'test_file.csv' is not a standard csv file.
[WARN ] 'test_file.csv' is not a standard csv file.
[WARN ] Loading 'test_file.bin' as raw binary formatted data; but this may not be the actual filetype!
[WARN ] Attempted to save HDF5 data to 'test_file.h5', but Armadillo was compiled without HDF5 support.  Save failed.
[WARN ] Attempted to save HDF5 data to 'test_file.hdf5', but Armadillo was compiled without HDF5 support.  Save failed.
[WARN ] Attempted to save HDF5 data to 'test_file.hdf', but Armadillo was compiled without HDF5 support.  Save failed.
[WARN ] Attempted to save HDF5 data to 'test_file.he5', but Armadillo was compiled without HDF5 support.  Save failed.
[WARN ] L-BFGS line search direction is not a descent direction (terminating)!
[WARN ] L-BFGS line search direction is not a descent direction (terminating)!

*** 1 failure is detected in the test module "mlpackTest"
==> ERROR: A failure occurred in check().
    Aborting...
```

**Comment by rcurtin** [comment]
Hi Vishal,

This is a very strange error---the AdaBoost test failure indicates that AdaBoost is performing *worse* than the weak learners that it's built on, which should definitely not ever be the case, especially since there is no randomness in this test.  I have never seen this test fail in any other context, so maybe there is something unique about the environment in which you're running the test.

If I am understanding right, this output was given while building mlpack for the AUR.  Is it possible to try and reproduce a similar environment on a different system that also fails the test?

I don't have an Arch Linux system here, so I can't reproduce this myself, but if you are willing to get your hands dirty, we can try and reproduce it, then isolate what the actual problem is.  I can help guide you through the process; if you are familiar with C++, valgrind, and gdb, it should not be too hard. :)

**Comment by vishalbelsare** [comment]
Hi Ryan,
Thanks for the note. Yes, I was stumped myself see that - I had wondered whether openmp might be cause that, but was waiting to hear from someone. Now, if the test is deterministic that would be unlikely too.
I was working with the PKDGBUILD from AUR, but which I modified slightly to use the latest mlpack release (2.2.3), but nothing to cause such an upset.

To see whether something was up with AUR PKGBUILD (unlikely IMHO), I separately worked outside of the AUR and did a traditional untar->cmake->make sequence. And then I executed mlpack_test. Here's what I get this way:

```
[vishal@einstein build]$ bin/mlpack_test 
Running 761 test cases...
[WARN ] RANN-RS: RANN guarantee fails on 0 queries.
[WARN ] RANN-TSS: RANN guarantee fails on 0 queries.
[WARN ] RANN-TSD: RANN guarantee fails on 0 queries.
[WARN ] RANN-TSS (cover tree): RANN guarantee fails on 0 queries.
[WARN ] RANN-TSD (cover tree): RANN guarantee fails on 0 queries.
[WARN ] Encountered singularity when adding variable 1 to active set; permanently removing.
[WARN ] Encountered singularity when adding variable 1 to active set; permanently removing.
[WARN ] Encountered singularity when adding variable 1 to active set; permanently removing.
[WARN ] Encountered singularity when adding variable 1 to active set; permanently removing.
[WARN ] Encountered singularity when adding variable 1 to active set; permanently removing.
[WARN ] Encountered singularity when adding variable 1 to active set; permanently removing.
[WARN ] Encountered singularity when adding variable 1 to active set; permanently removing.
[WARN ] Encountered singularity when adding variable 1 to active set; permanently removing.
[WARN ] Encountered singularity when adding variable 1 to active set; permanently removing.
[WARN ] Encountered singularity when adding variable 1 to active set; permanently removing.
[WARN ] Encountered singularity when adding variable 1 to active set; permanently removing.
[WARN ] Cannot open file 'noextension'; load failed.
[WARN ] No extension given with filename 'noextension'; type unknown.  Save failed.
[WARN ] Cannot open file 'nonexistentfile_______________.csv'; load failed.
[WARN ] 'test_file.csv' is not a standard csv file.
[WARN ] 'test_file.csv' is not a standard csv file.
[WARN ] Loading 'test_file.bin' as raw binary formatted data; but this may not be the actual filetype!
[WARN ] Attempted to save HDF5 data to 'test_file.h5', but Armadillo was compiled without HDF5 support.  Save failed.
[WARN ] Attempted to save HDF5 data to 'test_file.hdf5', but Armadillo was compiled without HDF5 support.  Save failed.
[WARN ] Attempted to save HDF5 data to 'test_file.hdf', but Armadillo was compiled without HDF5 support.  Save failed.
[WARN ] Attempted to save HDF5 data to 'test_file.he5', but Armadillo was compiled without HDF5 support.  Save failed.
[WARN ] L-BFGS line search direction is not a descent direction (terminating)!
[WARN ] L-BFGS line search direction is not a descent direction (terminating)!
/home/vishal/src-bld/mlpack-2.2.3/src/mlpack/tests/nystroem_method_test.cpp(117): fatal error: in "NystroemMethodTest/Rank10Test": absolute value of normalizedFroAverage{615.01889440345735} exceeds 0.001

*** 1 failure is detected in the test module "mlpackTest"
[vishal@einstein build]$ 
```

So, outside of AUR, the fatal error seems to be "fatal error: in "NystroemMethodTest/Rank10Test": absolute value of normalizedFroAverage{615.01889440345735} exceeds 0.001"
Even stranger now?

I am willing to help you and anyone else to isolate what is going on here. I am an econometrics/statistics guy than developer, so valgrind / gdb would take work on my part, but I will do that, if you can provide input.

p.s: does the Adaboost test and Nystrom Method Test use some form of random sampling? I will try compiling this on an Ubuntu system tomorrow.

**Comment by rcurtin** [comment]
Unfortunately there are some tests that are known to fail occasionally; this is a problem we have been working to fix (see #922).  The Nystroem method test is one of those tests, so I wouldn't worry about that failure.

The only randomness in the Adaboost test is the initial weights used for the perceptrons.  To see if this was an issue, I added `math::RandomSeed(std::time(NULL))` to the beginning of the `WeakLearnerErrorIris` test in `adaboost_test.cpp`.  Then I ran the following script:

```
i=0; while(true); do echo $i; bin/mlpack_test -t AdaBoostTest/WeakLearnerErrorIris 2>&1 | grep "fatal error"; if [ "$?" != "1" ]; then break; fi; sleep 1; i=$(($i + 1)); done
```

That will run the test over and over again, stopping when the test finally fails.  I ran this for about a day, doing a total of 58147 tests, and none of them failed.  So either that AUR build is the unluckiest build in the world, or the problem is not caused by random initialization.  Realistically, also, there is no way a simple perceptron should outperform AdaBoost.

Personally I think that something about the AUR environment is causing the issue, but I am not sure what.  It could be the version of the compiler, the version of Boost, or the Armadillo version, or any number of other things.  In my opinion, the first thing to do will be to try and reproduce it.  If we can't reproduce it on AUR or any other system, then unfortunately I don't think there's any way we can solve it and we'll have to just shrug and move on I guess, possibly concluding that whatever machine the AUR was running on had some extremely low probability RAM bit flip or something.

Could you build mlpack 2.2.2 on AUR and see if it has the same problem?  There were no changes to the perceptron or AdaBoost code between 2.2.2 and 2.2.3.  Another idea would be to build the git master branch of mlpack on AUR and see if the test failure occurs there.  Past that, I guess testing on an Arch system with the same dependencies as AUR would be the next thing.  Then, once (or if) we can reproduce it, then we can dig deeper with valgrind or gdb to try and isolate what the actual issue is.

I tried running valgrind on the test on my system; there were no invalid accesses there, at least.

**Comment by vishalbelsare** [comment]
Hi Ryan, thanks. I think I have managed to narrow down a bit. I worked with a downloaded zip file of the master branch off Github. Compiled via makepkg using a PKGBUILD gave the error with Adaboost. However, the same source  but when compiled manually did not give that particular error. You were right to suggest that something in the AUR environment is likely to cause that error. So, I passed different flags in the PKGBUILD to set more generic options and override those in the makepkg.conf.

The makepkg.conf I use to build AUR packages has the following : 
```
CFLAGS="-march=native -mtune=native -O2 -pipe -fstack-protector-strong -frecord-gcc-switches"
CXXFLAGS="-march=native -mtune=native -O2 -pipe -fstack-protector-strong -frecord-gcc-switches"
```
I changed those to the following : 
```
#CFLAGS="-march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -frecord-gcc-switches"
#CXXFLAGS="-march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -frecord-gcc-switches"
```
That Adaboost related error does not make an appearance with the latter flags. However, the following error persists.
```
~/mlpack/tests/load_save_test.cpp(683): fatal error: in "LoadSaveTest/LoadHDF5Test": critical check test.n_rows == 4 has failed [2 != 4]
```

I think we can close this to the extent that the remaining error can be safely ignored. Thanks again and particularly for running 58,147 tests!

**Comment by rcurtin** [comment]
Hm, I think there may still be some problem here if the CFLAGS and CXXFLAGS cause a test to fail, but if the workaround is ok for you, then we can go with that.  For the HDF5 loading issue, it looks like something is loading transposed, but I am not sure why---maybe an HDF5 configuration issue?  HDF5 is a really complex library unfortunately.

Anyway, if you have more problems in the future, please feel free to open an issue.
