### ISSUE TITLE
How to expose Forward and Backward of FFN?

### ISSUE THREAD

**Issue by ShangtongZhang** [mlpack/mlpack#1028]
Basically I want to expose Forward and Backward of FFN and re-use existing optimizer. After reading the implementation of several optimizers and FFN, following is my idea, for each optimizer, we can add a new method called `Update(mat& parameters, mat& gradient)`, so we can manually compute the gradient using `Backward` and then pass the result to the optimizer to update the parameters (re-using `UpdatePolicy`). Until now I can see I'm able to do this for optimizers which have a `updatePolicy`. I'm not sure whether this idea works for those complicated optimizers. If not, can we accept that some optimizers don't have this `Update` API? And just for curiosity, what are those complicated optimizers used for? I assume few will use them in `ANN`. And, does anyone have a more elegant solution for this?

**Comment by zoq** [comment]
Couldn't we use the update policy e.g. ``VanillaUpdate`` or ``RMSPropUpdate`` instead of going through the optimizer class?

You could use LBFGS but a lot of people don't because of memory constraints, LBFGS stores/holds a couple of gradient evaluations, also LBFGS doesn't work with mini batches, which is often essential when training deep networks. Many people have tried to make LBFGS work in a stochastic setting, e.g. include line search but I'm not aware that the results are good enough to replace SGD.

**Comment by ShangtongZhang** [comment]
> Couldn't we use the update policy e.g. VanillaUpdate or RMSPropUpdate instead of going through the optimizer class?

That will be more easy to implement. But the extendability may be somehow hurt. E.g. if we want to make optimizers without a update policy compatible with this RL code in the future, it may be difficult. But I suspect this case will never happen. I don't think some one will use them in DeepRL. So I'm fine to use `UpdatePolicy` directly.

**Comment by zoq** [comment]
I agree, if someone likes to use another optimizer in combination with the DeepRL code, he has to implement an update policy.
