### ISSUE TITLE
Queries in the Paper inspiring RANN

### ISSUE THREAD

**Issue by naveenjafer** [mlpack/mlpack#1059]
Hi, I have been trying to understand the RANN package to possibly try to implement in a language of my choice as an exercise. This paper is the reference I have been using http://www.mlpack.org/papers/rann.pdf and I believe is the crude basis on which the entire RANN implementation is based.

I have a few queries regarding the Pseudo code that is presented in Figure 2 in the above paper, it would be great if someone could clarify the same for me.

I am interested in understanding specifically for the following scenario as a starter.
a) KD Tree.
b) Single Tree(Single query point)
c) K neighbors.

1) Is the initial value of ub(q) infinity?

2) The leaf can consist of possibly more than 1 item, why does the STRANN implementation indicate that if the node "R" is a leaf node, then BruteNN is the only possibility? I am unable to wrap my head around why an approximation should not be performed for the lead node.

3) Where is the nearest neighbor being stored in the pseudocode? Shouldn't this be a part of the BruteForceNN?

4) The entire pseudocode assumes the number of nearest neighbors that the user queries for is 1, right? I am a little confused about how it would change in the case of "k" neighbors needed.

**Comment by rcurtin** [comment]
Hi Naveen,

This question may have been more appropriate to ask the paper authors but I can try to answer it.

1.  Probably yes, but you should check the code in `ra_search_rules.hpp`.
2.  What is meant is that `BruteNN` will be performed over all points held in the leaf node.
3.  I did not write the pseudocode so I can't answer this one.
4.  You have to rework the algorithm for k > 1; it's almost never possible to fit that in the paper because it would make the entire algorithm way more complex.  If you are trying to understand the paper, that is probably a great exercise to test understanding. :)

**Comment by naveenjafer** [comment]
@rcurtin  Thank you, I will get in touch with the authors of the paper too to further clarify :)

**Comment by rcurtin** [comment]
Sounds good---I'll go ahead and close this then. :)
