### ISSUE TITLE
Documentation needs to be clarified

### ISSUE THREAD

**Issue by Prabhat-IIT** [mlpack/mlpack#1232]
In the [allow_empty_clusters section of documentation](http://www.mlpack.org/docs/mlpack-2.2.5/doxygen/kmtutorial.html) it is written that 

> when you save your clusters, some of the clusters may be filled with NaNs. This is expected behavior – if a cluster has no points, the concept of a centroid makes no sense.

whereas in [EmptyCluster section of Documentation](http://www.mlpack.org/docs/mlpack-2.2.5/doxygen/classmlpack_1_1kmeans_1_1AllowEmptyClusters.html) it is stated that

> This function allows empty clusters to persist simply by leaving the empty cluster in its last position.

As `allow_empty_clusters` is the default constructor used for this policy of `EmptyCluster()` then I think we will not get any Nans when we save our clusters. I've experimented with several data sets and various values of clusters and I didn't get Nan even a single time. 

Moreover, it would be great if we could add a section of `kill_empty_clusters` to [command line kmeans](http://www.mlpack.org/docs/mlpack-2.2.5/doxygen/kmtutorial.html) describing how it will fill the results with `DBL_MAX` in case of empty clusters

**Comment by rcurtin** [comment]
I agree, the documentation seems to be off here.  Thank you for digging in and pointing that out.

I think that we should update the documentation: empty clusters will not be filled with NaNs (or DBL_MAX) if `allow_empty_clusters`.  I might suggest something more like

> Note that when you save your clusters, even empty clusters will still have centroids.  The centroids of the empty cluster will be the same as what they were on the last iteration the cluster was not empty.

(or similar)

For `kill_empty_clusters`, I agree, it would be nice add another example to the k-means tutorial.  Another thing we might consider doing is modifying the `KMeans` code so that any empty clusters are completely removed.  (This could be done either in `KMeans`, which would be the nicer way to do it but would likely require a little bit of changing abstractions, like adding another function to `AllowEmptyClusters` and `KillEmptyClusters`; or it could be done in `kmeans_main.cpp`, which would be a little easier but less flexible in my opinion.)

I know that you only set out to write tests for the k-means program, but I think it is common that during this process we find some additional bugs that need to be fixed... :)

**Comment by Prabhat-IIT** [comment]
Thanks for some good suggestions @rcurtin . As soon as I get some time I'll fix these bugs. Actually, my exams are going to start so I'm slowing down. Sorry  for that!
