### ISSUE TITLE
Nearest neighbors with spill trees in dualtree mode does not always return neighbors

### ISSUE THREAD

**Issue by vasiloglou** [mlpack/mlpack#1269]
I have noticed that if the k is big the dual tree algorithm will return max float distances and invalid indices. This probably happens because some leaf nodes do not have enough points

**Comment by akhandait** [comment]
Yes, you are right, I was righting tests for nearest neighbors bindings in #1263 when I noticed this.
As discussed on that pull request, I am working on the solution. :)

**Comment by rcurtin** [comment]
For anyone looking to contribute, this is a semi-challenging issue that requires some knowledge of how nearest neighbor works with spill trees.  You can reproduce @vasiloglou's original issue by running the following command once you've built mlpack:

```
mlpack_knn -i test_data_3_1000.csv --leaf_size 5 -t spill -k 10 -n n.csv -d d.csv -v -a single_tree
```

This runs k-nearest-neighbor search in single-tree mode using spill trees with a leaf size of 5.  (So, every leaf in the spill tree contains 5 or fewer points.)  But you can see in `n.csv` and `d.csv` (the result files), that many of the indices of nearest neighbors are invalid!  The reason for this is that the single-tree traverser for spill trees (in `src/mlpack/core/tree/spill_tree/spill_single_tree_traverser.hpp`), which will be run with `Defeatist = true`, never actually encounters enough points to add to the results!  This is because the algorithm will traverse to the nearest leaf, then run the base cases to find the nearest neighbor.  But since `leaf_size` is only 5, and we are looking for 10 neighbors, we are guaranteed that will find at most 5 nearest neighbors!

The task here, then, is to modify the code such that enough results are always returned for the defeatist spill tree single-tree traverser, and the defeatist spill tree dual-tree traverser---the problem also happens when using `-a dual_tree`.

**Comment by UTpH** [comment]
Hello!
I'm looking to contribute to this project. Could I work on this if it is not already taken?

**Comment by zoq** [comment]
Hello @UTpH , no one is working on this one right now, so please feel free to pick this up.

**Comment by shashank-007** [comment]
@rcurtin 
```
mlpack_knn -i test_data_3_1000.csv --leaf_size 5 -t spill -k 10 -n n.csv -d d.csv -v -a single_tree
```
this command throws error 
```
[FATAL] Unable to detect type of 'test_data_3_1000.csv'; incorrect extension?
```

**Comment by rcurtin** [comment]
@shashank-007: does the file exist?

**Comment by shashank-007** [comment]
@rcurtin yea,file does exist .

**Comment by whoopityDoop** [comment]
@rcurtin so when k>leaf_size this occurs too but after varying k size so from 2 to 5 and from 5 to 11 here are the results. also the error is a big one because if we keep k the same only the max float values increases ..
![screenshot from 2019-02-25 12-53-07](https://user-images.githubusercontent.com/20016369/53320896-03043700-38fd-11e9-9e79-da47c93fc418.png)
![screenshot from 2019-02-25 12-53-39](https://user-images.githubusercontent.com/20016369/53320917-11525300-38fd-11e9-9fcc-3c020947da6d.png)
![screenshot from 2019-02-25 12-53-56](https://user-images.githubusercontent.com/20016369/53320947-229b5f80-38fd-11e9-8be6-f9fa515dea86.png)
![screenshot from 2019-02-25 12-54-11](https://user-images.githubusercontent.com/20016369/53320972-38108980-38fd-11e9-99d6-1cc5c595ca3c.png)
![screenshot from 2019-02-25 12-55-36](https://user-images.githubusercontent.com/20016369/53321012-52e2fe00-38fd-11e9-9c03-90935369b2bf.png)
![screenshot from 2019-02-25 12-55-36](https://user-images.githubusercontent.com/20016369/53321042-5ecec000-38fd-11e9-8c18-50d5525656d6.png)
![screenshot from 2019-02-25 12-55-47](https://user-images.githubusercontent.com/20016369/53321070-7312bd00-38fd-11e9-9269-66e3ca4cd724.png)
![screenshot from 2019-02-25 12-56-04](https://user-images.githubusercontent.com/20016369/53321083-7d34bb80-38fd-11e9-80d1-18036355dc34.png)

this is happening even for when leaf size is less than n or equal ..

**Comment by rcurtin** [comment]
`k == n` should not be allowed for cases where we have only a reference set, since it is not possible to return enough neighbors---the maximum we can return is (n - 1).  Otherwise your observations are correct and confirm the bug.

**Comment by whoopityDoop** [comment]
@rcurtin how should i proceed into finding the bug ??

**Comment by ameyanator** [comment]
Hi, is this issue resolved?

**Comment by rcurtin** [comment]
@ameyanator it is not fixed yet, so you're welcome to work on it.  You can take a look at the original comments that I left up at the top for guidance.

**Comment by ameyanator** [comment]
@rcurtin I'll do that sure! Will ask over here if I want to about anything else

**Comment by rcurtin** [comment]
@vasiloglou sorry that this took so long!  It should be fixed now.  We can celebrate with Cafe Agora next time we run into each other. :smile:
