### ISSUE TITLE
examples

### ISSUE THREAD

**Issue by Jiewen2017** [mlpack/mlpack#1305]
Hi, could you provide some examples and data for us to use? thanks!

**Comment by zoq** [comment]
There are a couple of helpful links:

- Tutorials: http://www.mlpack.org/docs.html
- Tests: https://github.com/mlpack/mlpack/tree/master/src/mlpack/tests
- Test data: https://github.com/mlpack/mlpack/tree/master/src/mlpack/tests/data

**Comment by rickllyxu** [comment]
A superfluous suggestion: remember to run `g++ input.cpp -std=c++11 -larmadillo -lmlpack`.
May be helpful for later users.

**Comment by rcurtin** [comment]
@rickllyxu: thanks for the suggestion; I'll be redoing the guide and tutorials soon, and I'll make sure that an actual command to compile is in the documentation.  I agree that could be helpful.

I'm going to go ahead and close this issue for inactivity, since it seems like the original question is answered.
