### ISSUE TITLE
[JOSS] Add dependencies and installation instructions to main website

### ISSUE THREAD

**Issue by mlgill** [mlpack/mlpack#1404]
@rcurtin I see the list of dependencies on GitHub [here](https://github.com/mlpack/mlpack/blob/master/README.md#3-dependencies) followed by installation instructions. Would it be possible to add this information (or a link to the GitHub dependencies) and on the main website [here](http://www.mlpack.org/) somewhere after the download links, etc?

**Comment by rasbt** [comment]
I found a list of the dependencies on the documentation website following the links:

http://www.mlpack.org => docs => read the mlpack tutorials => Building mlpack From Source => Dependencies of mlpack

However, I agree that it would be nice to have a more obvious place for installation instructions and requirements. Ideally as a link in the navbar on http://www.mlpack.org or via a link like "Installation Instructions" on the http://www.mlpack.org/docs page.

**Comment by rcurtin** [comment]
I added a link to "build instructions" on the http://www.mlpack.org/download.html page; since you already have to go to that page to download the source, I think it's reasonable to put it right below the links for downloading the source.

Let me know if you think that's reasonable---I'll go ahead close this issue since I think it is handled.

Thanks for pointing it out! :)
