### ISSUE TITLE
linear_regression

### ISSUE THREAD

**Issue by sungliner** [mlpack/mlpack#1426]
this is my code:

```
#include <mlpack/core.hpp>
#include <mlpack/methods/linear_regression/linear_regression.hpp>

using namespace mlpack;
using namespace std;
using namespace mlpack::regression;

int main() {
    arma::mat data;
    arma::rowvec responses;

    data::Load("regressionInputs.csv", data, true);
    LinearRegression lr(data, responses);
   
    arma::mat points;
    arma::rowvec predictions;
    data::Load("predict.csv", points, true);
 
    lr.Predict(points, predictions);
    for (size_t i = 0; i < predictions.n_elem; ++i)
    {
        std::cout << "the prediction of test data " << i << " is "
                  << predictions[i] <<  ".\n";
    }        
}
```

but i cant get the right predictions,dont know why

**Comment by rcurtin** [comment]
Hi there,

I don't know why either, since I don't have your dataset.  The code looks fine.  Linear regression isn't always guaranteed to get the right solution, so do you have a reason to believe that the model is not performing as well as it should?

If performance is not good enough you may also consider LARS or playing with the LinearRegression regularization parameter (so that it is ridge regression).

**Comment by sungliner** [comment]
thank  for your response first!
my traindata ls a simple matrix
1,1,4
2,2,8
3,3,12
5,5,20
4,4,16
my predictdata ls a simple matrix
8,8
9,9
10,10
 but the prediction i got is always 
0  0  0

**Comment by rcurtin** [comment]
Sorry for the slow response---I was on vacation last week.  I see that the `responses` vector is never being set when you construct the object `lr`.  I think maybe you are missing the following code after the `data::Load()` call:

```
responses = data.row(data.n_rows - 1);
data.shed_row(data.n_rows - 1);
```

(I haven't tested that, but I think it will work.)

**Comment by rcurtin** [comment]
I'll go ahead and close this for inactivity.  If you need, please feel free to reopen it.
