### ISSUE TITLE
predict the closest cluster belonging to input vector

### ISSUE THREAD

**Issue by RonakDedhiya** [mlpack/mlpack#1453]
Hello,
I used kmeans clustering(elkan) algorithm with mahalanobis distance to create around 2000 cluster for my application. It took me alot of time to get these cluster, its centroids. 
I want to know cluster assignment for new data values but there is no function available wherein there would be no training and just cluster assignment.
Please help me how shall I do this with available functionality???

**Comment by rcurtin** [comment]
Hey there,

If Elkan's algorithm was slow I might recommend trying Hamerly's algorithm or one of the tree-based algorithm.  The dualtree algorithm may be useful if the data is of low(ish) dimensionality, since you are searching for many clusters.

My suggestion would be to use k-nearest-neighbor search for this, with the cluster centroids as your reference set and your new points as the query set.  That will return to you the indices of the nearest cluster centroid, which is exactly the cluster assignment of each point that you are looking for.

I hope this helps!  Let me know if I can clarify.

**Comment by RonakDedhiya** [comment]
Hello,
Thanks for the suggestion.
I have tried the above suggestion and used k nearest neighbor. But
unfortunately it didn't worked with Mahalanobis Distance metric type.
Mahalanobis distance dont work with tree algorithms, I have tried with
kmeans and dualtree algorithm. With both I have got this error!!!

/usr/local/include/mlpack/core/tree/hrectbound_impl.hpp:243:27: error:
‘Power’ is not a member of ‘mlpack::metric::MahalanobisDistance<true>’
     if (MetricType::Power == 1)
                           ^
/usr/local/include/mlpack/core/tree/hrectbound_impl.hpp:245:32: error:
‘Power’ is not a member of ‘mlpack::metric::MahalanobisDistance<true>’
     else if (MetricType::Power == 2)
                                ^
/usr/local/include/mlpack/core/tree/hrectbound_impl.hpp:252:17: error:
‘Power’ is not a member of ‘mlpack::metric::MahalanobisDistance<true>’
       sum += pow((lower + fabs(lower)) + (higher + fabs(higher)),
                 ^
/usr/local/include/mlpack/core/tree/hrectbound_impl.hpp:262:25: error:
‘Power’ is not a member of ‘mlpack::metric::MahalanobisDistance<true>’
   if (MetricType::Power == 1)
                         ^
/usr/local/include/mlpack/core/tree/hrectbound_impl.hpp:264:30: error:
‘Power’ is not a member of ‘mlpack::metric::MahalanobisDistance<true>’
   else if (MetricType::Power == 2)
                              ^
/usr/local/include/mlpack/core/tree/hrectbound_impl.hpp:266:5: error:
‘TakeRoot’ is not a member of ‘mlpack::metric::MahalanobisDistance<true>’
     if (MetricType::TakeRoot)
     ^
/usr/local/include/mlpack/core/tree/hrectbound_impl.hpp:273:5: error:
‘TakeRoot’ is not a member of ‘mlpack::metric::MahalanobisDistance<true>’
     if (MetricType::TakeRoot)
     ^
/usr/local/include/mlpack/core/tree/hrectbound_impl.hpp:275:15: error:
‘Power’ is not a member of ‘mlpack::metric::MahalanobisDistance<true>’
           1.0 / (double) MetricType::Power) / 2.0;
               ^
/usr/local/include/mlpack/core/tree/hrectbound_impl.hpp:277:23: error:
‘Power’ is not a member of ‘mlpack::metric::MahalanobisDistance<true>’
       return sum / pow(2.0, MetricType::Power);

**Comment by rcurtin** [comment]
If you'd like to use the Mahalanobis distance, you're better off just transforming your data beforehand.  Note that a Mahalanobis distance `d_M(x, y) = (x - y)^T M (x - y)`.

So if you find L such that `M = L^T L`, then taking the non-Mahalanobis distance `d(Lx, Ly)`, you get the same result.

In my experiments it was faster to just multiply my data by `L` instead of using the Mahalanobis distance directly in the trees.

I'll leave this issue open until I have the chance to confirm that what I've written here ends up in the documentation for the `MahalanovmbisDistance` class.

**Comment by rcurtin** [comment]
With #1459 merged, this is closed, but if you are having problems still please do not hesitate and we can reopen it. :)
