### ISSUE TITLE
Minor Windows installer fixes/changes

### ISSUE THREAD

**Issue by rcurtin** [mlpack/mlpack#1506]
These are just a few leftover changes from #1485.  They aren't high priority but I don't think any of them are too hard.

1. Higher resolution image that looks less blurry.  https://github.com/mlpack/mlpack/pull/1485#issuecomment-417945989
2. Wrapped lines for AppVeyor config.  (Not totally sure if this will work.)  https://github.com/mlpack/mlpack/pull/1485#discussion_r214467616
3. Use git version in build number by parsing gitversion.hpp if it exists.  https://github.com/mlpack/mlpack/pull/1485#discussion_r214466275

This could be a nice intro task for someone with some Windows knowledge who wants to contribute.

**Comment by gmanlan** [comment]
Another improvement might be to remove the *_test.exe and the test dependency (boost_unit_test_framework-vc140-mt-1_60.dll). Having the test in the installer may not be that useful (and it fails anyways because it can't find many test files).

**Comment by KimSangYeon-DGU** [comment]
Hi @rcurtin. In work list, the 1 and 2 have been done and the 3 almost has been done. To use the git version in build, the version should be `x.x.x.x` or `x.x.x` format(x is integer from 0 to 655). However, the git version is 7 hexadecimal string, so we should convert this string to x.x.x.x format. So, I have a idea on converting it. **Combine two words into a integer number**. Below is example. Let's assume the git version is `abcd207`.
`
1. User's git version is **abcd207**.
2. Add the end of git version to '0' (like padding).
3. So changed git version is **abcd2070**
4. A binary of **a**, and **b** is 1010 and 1011 respectively, so it can be 1010 1011 (171)
5. Likewise, the rest of pair can be converted to 205, 32, and 112.
6. As a result, the git version abcd207 can be converted to 171.205.32.112.
`
Thus, we can distinguish between `git version` and `official mlpack version` using the number of `x`. (if the number of `x` is 3, it is `official mlpack version`, otherwise it is 'git version')
So, is it proper way to converting it??

**Comment by rcurtin** [comment]
Hehe, @KimSangYeon-DGU, thanks for the extensive analysis.  But I was thinking something much simpler, just like we do for existing Linux builds. :)  Basically we just use the git hash... so if the hash is `b23d5ce` then the version is `mlpack git-b23d5ce`.  CMake will already generate `${CMAKE_BINARY_DIR}/src/mlpack/core/util/gitversion.hpp`, which will have this text in it, so I think the only thing to do would be to use a line in the AppVeyor config in order to extract that text and modify the WiX configuration accordingly.

**Comment by rcurtin** [comment]
With #1506 merged, we can close this now.  Thanks @KimSangYeon-DGU! :+1:
