### ISSUE TITLE
LinearRegression out of memory

### ISSUE THREAD

**Issue by cloudray8580** [mlpack/mlpack#1517]
Hi, I'm new to mlpack. I'm trying to use linear regression to have a test on my .csv file. I'm using VS2017 for coding. The codes are shown below:
```
mat data;
bool loaded = mlpack::data::Load("C:/Users/Cloud/Desktop/LearnIndex/data/HilbertSortedPOIs2.csv", data);
arma::rowvec responses = data.row(data.n_rows - 1);
data.shed_row(data.n_rows - 1);
LinearRegression lr(data, responses);
```

Where the .csv file has about 1M rows and 6 columns. When I run the above codes, there is an error "error: arma::memory::acquire(): out of memory". I have a look into the call stack and find that the Q matrix in QR decomposition set its size to be (1M, 1M), which is definitely much larger than the size of my memory (16G). 

I'm wondering is there any way to run the LR with my dataset? Or I'm not using the right way for this?
Can anyone help me with this? Thanks.

**Comment by rcurtin** [comment]
I think I just fixed this issue recently in master, but there hasn't yet been a 3.0.4 release to incorporate that fix.  That's been on my todo list for... too long... but I'm tapped out until probably at least Oct. 19th to release a new version.

Here's the mailing list thread where the issue was brought up:

http://knife.lugatgt.org/pipermail/mlpack/2018-August/003778.html

The new code doesn't use a QR decomposition, it just calls `arma::solve()`, which I think will in general do something a little smarter.

Can you try again with the git master branch?  (Alternately, if you can wait until I can release the new version, that could work too.)

**Comment by rcurtin** [comment]
I'm going to close this for inactivity.  If you're still having problems, feel free to reopen it.
