### ISSUE TITLE
Fail in building MLPACK with MS Visual Studio 2015

### ISSUE THREAD

**Issue by jbensabat** [mlpack/mlpack#1524]
Hello 
I have tried to build mlpack following the instructions. 
I managed to download the packages (openblas and boost libs)
however CMake fails in the configuration phase of mlpack 
one of the errors is that boost libs are missing but they are there 
is there any consistent and complete guide on how to install mlapck from MSVC ?
thanks
jac

**Comment by rcurtin** [comment]
Did you try reading http://www.mlpack.org/docs/mlpack-git/doxygen/build_windows.html ?

**Comment by jbensabat** [comment]
Hi
Thanks for your message
This is where I started from
Best
Jac


Jacob Bensabat, PH.D.
CTO
EWRE Ltd.
Tel: +972-4-8383919.
Fax: +972-4-8387621.
Mobile: +972-544-417511.

**Comment by rcurtin** [comment]
Ok, well, I can try and help out if you provide some details on what you have done.  That tutorial page I linked you to was just created and tested recently, so it should work.

**Comment by jbensabat** [comment]
Hi
This is what I have done


1.       Creating the mlpack directory , then mlpack-3.0.3

2.       Unpacked the mlpack-master.zip to mlpack-3.0.3

3.       Created a MSVC solution from code – named mlpack in directory mlpack-3.0.3

4.       Used NuGet to download openblas and boost (version 1.68.00)

5.       Put all the compile boost libs inside a directory called boost_libs within the packages directory

6.       Put all the compiled libs into one lib

7.       create a directory armadillo inside mlpack

8.       download and unpacked armadillo into the armadillo directory

9.       created a build directory inside armadillo

tried to run the following bacth

cmake -G "Visual Studio 14 2015 Win64" ^
-DBLAS_LIBRARY:FILEPATH="C:/software/mlpack/mlpack-3.0.3/packages/OpenBLAS.0.2.14.1/lib/native/lib/x64/libopenblas.dll.a" ^
-DLAPACK_LIBRARY:FILEPATH="C:/software/mlpack/mlpack-3.0.3/packages/OpenBLAS.0.2.14.1/lib/native/lib/x64/libopenblas.dll.a" ^
-DCMAKE_PREFIX:FILEPATH="C:/software/mlpack/armadillo" ^
-DBUILD_SHARED_LIBS=OFF ..

I got an error – Cmakelists.txt is not present in the build directory.
Then I moved the batch file to the root directory of armadillo and I was able to build armadillo

I created a build directory inside mlpack-3.0.3
Then I tried to run the following batch

cmake -G "Visual Studio 14 2015 Win64" ^
-DBLAS_LIBRARY:FILEPATH="C:/software/mlpack/mlpack-3.0.3/packages/OpenBLAS.0.2.14.1/lib/native/lib/x64/libopenblas.dll.a"  ^
-DLAPACK_LIBRARY:FILEPATH="C:/software/mlpack/mlpack-3.0.3/packages/OpenBLAS.0.2.14.1/lib/native/lib/x64/libopenblas.dll.a" ^
-DARMADILLO_INCLUDE_DIR="C:/software/mlpack/armadillo/include" ^
-DARMADILLO_LIBRARY:FILEPATH="C:/software/mlpack/armadillo/Debug/armadillo.lib" ^
-DBOOST_INCLUDEDIR:PATH="C:\Software\mlpack\mlpack-3.0.3\packages\boost.1.68.0.0\lib\native\include" ^
-DBOOST_LIBRARYDIR:PATH="C:\Software\mlpack\mlpack-3.0.3\packages\boost_libs" ^
-DDEBUG=OFF  ^
-DPROFILE=OFF ..


The last script produced errors, once of them was that the three boost libs were not present boost_program_options, boost_serialization and boost_unit_test_framework

The names of the libs in the boost_libs directories are

boost_math_c99-vc140-mt-gd-x64-1_68.lib
boost_math_c99-vc140-mt-x64-1_68.lib

etc

maybe it is expecting different names ?
best
jac



Jacob Bensabat, PH.D.
CTO
EWRE Ltd.
Tel: +972-4-8383919.
Fax: +972-4-8387621.
Mobile: +972-544-417511.

**Comment by rcurtin** [comment]
I see that you're using Boost 1.68, this could be the issue.  If you take a look in the `CMakeLists.txt` in the root of the project, you can find the following lines:

```
set(Boost_ADDITIONAL_VERSIONS
  "1.66.0" "1.66"
  "1.65.1" "1.65.0" "1.65"
  "1.64.1" "1.64.0" "1.64"
  "1.63.1" "1.63.0" "1.63"
  "1.62.1" "1.62.0" "1.62"
  "1.61.1" "1.61.0" "1.61"
  "1.60.1" "1.60.0" "1.60"
  "1.59.1" "1.59.0" "1.59"
  "1.58.1" "1.58.0" "1.58"
  "1.57.1" "1.57.0" "1.57"
  "1.56.1" "1.56.0" "1.56"
  "1.55.1" "1.55.0" "1.55"
  "1.54.1" "1.54.0" "1.54"
  "1.53.1" "1.53.0" "1.53"
  "1.52.1" "1.52.0" "1.52"
  "1.51.1" "1.51.0" "1.51"
  "1.50.1" "1.50.0" "1.50"
  "1.49.1" "1.49.0" "1.49")
```

Can you try adding "1.68" and "1.68.0" to the beginning of that list?  Unfortunately CMake does not handle new versions of Boost very well and this is sometimes necessary if a new version of Boost has been released since the last release of mlpack.

**Comment by jbensabat** [comment]
Thanks
Will try
Jac


Jacob Bensabat, PH.D.
CTO
EWRE Ltd.
Tel: +972-4-8383919.
Fax: +972-4-8387621.
Mobile: +972-544-417511.

**Comment by jbensabat** [comment]
Hi
I amended the CMakelists.txt file so it includes the new version of boost but it failed
I then deleted everything and stated from scratch this time with boost 1_66_0
I got also an error

He did not find three boost libs


-        "boost_program_options"

-        "boost_unit_test_framework"

-        "boost_serialization"

It seems that the problem is not the version but how cmake expects the name of these libs.

Any suggestions ?
Thanks
Jac


Jacob Bensabat, PH.D.
CTO
EWRE Ltd.
Tel: +972-4-8383919.
Fax: +972-4-8387621.
Mobile: +972-544-417511.

**Comment by zoq** [comment]
Can you post
- the modified ``CMakelists.txt`` file
- the files that are in boost libs folder
- cmake command you used to configure mlpack

**Comment by rcurtin** [comment]
Another issue (#1514) also suggested that this works with Boost 1.64... if you'd like to try that also, it could be a fix.

**Comment by jbensabat** [comment]
Hi
CMakelists.txt is attached
List of files in the boost libs folder attached
CMake Command


cmake -G "Visual Studio 14 2015 Win64" ^
-DBLAS_LIBRARY:FILEPATH="C:/software/mlpack/mlpack-3.0.3/packages/OpenBLAS.0.2.14.1/lib/native/lib/x64/libopenblas.dll.a"  ^
-DLAPACK_LIBRARY:FILEPATH="C:/software/mlpack/mlpack-3.0.3/packages/OpenBLAS.0.2.14.1/lib/native/lib/x64/libopenblas.dll.a" ^
-DARMADILLO_INCLUDE_DIR="C:/software/mlpack/armadillo/include" ^
-DARMADILLO_LIBRARY:FILEPATH="C:/software/mlpack/armadillo/Debug/armadillo.lib" ^
-DBOOST_INCLUDEDIR:PATH="C:\local\boost_1_66_0" ^
-DBOOST_LIBRARYDIR:PATH="C:\Software\mlpack\mlpack-3.0.3\packages\boost_libs" ^
-DDEBUG=OFF  ^
-DPROFILE=OFF ..


Thanks
ja



Jacob Bensabat, PH.D.
CTO
EWRE Ltd.
Tel: +972-4-8383919.
Fax: +972-4-8387621.
Mobile: +972-544-417511.

**Comment by jbensabat** [comment]
Go it ☺
Thanks
Jac


Jacob Bensabat, PH.D.
CTO
EWRE Ltd.
Tel: +972-4-8383919.
Fax: +972-4-8387621.
Mobile: +972-544-417511.

**Comment by rcurtin** [comment]
So you mean that you got it working with Boost 1.64?

(By the way... getting CMake to find Bpost right, especially on Windows, has always been a nightmare... :( )

**Comment by jbensabat** [comment]
Not yet but I am confident that this resolves the problem
Indeed CMake is beautiful on the paper and sometimes it works.
Best
Jac


Jacob Bensabat, PH.D.
CTO
EWRE Ltd.
Tel: +972-4-8383919.
Fax: +972-4-8387621.
Mobile: +972-544-417511.

**Comment by jbensabat** [comment]
Hi
Tried  with boost_1_64_0
Still does find the libs
Best
Jac


Jacob Bensabat, PH.D.
CTO
EWRE Ltd.
Tel: +972-4-8383919.
Fax: +972-4-8387621.
Mobile: +972-544-417511.

**Comment by jbensabat** [comment]
Still fails
Best
Jac

Sent from my iPhone

On 11 Oct 2018, at 16:52, Jbensabat <jbensabat@ewre.com<mailto:jbensabat@ewre.com>> wrote:

Hi
Tried  with boost_1_64_0
Still does find the libs
Best
Jac


Jacob Bensabat, PH.D.
CTO
EWRE Ltd.
Tel: +972-4-8383919.
Fax: +972-4-8387621.
Mobile: +972-544-417511.

**Comment by zoq** [comment]
Looks like this issue is known: https://gitlab.kitware.com/cmake/cmake/issues/17575

can you download https://gitlab.kitware.com/cmake/cmake/blob/6297d6c7fd6f80dafe17c0aefeeb0439432aa4b0/Modules/FindBoost.cmake and put it into ``mlpack/CMake/`` and see if that helps to find the necessary libs.

**Comment by jbensabat** [comment]
Hi
I tried and it did not work
I also downloaded the newest version of CMake which recognizes the newer versions of boost., with and without the FindBoost.Cmake script.
It did not work.
I went through the FindBoost. It seems to me that there is an incompatibility between the names of the libraries as we get them from the boost installation available in sourceforge and the way CMake expects them
Best
Jac


Jacob Bensabat, PH.D.
CTO
EWRE Ltd.
Tel: +972-4-8383919.
Fax: +972-4-8387621.
Mobile: +972-544-417511.

**Comment by jbensabat** [comment]
I finally managed to build mlpack opting for an alternative route.

I installed Cmake 3.13.0 (last version)
I used the GUI instead of the command line
I then provided manually the boost libraries and the openblas (for blas, lapack and openblas)
And it worked.
Thank you for your help

Could you please indicate a good example/tutorial of time series analysis and prediction that I could start from
Best
Jac



Jacob Bensabat, PH.D.
CTO
EWRE Ltd.
Tel: +972-4-8383919.
Fax: +972-4-8387621.
Mobile: +972-544-417511.

**Comment by jbensabat** [comment]
Hello
Still one obstacle
I managed to complete the configuration and project generation
However, when I try to build the library I get the following error

cl : Command line error D8021: invalid numeric argument '/Wno-unknown-pragmas'

this happens even with the file "version.cpp" , which has basically very simple includes

so it must be one of the arguments in the command line

/GS /TP /W0 /Zc:wchar_t /I"C:\Software\mlpack\mlpack-3.0.3\src" /I"C:\local\boost_1_66_0" /I"C:\Software\mlpack\armadillo\include" /I"C:\Software\mlpack\mlpack-3.0.3\bin\src\mlpack\.." /Zi /Gm- /Od /Ob0 /Fd"mlpack.dir\Debug\vc140.pdb" /Zc:inline /D "WIN32" /D "_WINDOWS" /D "CMAKE_INTDIR=\"Debug\"" /D "mlpack_EXPORTS" /D "_WINDLL" /D "_MBCS" /errorReport:prompt /WX- /Zc:forScope /RTC1 /GR /Gd /MDd /Fa"Debug/" /EHsc /nologo /Fo"mlpack.dir\Debug\" /Fp"mlpack.dir\Debug\mlpack.pch"


Any idea about what is wrong ?

Best
Jac

Jacob Bensabat, PH.D.
CTO
EWRE Ltd.
Tel: +972-4-8383919.
Fax: +972-4-8387621.
Mobile: +972-544-417511.

**Comment by jbensabat** [comment]
Hello
I do not know if this is of interest to anybody but I managed to build mlpack using visual studio 2015.
I installed the new version of cmake 3.13.0 (it is aware of the newest versions of boost)
I downloaded openblas using NuGet
I downloaded the binary build of boost, version 14.0 or boost_1_66_0-msvc-14.0-64.exe. For some reason I got errors  with
version 14.1 , boost_1_66_0-msvc-14.1-64.exe
I downloaded the source boost_1_66_0

When clicking "configure" make sure to select the 64 bit version
At the beginning the GUI asks for the location of the libraries. Once it is provided, the configuration is completed,
Then click Generate
Then open project

Best regards
Jac


Jacob Bensabat, PH.D.
CTO
EWRE Ltd.
Tel: +972-4-8383919.
Fax: +972-4-8387621.
Mobile: +972-544-417511.

**Comment by zsogitbe** [comment]
I think that you should change the document http://www.mlpack.org/docs/mlpack-git/doxygen/build_windows.html to something which always works. I see a lot of similar issues.

Very simply put one should follow on Windows something like this (off the top of my head):

1. Download and extract all necessary source code (Armadillo, MKL or openBLAS, boost, mlpack) in sub directories of your choice.
2. Install MKL (recommended!) if chosen instead of OpenBLAS.
3. Use the Windows GUI (!) version of CMake and generate VS solution files for Armadillo. Compile Armadillo.
4. Use the Windows GUI (!) version of CMake and generate VS solution files for mlpack. Add the boost, Armadillo and MKL/OpenBLAS source code directory folders to the CMake configuration, etc. The trick with boost is that you should add the source code instead of linking to a DLL and use the preprocessor directive BOOST_ALL_NO_LIB ! In this way you can use any version of boost and you will not have problems with versioning!

I have done this the first time I have compiled mlpack and it was compiled in 10 min.

Concerning the examples and tutorials I have a template VS solution file with a script which generates the solution automatically without CMake. Let me know if you want me to contribute this for Windows.

**Comment by jbensabat** [comment]
Hi
I think it makes sense to post the new and more stable way of installing mlpack on MSVC
I think it would be great if you could post to VS app.
Best
Jac


Jacob Bensabat, PH.D.
CTO
EWRE Ltd.
Tel: +972-4-8383919.
Fax: +972-4-8387621.
Mobile: +972-544-417511.

**Comment by rcurtin** [comment]
I'd like to update the VS tutorial with these notes if possible, but I'd like to get a bit more clarification before I build a patch:

> Use the Windows GUI (!) version of CMake and generate VS solution files for mlpack. Add the boost, Armadillo and MKL/OpenBLAS source code directory folders to the CMake configuration, etc. The trick with boost is that you should add the source code instead of linking to a DLL and use the preprocessor directive BOOST_ALL_NO_LIB ! In this way you can use any version of boost and you will not have problems with versioning!

@zsogitbe: Can you explain about `BOOST_ALL_NO_LIB` a bit more?  What would we need to specify to the CMake configuration to use this?  I see that the `FindBoost.cmake` script has some support for this, but I don't know exactly how you've done it.  For the other directories, I guess you are manually using the CMake GUI to set `ARMADILLO_LIBRARY`, `ARMADILLO_INCLUDE_DIR`, `BOOST_INCLUDEDIR`, `BOOST_LIBRARYDIR`, `BLAS_LIBRARY`, and `LAPACK_LIBRARY`?

Does NuGet have a package for MKL?  Or did you install that through whatever Intel-provided installer?

The template VS solution file could be useful, but I'd really prefer to stick with CMake-built configurations---otherwise we then have to maintain both a CMake configuration and a Visual Studio template. :)

**Comment by rcurtin** [comment]
I spent some time looking into this this evening.  I found that `-DBOOST_ALL_NO_LIB=1` can be helpful in some situations and I don't have a problem including that bit when on Windows, but what this variable does is tell the Boost config---at compile time, which is after configure time---that auto-linking shouldn't be done.  But the problem we had in this issue (and many others) is that we have failures at configuration time.

I definitely won't include the entire Boost sources as part of the mlpack project (and won't generally suggest that to users) because as you pointed out, this means that Boost is compiled every time a user compiles mlpack, and also this would wreak havoc on the usual Linux installation (it would be very weird for a project to not use the system Boost), as well as the license issues that come with redistributing Boost (tedious).

For directly setting the path to the Boost libraries, which variables did you use?  In my experimentation (on Linux) I found that I could "force" the Boost scripts to find a Boost version that I manually specified by setting:

 * `Boost_INCLUDE_DIR` (`PATH`)
 * `Boost_PROGRAM_OPTIONS_LIBRARY_DEBUG` (`FILEPATH`)
 * `Boost_PROGRAM_OPTIONS_LIBRARY_RELEASE` (`FILEPATH`)
 * `Boost_SERIALIZATION_LIBRARY_DEBUG` (`FILEPATH`)
 * `Boost_SERIALIZATION_LIBRARY_RELEASE` (`FILEPATH`)
 * `Boost_UNIT_TEST_FRAMEWORK_LIBRARY_DEBUG` (`FILEPATH`)
 * `Boost_UNIT_TEST_FRAMEWORK_LIBRARY_RELEASE` (`FILEPATH`)

Are these the variables that you manually configure?  If so, I can add these to the tutorial, but if not, I can either try and use what you did, or you can check and see if setting the variables I listed work.  Then I can add these to the tutorial as a "backup" in case people have problems with Boost configuration.

**Comment by zsogitbe** [comment]
I will give you here under my changes to the CMakeLists.txt on my system:

Around line 190 correction for Windows:

```
if (NOT MSVC)
     set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -O3")
     set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -std=c99 -O3")
  else()
     set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS}")
     set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -std=c99")
  endif()
```

This I have completely removed:

```
# find_package(Boost 1.49
#    COMPONENTS
#       program_options
#       unit_test_framework
#       serialization
#     REQUIRED
# )
```

Removed one line with DBOOST_TEST_DYN_LINK and added two lines:

```
# add_definitions(-DBOOST_TEST_DYN_LINK)
add_definitions(-DBOOST_ALL_NO_LIB)
add_definitions(-DBOOST_ALL_DYN_LINK)
```
I just set Boost_INCLUDE_DIR manually in the CMake GUI (it is difficult to detect that one). I do not use the other parameters at all because I do not link to those boost libraries.

**Comment by jbensabat** [comment]
Hi
If you use the GUI version of CMAKE it will find the installation of the boost binaries.
I my case I put them in the \local directory (c:\local\boost_1_68_00) and it found them
Best
Jac


Jacob Bensabat, PH.D.
CTO
EWRE Ltd.
Tel: +972-4-8383919.
Fax: +972-4-8387621.
Mobile: +972-544-417511.
