### ISSUE TITLE
Enhancement: Stop running operations with cleanup.

### ISSUE THREAD

**Issue by zsogitbe** [mlpack/mlpack#1552]
It would be very interesting to have a signal mechanism to be able to stop running operations in a clean way. For this one global thread-safe variable would be sufficient which should be checked during long processes (loops). In case the stop is signaled then the operation should stop in a clean way and clean up memory.

**Comment by zoq** [comment]
I think this could be integrated into the ``FunctionWrapper`` idea (https://github.com/mlpack/mlpack/issues/1481), that is part of the optimizer. That would cover some "long processes (loops)" but not all, I think that might be a good start. Let me know what you think.

**Comment by zsogitbe** [comment]
That solution looks a bit too complicated to me but maybe I am not yet used to the idea. Would that not slow down the code significantly by going through several levels of function wrappers? Would that not be too much work to implement?
I think that stopping long operations is a general (and important) need in several places and maybe a general/global solution would be better. The simpler the better.

**Comment by rcurtin** [comment]
> I know that you do not like inheritance and would like to solve all problems with templates but if I were you I would solve this problem with a simple inheritance in which you derive all 'long operation classes' from a 'stoppable base class'. I think that this would be the easiest to implement (less code to change in current code) and would also be the easiest to understand and use.

This is a case where inheritance would be a disaster due to the overhead of virtual function calls, since functions we are optimizing are called repeatedly.  Using the `FunctionWrapper` is the right approach here, and assuming that the functions are properly marked as `inline` (and the compiler believes inlining is the right thing to do), there is no additional overhead since all this happens at compile time.

I think the way we should approach this depends entirely on what your functionality goals are.  From what I'm piecing together I'm guessing your aim is to say something like "this neural network training is taking too long", interrupt it, and still get a recent checkpoint of the model.  The approach for that would definitely be the `FunctionWrapper` approach (think like `ModelCheckpoint` in Keras), and that could be extensible only to algorithms that use the optimization infrastructure.

If your goal is to be able to terminate any mlpack algorithm via signals and then get an intermediate result, we have a few problems that basically make this impossible: (1) many algorithms aren't iterative and so you can't terminate them while they are running and get a result; one example is a kd-tree, where it either finishes and you get a kd-tree or it doesn't finish and you get nothing.  (2) this would be a huge overhaul of the codebase to be able to handle signals from `<csignal>` or something.  We would essentially need to make an entire infrastructure to catch these, make sure loops terminate "cleanly" (still not fully sure what that always means), and then exit.  I'd really rather not go this direction, since it would be a huge testing an maintenance nightmare.  (But if all you wanted was what I described in the first paragraph, hey, ignore what I wrote here then. :))

**Comment by rcurtin** [comment]
So, I definitely agree that a `ModelCheckpoint` type functionality should be implemented.  But I'm a bit confused about the rest.  I don't know of any machine learning or linear algebra libraries that have custom handlers for signals.  It seems somewhat out of scope for mlpack.  If someone wants to write an application that uses mlpack that needs to terminate an mlpack thread or process, then they can use the existing signaling infrastructure provided by POSIX (i.e. SIGTERM, SIGKILL, etc.).  Then whatever the mlpack thread is doing will be terminated and cleaned up.

**Comment by zsogitbe** [comment]
OK, no problem, do not worry about it. I was just also thinking that most of the time there is some kind of outside cycle (between calls to e.g. an optimizer) which can be terminated. The ModelCheckpoint idea looks good and that can also be used to save the model at checkpoints if needed.

**Comment by rcurtin** [comment]
I think we can handle the bones of the `ModelCheckpoint` idea in ensmallen#49, so I'll close this in favor of discussion there. :+1:
