### ISSUE TITLE
Last step of mlpack_cf takes forever to finish

### ISSUE THREAD

**Issue by stiv-yakovenko** [mlpack/mlpack#1555]
My data file is few gb in size, 30M user-item pairs, 4M users, ~300K items, calculating each iteration takes reasonable time, few minutes:

    ~/mlpack-3.0.3/build/bin/mlpack_cf -A -t oryxlog.int.txt -o rec.txt -v -R 40 -c 200

![image](https://user-images.githubusercontent.com/4163254/48051166-f4233880-e1d6-11e8-8570-d33fcebe1f41.png)

but this last step has already been in progress for ~5hrs. It is taking just 300% of cpu (according to **top** linux command), but when calculation is in the middle, then I see 800% cpu consumption. How can I make it faster? What is it doing under the hood?

**Comment by stiv-yakovenko** [comment]
One more clarification. Once mlpack_fc wrote 'Generating node combinations for all users', there are two stages, judging from what i see as **top** command output: 100% CPU utilisation stage (shorter one) and 300% utilization stage (while at iteration stage utilisation is 800%). 

I tried to read code of mlpack_fc and even debug it, but its hard to understand from a single glance. I've seen references to Mahalanobis distance and also initialization of some huge trees. As far as I understand, to compute preferences in brute force way, you should multiply feature vector for each user to each item feature vector and find top k recommendations. But Mahalanobis somehow allows to get result faster, do I get it correctly?

**Comment by alexander-jansen** [comment]
Dear rcurtin, thank you for detailed explaination, even though I might have not understood some of the details. I've figured exact number of users and items which I have in my datafile, number which i have put in the previous messages, are too rough, actual number of items is much less, because most of items are very old and our recommender system throws away from dataset. Given these numbers, I've created very simple c++ code to emulate brute-force approach to calculation of top-20 items:

```
#include <vector>
#include <iostream>
#include <map>

using namespace std;
int main() {
	int I = 37000;
	int U = 4300000;
	int F = 40;
	int B = 200;
	vector<vector<double>> items;
	for (int i = 0; i < I; i++) {
		if (i % 10000 == 0)
			cout << i << endl;
		vector<double>fs;
		for (int f = 0; f < F; f++) {
			fs.push_back(1.*rand() / RAND_MAX);
		}
		items.push_back(fs);
	}
	for (int u = 0; u < U; u++) {
		if (u % 1000 == 0)
			cout << (100.*u/ U) << endl;
		vector<double>fs;
		for (int f = 0; f < F; f++) {
			fs.push_back(1.*rand() / RAND_MAX);
		}
		map<double, int> best;
		for (int i = 0; i < I; i++) {
			double s = 0;
			for (int f = 0; f < F; f++) {
				s += fs[f] * items[i][f];
			}
			best[s] = i; if (best.size() > B) {
				auto minKey = best.begin()->first;
				best.erase(minKey);
			}
		}

	}

	return 0;
}
```
I and its value is real number of items, U is number of users, F is number of dimensions, B is number of desired recommendations. I throw random garbage in each feature vector for each user and each item. This code completes 1% on one cpu core in 4 min on my laptop. 100% would be 400 min, but on 8core cpu it should be 50 min, which is sufficiently less then I observe with current implementation of mlpack. So may be Mahalanobis is a bit over-engineering, or may be I am missing something in my code. Or Mahalanobis can even perform better if done more efficiently.

**Comment by alexander-jansen** [comment]
I can also supply my CSV datafile of longs if you wish.

**Comment by stiv-yakovenko** [comment]
These 2 comments should go after my name, but sorry for that, let it be as is.

**Comment by rcurtin** [comment]
@stiv-yakovenko: thanks for the explanation.  In the code that you're running there, the number of items is 37k not 300k.  So I want to just double-check, is the CSV formatted such that the maximum item ID is 37000 (or close)?  If there are items for which there are no points in the training set, effectively that will just be a 0.  So if you pass in some dataset that uses items 0, 1, and 10 only... the code will still believe that items 2-9 exist, it just has no data for them.  So that could cause some significant slowdown in some cases.

I think the code you have written is missing a bit of what the CF code actually does.  Note that there is a neighborhood of users that we are using for recommendations, which means that the computation of what you've called `s` has to happen for many users.

If you'd like to provide data, I can try and run it through and do some quick profiling.  (Or, if you are willing to do it, I can help guide you, and we can get to a result faster---I am pretty busy these days so it may be a while until I can really debug in-depth.)

**Comment by stiv-yakovenko** [comment]
Dear Ryan, I know about input data requirements, all ids should go one by one, there should be no holes otherwise they will slow down the calculation. I've done preprocessing after which there is no 'unused' items. Here is a data file: https://drive.google.com/open?id=16a-U43TDUp8_U3oRG30bq08t51HhZbgd

I've seen approach with neighborhoods in Apache Mahout, neighborhoods are used to reduce calculation time there, for example we compare current user only with top N=100 users to find most similar ones. But selecting neighbourhood is a bit arbitrary, so its not clear to me how mlpack_cf does it, are there any hard-coded constants like N?

Also another question regarding algorithm mlpack_cf, if you don't mind: I've used ALS from apache spark (https://spark.apache.org/docs/2.2.0/ml-collaborative-filtering.html), in the bottom of the link you can see that there is regularization parameter setRegParam. I tried different values of this parameter on my dataset and it gives various results. Do you have similar coefficient in mlpack_cf? Is it hardcoded or you somehow manage to do without it?

**Comment by stiv-yakovenko** [comment]
And one more comment to be clear: my code is of cause incomplete, but I just wanted to show that even brute force non-optimized iteration over all items and users performs faster (~1h) then current mlpack_cf (~5hr) on large dataset. May be optimisation is redundant, or may be it can be implemented even faster then my 1h.

**Comment by rcurtin** [comment]
Hey @stiv-yakovenko, sorry for the slow response---I have been traveling and on vacation recently, and only today was I able to return to this.  I spent some time looking at your code.  From what I understand, the actual computation is this bit:

```
for (int i = 0; i < I; i++) {
			double s = 0;
			for (int f = 0; f < F; f++) {
				s += fs[f] * items[i][f];
			}
			best[s] = i; if (best.size() > B) {
				auto minKey = best.begin()->first;
				best.erase(minKey);
			}
		}
```

but actually there is a key difference between this and the CF code, and that difference is the neighborhood.  So in your code you use this loop to compute `s`:

```
			for (int f = 0; f < F; f++) {
				s += fs[f] * items[i][f];
			}
```

That only considers the current user's "vector" `fs[f]`, but the corresponding mlpack code actually considers an entire neighborhood.  That is, the computation would look more like this...

```
for (int u = 0; u < N; ++u) // By default in mlpack, N = 5
{
  for (int f = 0; f < F; f++)
  {
    // here users[][] is generated just like items[][]
    s += weights[u] * users[u][f] * items[i][f];
  }
}
```

So that would increase the complexity by at least a factor of five.  I am not sure if the speedup would be 8x with 8 cores---there might be some cache effects.

I'd like to do some profiling of this tomorrow, but I will have to run `mlpack_cf` to build and save the CF model overnight (since it takes a little while), and I'll let you know what I find.

**Comment by rcurtin** [comment]
Ah sorry I see there were also some questions I did not answer.

> But selecting neighbourhood is a bit arbitrary, so its not clear to me how mlpack_cf does it, are there any hard-coded constants like N?

This is done by a nearest neighbor search on the columns of the user matrix H.  N is not hardcoded but can be specified by the `--neighborhood` parameter.  By default it's 5, but you could make it smaller and that should speed things up a little.

> I tried different values of this parameter on my dataset and it gives various results. Do you have similar coefficient in mlpack_cf? Is it hardcoded or you somehow manage to do without it?

The NMF+ALS decomposition that mlpack implements doesn't have regularization on the W or H matrices.  However, if you use the `RegSVD` decomposition (regularized SVD), it does have a regularization parameter.  It is not exactly the same though.  Unfortunately, it appears that the regularization parameter is not accessible via either the `mlpack_cf` program or even the `CF` class in C++.  I could probably provide a patch that would allow setting the regularization parameter to regularized SVD, and then integrate it into the codebase, if you need the support.

**Comment by stiv-yakovenko** [comment]
Thank you for devoting your time. So, if I understand this correctly, this version of ALS not simply uses users' coefficients, but also finds ~5 close 'friends' to improve results somehow? It would be cool to cover this in the manual.

**Comment by rcurtin** [comment]
Yes, exactly.  It would be easy to add a note about `--neighborhood` in the documentation, so before we close this issue we can make sure that is done.

I spent a while profiling and debugging but I actually am not able to replicate the results that you mentioned when you opened the issue.  I found that, on my system, I could build the model in about 1h50m.  I saved this model with `--output_model_file`, then used it in subsequent runs.  To generate 200 recommendations (`-c 200`) for only 5 users (I used `-q users-5.csv` where `users-5.csv` just had numbers 0 through 4 on each line), the program took 220 seconds.  Of that 220 seconds, the vast majority (219 seconds) was spent building the tree for nearest neighbor search.

I then tried with 10k users, which took roughly 15 seconds after building the tree for nearest neighbor search to generate the recommendations.  With 100k users, it took 148s, and with all 2.3M users in the dataset, it took roughly 2100s to generate the recommendations.  Overall the run with `-A` to generate all recommendations took 57 minutes.

I tried also with regular BLAS and LAPACK instead of OpenBLAS and the slowdown was a factor of about 4 (which seems reasonable since BLAS and LAPACK are singlethreaded).  But this doesn't really seem to reproduce the significant slowdowns that you were experiencing.  I'm now running the entire command all at once to see if all runs in about 3 hours like I expect.

Can you tell me a little more about your setup?  i.e. machine specs, OS, Armadillo version, mlpack version, BLAS/LAPACK version?

**Comment by stiv-yakovenko** [comment]
```
[ec2-user@htm-psycho-401 ~]$ lscpu
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                8
On-line CPU(s) list:   0-7
Thread(s) per core:    1
Core(s) per socket:    4
Socket(s):             2
NUMA node(s):          1
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 23
Model name:            Intel(R) Xeon(R) CPU           E5450  @ 3.00GHz
Stepping:              10
CPU MHz:               3000.088
BogoMIPS:              6000.17
Virtualization:        VT-x
L1d cache:             32K
L1i cache:             32K
L2 cache:              6144K
NUMA node0 CPU(s):     0-7
Flags:                 fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx lm constant_tsc arch_perfmon pebs bts rep_good nopl aperfmperf eagerfpu pni dtes64 monitor ds_cpl vmx est tm2 ssse3 cx16 xtpr pdcm dca sse4_1 xsave lahf_lm tpr_shadow vnmi flexpriority dtherm
```

```
[ec2-user@htm-psycho-401 ~]$ cat /proc/cpuinfo
processor       : 0
vendor_id       : GenuineIntel
cpu family      : 6
model           : 23
model name      : Intel(R) Xeon(R) CPU           E5450  @ 3.00GHz
stepping        : 10
microcode       : 0xa0b
cpu MHz         : 3000.088
cache size      : 6144 KB
physical id     : 0
siblings        : 4
core id         : 0
cpu cores       : 4
apicid          : 0
initial apicid  : 0
fpu             : yes
fpu_exception   : yes
cpuid level     : 13
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx lm constant_tsc arch_perfmon pebs bts rep_good nopl aperfmperf eagerfpu pni dtes64 monitor ds_cpl vmx est tm2 ssse3 cx16 xtpr pdcm dca sse4_1 xsave lahf_lm tpr_shadow vnmi flexpriority dtherm
bogomips        : 6000.17
clflush size    : 64
cache_alignment : 64
address sizes   : 38 bits physical, 48 bits virtual
power management:

processor       : 1
vendor_id       : GenuineIntel
cpu family      : 6
model           : 23
model name      : Intel(R) Xeon(R) CPU           E5450  @ 3.00GHz
stepping        : 10
microcode       : 0xa0b
cpu MHz         : 3000.088
cache size      : 6144 KB
physical id     : 1
siblings        : 4
core id         : 0
cpu cores       : 4
apicid          : 4
initial apicid  : 4
fpu             : yes
fpu_exception   : yes
cpuid level     : 13
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx lm constant_tsc arch_perfmon pebs bts rep_good nopl aperfmperf eagerfpu pni dtes64 monitor ds_cpl vmx est tm2 ssse3 cx16 xtpr pdcm dca sse4_1 xsave lahf_lm tpr_shadow vnmi flexpriority dtherm
bogomips        : 6000.01
clflush size    : 64
cache_alignment : 64
address sizes   : 38 bits physical, 48 bits virtual
power management:

processor       : 2
vendor_id       : GenuineIntel
cpu family      : 6
model           : 23
model name      : Intel(R) Xeon(R) CPU           E5450  @ 3.00GHz
stepping        : 10
microcode       : 0xa0b
cpu MHz         : 3000.088
cache size      : 6144 KB
physical id     : 0
siblings        : 4
core id         : 1
cpu cores       : 4
apicid          : 1
initial apicid  : 1
fpu             : yes
fpu_exception   : yes
cpuid level     : 13
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx lm constant_tsc arch_perfmon pebs bts rep_good nopl aperfmperf eagerfpu pni dtes64 monitor ds_cpl vmx est tm2 ssse3 cx16 xtpr pdcm dca sse4_1 xsave lahf_lm tpr_shadow vnmi flexpriority dtherm
bogomips        : 6000.17
clflush size    : 64
cache_alignment : 64
address sizes   : 38 bits physical, 48 bits virtual
power management:

processor       : 3
vendor_id       : GenuineIntel
cpu family      : 6
model           : 23
model name      : Intel(R) Xeon(R) CPU           E5450  @ 3.00GHz
stepping        : 10
microcode       : 0xa0b
cpu MHz         : 3000.088
cache size      : 6144 KB
physical id     : 1
siblings        : 4
core id         : 1
cpu cores       : 4
apicid          : 5
initial apicid  : 5
fpu             : yes
fpu_exception   : yes
cpuid level     : 13
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx lm constant_tsc arch_perfmon pebs bts rep_good nopl aperfmperf eagerfpu pni dtes64 monitor ds_cpl vmx est tm2 ssse3 cx16 xtpr pdcm dca sse4_1 xsave lahf_lm tpr_shadow vnmi flexpriority dtherm
bogomips        : 6000.01
clflush size    : 64
cache_alignment : 64
address sizes   : 38 bits physical, 48 bits virtual
power management:

processor       : 4
vendor_id       : GenuineIntel
cpu family      : 6
model           : 23
model name      : Intel(R) Xeon(R) CPU           E5450  @ 3.00GHz
stepping        : 10
microcode       : 0xa0b
cpu MHz         : 3000.088
cache size      : 6144 KB
physical id     : 0
siblings        : 4
core id         : 2
cpu cores       : 4
apicid          : 2
initial apicid  : 2
fpu             : yes
fpu_exception   : yes
cpuid level     : 13
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx lm constant_tsc arch_perfmon pebs bts rep_good nopl aperfmperf eagerfpu pni dtes64 monitor ds_cpl vmx est tm2 ssse3 cx16 xtpr pdcm dca sse4_1 xsave lahf_lm tpr_shadow vnmi flexpriority dtherm
bogomips        : 6000.17
clflush size    : 64
cache_alignment : 64
address sizes   : 38 bits physical, 48 bits virtual
power management:

processor       : 5
vendor_id       : GenuineIntel
cpu family      : 6
model           : 23
model name      : Intel(R) Xeon(R) CPU           E5450  @ 3.00GHz
stepping        : 10
microcode       : 0xa0b
cpu MHz         : 3000.088
cache size      : 6144 KB
physical id     : 1
siblings        : 4
core id         : 2
cpu cores       : 4
apicid          : 6
initial apicid  : 6
fpu             : yes
fpu_exception   : yes
cpuid level     : 13
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx lm constant_tsc arch_perfmon pebs bts rep_good nopl aperfmperf eagerfpu pni dtes64 monitor ds_cpl vmx est tm2 ssse3 cx16 xtpr pdcm dca sse4_1 xsave lahf_lm tpr_shadow vnmi flexpriority dtherm
bogomips        : 6000.01
clflush size    : 64
cache_alignment : 64
address sizes   : 38 bits physical, 48 bits virtual
power management:

processor       : 6
vendor_id       : GenuineIntel
cpu family      : 6
model           : 23
model name      : Intel(R) Xeon(R) CPU           E5450  @ 3.00GHz
stepping        : 10
microcode       : 0xa0b
cpu MHz         : 3000.088
cache size      : 6144 KB
physical id     : 0
siblings        : 4
core id         : 3
cpu cores       : 4
apicid          : 3
initial apicid  : 3
fpu             : yes
fpu_exception   : yes
cpuid level     : 13
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx lm constant_tsc arch_perfmon pebs bts rep_good nopl aperfmperf eagerfpu pni dtes64 monitor ds_cpl vmx est tm2 ssse3 cx16 xtpr pdcm dca sse4_1 xsave lahf_lm tpr_shadow vnmi flexpriority dtherm
bogomips        : 6000.17
clflush size    : 64
cache_alignment : 64
address sizes   : 38 bits physical, 48 bits virtual
power management:

processor       : 7
vendor_id       : GenuineIntel
cpu family      : 6
model           : 23
model name      : Intel(R) Xeon(R) CPU           E5450  @ 3.00GHz
stepping        : 10
microcode       : 0xa0b
cpu MHz         : 3000.088
cache size      : 6144 KB
physical id     : 1
siblings        : 4
core id         : 3
cpu cores       : 4
apicid          : 7
initial apicid  : 7
fpu             : yes
fpu_exception   : yes
cpuid level     : 13
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx lm constant_tsc arch_perfmon pebs bts rep_good nopl aperfmperf eagerfpu pni dtes64 monitor ds_cpl vmx est tm2 ssse3 cx16 xtpr pdcm dca sse4_1 xsave lahf_lm tpr_shadow vnmi flexpriority dtherm
bogomips        : 6000.01
clflush size    : 64
cache_alignment : 64
address sizes   : 38 bits physical, 48 bits virtual
power management:
```

```
[ec2-user@htm-psycho-401 ~]$ cat /proc/meminfo
MemTotal:       32779320 kB
MemFree:        15221256 kB
MemAvailable:   28484388 kB
Buffers:          487448 kB
Cached:         12035504 kB
SwapCached:         1272 kB
Active:         11324964 kB
Inactive:        4590840 kB
Active(anon):    3401964 kB
Inactive(anon):   214380 kB
Active(file):    7923000 kB
Inactive(file):  4376460 kB
Unevictable:           0 kB
Mlocked:               0 kB
SwapTotal:       8191996 kB
SwapFree:        8161532 kB
Dirty:                88 kB
Writeback:             0 kB
AnonPages:       3391972 kB
Mapped:            96504 kB
Shmem:            223492 kB
Slab:            1397232 kB
SReclaimable:    1365352 kB
SUnreclaim:        31880 kB
KernelStack:        3408 kB
PageTables:        12492 kB
NFS_Unstable:          0 kB
Bounce:                0 kB
WritebackTmp:          0 kB
CommitLimit:    24581656 kB
Committed_AS:    4032296 kB
VmallocTotal:   34359738367 kB
VmallocUsed:       75608 kB
VmallocChunk:   34359658492 kB
HardwareCorrupted:     0 kB
AnonHugePages:   2033664 kB
CmaTotal:              0 kB
CmaFree:               0 kB
HugePages_Total:       0
HugePages_Free:        0
HugePages_Rsvd:        0
HugePages_Surp:        0
Hugepagesize:       2048 kB
DirectMap4k:      107188 kB
DirectMap2M:    33445888 kB
```

```
[ec2-user@htm-psycho-401 ~]$ mlpack-3.0.3/build/bin/mlpack_cf --version
Collaborative Filtering: part of mlpack 3.0.3.
```

```
[ec2-user@htm-psycho-401 build]$ yum info armadillo
Loaded plugins: fastestmirror
Repodata is over 2 weeks old. Install yum-cron? Or run: yum makecache fast
Determining fastest mirrors
 * base: mirror.reconn.ru
 * epel: mirror.infonline.de
 * extras: mirror.reconn.ru
 * updates: mirror.reconn.ru
epel                                                                                                                   12746/12746
zabbix                                                                                                                     129/129
Installed Packages
Name        : armadillo
Arch        : x86_64
Version     : 8.300.0
Release     : 1.el7
Size        : 58 k
Repo        : installed
From repo   : epel
Summary     : Fast C++ matrix library with syntax similar to MATLAB and Octave
URL         : http://arma.sourceforge.net/
License     : ASL 2.0
```

```
[ec2-user@htm-psycho-401 build]$ yum info blas
Loaded plugins: fastestmirror
Repodata is over 2 weeks old. Install yum-cron? Or run: yum makecache fast
Loading mirror speeds from cached hostfile
 * base: mirror.reconn.ru
 * epel: mirror.infonline.de
 * extras: mirror.reconn.ru
 * updates: mirror.reconn.ru
Installed Packages
Name        : blas
Arch        : x86_64
Version     : 3.4.2
Release     : 8.el7
Size        : 771 k
Repo        : installed
From repo   : base
Summary     : The Basic Linear Algebra Subprograms library
URL         : http://www.netlib.org/lapack/
License     : BSD
Description : BLAS (Basic Linear Algebra Subprograms) is a standard library which
            : provides a number of basic algorithms for numerical algebra.
```

```
[ec2-user@htm-psycho-401 build]$ yum info lapack
Loaded plugins: fastestmirror
Repodata is over 2 weeks old. Install yum-cron? Or run: yum makecache fast
Loading mirror speeds from cached hostfile
 * base: mirror.reconn.ru
 * epel: mirror.infonline.de
 * extras: mirror.reconn.ru
 * updates: mirror.reconn.ru
Installed Packages
Name        : lapack
Arch        : x86_64
Version     : 3.4.2
Release     : 8.el7
Size        : 10 M
Repo        : installed
From repo   : base
Summary     : Numerical linear algebra package libraries
URL         : http://www.netlib.org/lapack/
License     : BSD
```

As far as I understand you build tree to find faster items' vectors with largest scalar product for each user. Can you give a reference what algorithm do you use for it?

**Comment by stiv-yakovenko** [comment]
One more question regarding math of this calculation, sorry if its a bit offtopic, but also related to perfomance. Is it possible to speedup convergence of these iterations with linear pruning? For example you have vectors from previous and current iterations of the process *v_k* and *v_{k-1}*. Then you can build linear approximation between these two points (these highly multidimensional points include all users and features):

v = v_k + t (v_{k-1} - v_k)

Now if you plug this into optimized expression

(Aij - Uik*Hjk)^2 -> min

then since user vector U and item vector H depend linearly on t, then you'll get 4rth order polynomial as result:

c0 +c1 t+ c2 t*t + c3 *t^3 + c4t^4 -> min

This problem can be solved analytically by finding roots of cubic equation. Can this help to improve iterations? I used this kind of pruning for solving huge (1M variables) systems of nonlinear equations and it improves perfomance by orders of magnitude. Am I missing something here?

**Comment by stiv-yakovenko** [comment]
One more important note: I've also built mlpack on Windows (https://github.com/stiv-yakovenko/mlpack-windows-build contains binaries for it) and I have observed same perfomance problem during last step. If you wish I can measure time for windows build also.

**Comment by rcurtin** [comment]
Your hardware is better than mine I think, thanks for all the details. :)  But I see you are using the reference BLAS and LAPACK implementation.  Try installing OpenBLAS, I think it will give good speedup:

```
# yum install openblas
```
(I think that is the right package name...)

Then you will have to rebuild mlpack, I think.  Unless RHEL7 drops openblas into the exact same place with the same .so names as the other BLAS and LAPACK.  (Debian uses `update-alternatives` for this, which is pretty nice and lets me easily switch back and forth, since `liblapack.so.3` is just a symlink controlled by `update-alternatives`, for instance.  I would think that RHEL has similar support but I am not familiar with the details.  In any case, you could `make clean` and `make -j8 mlpack_cf` just to be sure...)

> As far as I understand you build tree to find faster items' vectors with largest scalar product for each user. Can you give a reference what algorithm do you use for it?

So what we are doing is using kd-trees for nearest neighbor search.  The actual algorithm we use here is a dual-tree algorithm, but if you are not familiar with kd-trees it might first be useful to read about how a kd-tree is used to find nearest neighbors:

https://en.wikipedia.org/wiki/K-d_tree#Nearest_neighbour_search

That's called 'single-tree search'; in dual-tree search it is a little bit more complicated.  The details of dual-tree nearest neighbor search can be found in this paper:

http://ratml.org/pub/pdf/2013tree.pdf

My thesis is way longer but it may also have more details if you are interested:

http://ratml.org/pub/pdf/2015improving.pdf

Sections 3.3--3.6 describe trees, then Section 7.1 describes how nearest neighbor search is done.  Not sure if you wanted that level of detail though. :)

> One more question regarding math of this calculation, sorry if its a bit offtopic, but also related to perfomance. Is it possible to speedup convergence of these iterations with linear pruning?

Do you mean the convergence of the matrix factorization?  If you use `-a NMF` (the default), it's just using the ALS update rules from https://onlinelibrary.wiley.com/doi/abs/10.1002/env.3170050203 .

I guess it is possible to speed up convergence here, and the idea you suggested reminds me a bit of optimizers with momentum.  Basically the idea would be to use the gradients from previous iterations as well as from this iteration to choose the step.  There are definitely some momentum-based techniques for CF, but I don't think any are implemented in mlpack.  And what you are suggesting sounds slightly different.  It could work though, I suppose.

> One more important note: I've also built mlpack on Windows (https://github.com/stiv-yakovenko/mlpack-windows-build contains binaries for it) and I have observed same perfomance problem during last step. If you wish I can measure time for windows build also.

Maybe the same here, if you can use OpenBLAS it could give speedup.  But if you want to try it and time how long it takes, it could be interesting to see the result.  Perhaps there are some compiler optimizations we should enable in Visual Studio?  If you see any that are not enabled that should be, I can look into changing the CMake configuration accordingly.

> Uh, and one more thing: you have this extra loop over N=5 elements in your fix for my code. But you can push this multiplication inside second loop (i.e. reorder loops) and have something like this

You're right, that is a nice trick.  I think that the actual CF code does not make that optimization quite that easy, but I will try to write the code for that tomorrow and see how much speedup it gives.

The run I kicked off earlier is still going; the NMF run has not converged yet, so I don't have results for that.  I'll probably have them tomorrow morning. :)

**Comment by rcurtin** [comment]
I ran the entire run with both OpenBLAS and then with stock LAPACK/BLAS (like you are using):

```
bin/mlpack_cf -t oryxlog.int.txt -v -c 200 -R 40 -A -o recs.csv
```

With OpenBLAS, the factorization took 1h50m over 56 iterations and then the computation of recommendations took roughly 55m.

With stock LAPACK/BLAS, the factorization took 9h25m over 29 iterations (note that the starting point is random, so each run may take a different number of iterations) and then the computation of recommendations took roughly 2h10m.

So using OpenBLAS can definitely give a big speedup.

**Comment by stiv-yakovenko** [comment]
Thank you, will try to migrate to openblas.
