### ISSUE TITLE
Choco installer for Windows?

### ISSUE THREAD

**Issue by buddha314** [mlpack/mlpack#1589]
I would like to use MLPack in an application that requires Windows to run.  The current setup is a bit daunting.  Would it be possible to create a [choco](https://chocolatey.org/) installer?

**Comment by rcurtin** [comment]
@buddha314: I agree, it would be really great to do that!  But I am not familiar with Chocolatey (and also don't use Windows).  If anyone out there is able to contribute something, I think we should definitely merge it.

I'll mark this as a good task for someone new to the library. :+1:

**Comment by buddha314** [comment]
These instructions are pretty intimidating: https://github.com/mlpack/mlpack/wiki/WindowsBuild for a guy like me who really just does math.

**Comment by zoq** [comment]
I think the tutorial here is quite good: https://www.mlpack.org/docs/mlpack-git/doxygen/build_windows.html but I agree there is definitely an advantage to install mlpack on windows with a single command.

**Comment by leonplust** [comment]
Anyone is working on this?

**Comment by zoq** [comment]
No, please feel free to take a closer look into the issue.

**Comment by leonplust** [comment]
I had pushed both mlpack and armadillo to the choco community repository. Except for armadillo, both boost and cmake are on the choco community repository already. So I created a package for armadillo as well. Since @rcurtin you are one of the authors of armadillo, I assume I can create a package for armadillo. I put all of the authors' names that I can find from the armadillo website for the package already. It will take some time for choco to review my packages until they go online since this is the first time I upload the package. Also, if anyone is using windows would like to try the installation of the package or more testing I would like to provide the instruction and package.

**Comment by rcurtin** [comment]
@leonplust thanks so much for doing the packaging!  I'm not the only author of Armadillo though, the primary maintainer is @conradsnicta---I assume it's not an issue to package Armadillo in Chocolatey.

I don't see mlpack in the list of packages at https://chocolatey.org/search?q=mlpack... i guess it will still be some time until it is in the main list of packages?  When it is, I think we can close this issue. :+1:
