### ISSUE TITLE
mlpack running at the same speed with nvblas

### ISSUE THREAD

**Issue by NacOJerk** [mlpack/mlpack#1677]
So I was finally able to run mlpack using nvblas , now when I run the code it seems to still be at the same speed (I am using the following code https://github.com/mlpack/models/blob/master/vae/vae_cnn_mnist/src/vae_cnn.cpp)
Now, I do see that the program is using a bit of the GPU but barely any.

I was wondering if anyone ever experienced it and has a solution (I am saying solution because the code should run faster so I assume there is something wrong).
In the linking of the program I am still linking openblas (nvblas is missing a few blas functions for some reason)

**Comment by zoq** [comment]
Do you mind to test the code from the stackoverflow question (https://stackoverflow.com/questions/51526442/dgemm-nvblas-gpu-offload)? That might give us some more insights.

**Comment by rcurtin** [comment]
Also, for what it's worth, I think the batch size will make a difference here.  NVBLAS is good when large matrices are being multiplied, so that it is worthwhile to move the matrix to the GPU for each computation, but it won't be very helpful for lots of small operations.  A larger batch size means a larger matrix computation at each level of the network, and so this should give better GPU usage and perhaps better speedup.

**Comment by NacOJerk** [comment]
well I gave the code @zoq gave and even though now I see clear GPU usage (100%) it is still slower. I even tried it with huge matrices ([10000, 20000] * [20000, 30000]) and the CPU is somehow still faster

**Comment by NacOJerk** [comment]
I found out that when ever you treat all the matrices as doubles only then will the nvblas functions be used.

Is there a way to make mlpack to only use double matrices ?

**Comment by rcurtin** [comment]
mlpack already uses double-valued matrices (i.e. `arma::mat`), so that shouldn't be an issue.  Depending on the GPU that you have and the computations involved, nvblas may or may not give speedup.  There's a lot involved, so it's hard to say exactly what's going on here.  You could try some different mlpack methods (maybe PCA?) that may have more "typical" linear algebra workloads, and maybe you might see some different behavior there.

**Comment by NacOJerk** [comment]
After deciding to check out the actual specs of the graphics card I found out the the boost is actually at floats and not doubles (it is around 6 times faster than the CPU when using floats)
