### ISSUE TITLE
Update mlpack3 consistently on PyPI

### ISSUE THREAD

**Issue by impredicative** [mlpack/mlpack#1697]
Is there any reason why [mlpack3](https://pypi.org/project/mlpack3/#history) hasn't been updated on PyPI in a while? Please try and update it whenever you've a new release. I see the current mlpack version, for example, is 3.0.4, but the one on PyPI is 3.0.2.

Also, will mlpack3 3.0.4 then work with the current version of Python, i.e. 3.7?

**Comment by rcurtin** [comment]
Hey there @impredicative, thanks for reporting this.  You are indeed right that it hasn't been updated in a while, and the reason for this is that I don't have a good release process that automatically does this.  I'm working on that.  To make things worse, I realize that I no longer have access to the system that my manylinux build scripts were on!  So I will need to rebuild them.  I hope to be able to handle this soon (next few days), but it may take longer for me to find the time (next few weeks).

In the longer term, I hope to be able to automatically update the package on PyPI when I release a new version.  But like I said, we are a bit far away from that today. :)

**Comment by impredicative** [comment]
OK

**Comment by rcurtin** [comment]
Hey @impredicative, I'm really sorry!  I forgot to respond to this one, instead responding to the related #1795.

I spent quite a while a few months back setting up the mlpack/mlpack-wheels repository in order to automatically build for PyPI each time we release.  So, as of about three weeks ago, 3.1.1 packages are now available on PyPI for Linux and OS X, and when we make future releases, this will be a part of the release pipeline.

I am still working on Windows versions for PyPI, but the discussion for that is in #1872.

Thanks again for waiting so patiently, and sorry it took so long. :+1: I'll go ahead and close this now, but please let me know if I missed something.

**Comment by rcurtin** [comment]
mlpack-bot to the rescue, by the way... I'd have completely forgotten about this for who knows how many more months unless it had been marked stale. :)
