### ISSUE TITLE
Design parallelization framework

### ISSUE THREAD

**Issue by rcurtin** [mlpack/mlpack#173]
**Reported by rcurtin on 3 Jun 41971839 12:40 UTC**
This is a master ticket designed to encompass the big 2.0 feature: parallelization.  Before this ticket is done:
- A framework for parallelization must be found
- This framework must be applied to each method

The framework we use should, ideally, make parallelization of the algorithm easy and fairly transparent to the developer.  They should not have to write workers, threads, callbacks, so on and so forth; they should be able to simply specify somehow that some particular loop could be parallelized... or something.

I seem to understand OpenMP is a decent framework for something like this, but I know so little about parallelization that I am not certain if what we are looking for is really possible at the moment.

Migrated-From: http://trac.research.cc.gatech.edu/fastlab/ticket/179

**Comment by thejonan** [comment]
Is this possible as a general task at all?

**Comment by rcurtin** [comment]
I think that OpenMP is really the best way to go here, so one way to do this is just "pick a method and OpenMP-ize it".  If you're interested in finding other parallelism solutions, you can explore libraries and propose solutions, but one of the biggest keys is that the code remains easy to maintain and easy to understand.  i.e., MPI code can be really ugly so we should really try to avoid that since it would make the algorithms very hard to read, for instance.  (The same is true of stuff like OpenCL and CUDA unfortunately.)

**Comment by thejonan** [comment]
I completely agree, that OpenMP is the best way, (although Apple a reluctant to support it in their standard `clang` compiler). I've misunderstood the issue thinking it is either about bringing some other (new) framework, rather than OpenMP; or aiming at providing a universal way of parallelizing the algorithms themselves, which not really possible, being pretty method/algorithm specific process.

This misunderstanding is probably because due to the span of the time (≈2 years), since now I can see that `openmp` is utilized in the `master` branch of MLPack. Probably you can rename the issue, or bring up another one, or nothing. In any case - you can ignore my comment :-)

**Comment by codedeamon** [comment]
hi, I would like to ask if you would be interested in an implementation in CUDA.

**Comment by rcurtin** [comment]
Hi there, it would be best to stick with OpenMP to avoid making the code too hard to understand.  If a user wants GPU support they can always use Armadillo with NVBLAS and this will give good speedup.

**Comment by codedeamon** [comment]
Hi, can I take this task through Google Summer of Code?

**Comment by rcurtin** [comment]
You are welcome to submit an application.

**Comment by rcurtin** [comment]
I think this issue is no longer really relevant.  We've kind of settled on using OpenMP where possible, and in many places a lower-level implementation is parallel on its own (like OpenBLAS for instance).  So it would always be nice to parallelize things that aren't already parallel, but the issue here---which was to figure out what parallelism framework to use---is now finished, in my opinion.
