### ISSUE TITLE
reinforcement learning actions question

### ISSUE THREAD

**Issue by kyleeng1** [mlpack/mlpack#1737]
Hi,

I'm working on a small example project, where I make an "environment" that has four degrees of freedom in the action space, so that I can change four properties in State . I'm working in Visual Studio on Windows 10.
I'm testing environments using the program given here:
https://rohanrajblogs.blogspot.com/2018/02/q-learning-using-mlpack.html
I based my work on both cart pole and pendulum.

I have my Action like this:

```
struct Action
{
	double action[4];

	const int size = 4;
};
```

I however ran into the error "C2440	'=': cannot convert from 'ai_sample::DqnSample::Action' to 'eT' sample_dqn_test_env	c:\projects\mlpack-3.0.4\build\include\mlpack\methods\reinforcement_learning\replay\random_replay.hpp	89"

And that points to this:
```
void Store(const StateType& state,
             ActionType action,
             double reward,
             const StateType& nextState,
             bool isEnd)
  {
    states.col(position) = state.Encode();
    actions(position) = action;
    rewards(position) = reward;
    nextStates.col(position) = nextState.Encode();
    isTerminal(position) = isEnd;
    position++;
    if (position == capacity)
    {
      full = true;
      position = 0;
    }
  }
```

I'm thinking the error has to do with how "actions" in the random_replay.hpp file is an arma::icolvec,
and the action I have is in the form of a double array.

I wasn't sure why Pendulum works even though it has a double array for action.
Could someone advise me as to how I can fix my current issue?
Thank you.
I'm quite new to reinforcement learning, so I may have missed some things.

**Comment by MuLx10** [comment]
@kyleeng1 Can you share your full code?

**Comment by kyleeng1** [comment]
I'm not able to share the full code, but the general idea is that I want to maximize some reward function that takes multiple real-numbered inputs, and this function outputs a real-numbered output (which I believe IsTerminal() achieves).

So I'm trying to use 4 degrees of freedom in the action, so that each property of state can change by different values.
Looking at Pendulum, I saw:
`double torque = std::min(
        std::max(action.action[0], -maxTorque), maxTorque);`

I want to do this for each of the 4 action array values like for example:

`double torque1 = std::min(
        std::max(action.action[1], -maxTorque), maxTorque);`

As I mentioned before, I'm not sure if I got the issue I have because I'm not casting the double array into ints instead (seeing as how actions in random_replay.hpp is an icolvec).

**Comment by mirraaj** [comment]
Hello @kyleeng1. By your previous statement, it seems that you have targeted using Q learning for a continuous action space environment by using ```4 degrees of freedom```. This becomes difficult because Q learning has been defined for discrete action space. Coming back to your question, DQN isn't compatible with Continous Mountain Car and Pendulum environment. 

From technicality point of view, you have recognized that the data type for Action in random replay is arma::icolvec. Since we need discreet action for this implementation, we went ahead with an ```enum``` for discrete action space game implementation. If your environment has the property of discrete action space, please define your environment properly and you will find the DQN code to be working.

For continuous action space games, there is an open PR #1328 by me. I hope to get this merged by the end of the second week of March. I believe that MLPACK do not support any continuous action space RL environment as of now.

Thank you for citing my blog and code. Please let me know if you need any more details.

**Comment by kyleeng1** [comment]
Hello Mehul, Rohan,

Thank you both very much for taking a look at my issue. Thank you Rohan for the information and guidance. As of now, I do not have further questions. I appreciate your advice and will be on the lookout for the PR merge you mentioned.

**Comment by mirraaj** [comment]
@kyleeng1 I hope you find my work useful. Thanks,
