### ISSUE TITLE
Can't import any mlpack-module in python

### ISSUE THREAD

**Issue by kumargopal** [mlpack/mlpack#1760]
I built mlpack from source as documented. In python 'import mlpack' doesn't show any error but I can't import any of the modules. Here is the full error:-

Python 3.6.8 |Anaconda, Inc.| (default, Dec 30 2018, 01:22:34) 
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from mlpack import knn
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'knn'
>>> import mlpack
>>>

**Comment by rcurtin** [comment]
How did you install mlpack?  Is it installed to somewhere that is available in PYTHONPATH?

You can run another test from your build directory to ensure they are working; start Python like this then try to import mlpack (substitute the right paths in place):

```
$ export LD_LIBRARY_PATH=/path/to/build/lib/
$ export PYTHONPATH=/path/to/build/src/mlpack/bindings/python/
$ python
```

then `import mlpack` should work.  If that does work, this is an installation issue, and for whatever reason Python is not seeing the installed mlpack libraries, so that would be a starting point for debugging.  Take a look at the install log to see where mlpack installed the Python bindings, and go from there. :+1:

**Comment by kumargopal** [comment]
Thanks!
I'm using Ubuntu 18.10 and installed mpack as documented here : http://www.mlpack.org/docs/mlpack-git/doxygen/build.html
by using the commands
`$ wget http://www.mlpack.org/files/mlpack-3.0.4.tar.gz
$ tar -xvzpf mlpack-3.0.4.tar.gz
$ mkdir mlpack-3.0.4/build && cd mlpack-3.0.4/build
$ cmake ../
$ make -j4  # The -j is the number of cores you want to use for a build.
$ sudo make install`
I tried by adding the path into bashrc file, that din't work for me.
`export PYTHONPATH="$PYTHONPATH:/usr/local/include:/home/gopal/mlpack-master/src/mlpack/bindings"
export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:/usr/local/bin:/home/gopal/mlpack-master/build/lib/"`

At First, I had built mlpack-3.0.4.tar.gz but as it din't work then I downloaded the source code from github (mlpack-master) and built it. Can this re-installation cause any error?

**Comment by yashodeepm** [comment]
I was facing the same issue. Try this:
`export PYTHONPATH='/usr/local/lib/python3.7/site-packages/:$PYTHONPATH'`
if you are using mlpack for python 3.

**Comment by karlzhang-hhg** [comment]
After a long way of hacking, I can import mlpack now. But I cannot use it. I try @yashodeepm 's suggestion, but it doesn't work. When I tried to make the example in https://www.mlpack.org/doc/mlpack-3.0.4/doxygen/python_quickstart.html work, it just said:
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-2-fdfa4c0d9acf> in <module>
      9 # Split the dataset using mlpack.  The output comes back as a dictionary,
     10 # which we'll unpack for clarity of code.
---> 11 output = mlpack.preprocess_split(input=dataset,
     12                                  input_labels=labels,
     13                                  test_ratio=0.3)

AttributeError: module 'mlpack' has no attribute 'preprocess_split'

I built mlpack-3.0.4 from source. I managed to work until using the command `sudo make install`. This command all works fine, but there is a Test fail.

-- Installing: /usr/local/include/mlpack/bindings/cli/map_parameter_name.hpp
-- Installing: /usr/local/include/mlpack/bindings/cli/get_allocated_memory.hpp
-- Installing: /usr/local/include/mlpack/mlpack_export.hpp
-- Installing: /usr/local/include/mlpack/core.hpp
-- Installing: /usr/local/lib/libmlpack.3.0.dylib
-- Installing: /usr/local/lib/libmlpack.3.dylib
-- Installing: /usr/local/lib/libmlpack.dylib
running install
Checking .pth file support in usr/local/lib/python3.6/site-packages/
/anaconda3/bin/python -E -c pass
/anaconda3/lib/python3.6/distutils/dist.py:261: UserWarning: Unknown distribution option: 'long_description_content_type'
  warnings.warn(msg)
TEST FAILED: usr/local/lib/python3.6/site-packages/ does NOT support .pth files
error: bad install directory or PYTHONPATH

You are attempting to install a package to a directory that is not
on PYTHONPATH and which Python does not read ".pth" files from.  The
installation directory you specified (via --install-dir, --prefix, or
the distutils default setting) was:

    usr/local/lib/python3.6/site-packages/

and your PYTHONPATH environment variable currently contains:

    '/usr/local/lib/python3.6/site-packages/'

Here are some of your options for correcting the problem:

* You can choose a different installation directory, i.e., one that is
  on PYTHONPATH or supports .pth files

* You can add the installation directory to the PYTHONPATH environment
  variable.  (It must then also be on PYTHONPATH whenever you run
  Python and want to use the package(s) you are installing.)

* You can set up the installation directory to support ".pth" files by
  using one of the approaches described here:

  https://setuptools.readthedocs.io/en/latest/easy_install.html#custom-installation-locations


Please make the appropriate changes for your system and try again.
-- Installing: /usr/local/bin/mlpack_adaboost
-- Installing: /usr/local/bin/mlpack_approx_kfn
-- Installing: /usr/local/bin/mlpack_cf
-- Installing: /usr/local/bin/mlpack_dbscan
-- Installing: /usr/local/bin/mlpack_decision_stump
-- Installing: /usr/local/bin/mlpack_decision_tree
-- Installing: /usr/local/bin/mlpack_det
-- Installing: /usr/local/bin/mlpack_emst
-- Installing: /usr/local/bin/mlpack_fastmks
-- Installing: /usr/local/bin/mlpack_gmm_train
-- Installing: /usr/local/bin/mlpack_gmm_generate
-- Installing: /usr/local/bin/mlpack_gmm_probability
-- Installing: /usr/local/bin/mlpack_hmm_train
-- Installing: /usr/local/bin/mlpack_hmm_loglik
-- Installing: /usr/local/bin/mlpack_hmm_viterbi
-- Installing: /usr/local/bin/mlpack_hmm_generate
-- Installing: /usr/local/bin/mlpack_hoeffding_tree
-- Installing: /usr/local/bin/mlpack_kernel_pca
-- Installing: /usr/local/bin/mlpack_kmeans
-- Installing: /usr/local/bin/mlpack_lars
-- Installing: /usr/local/bin/mlpack_linear_regression
-- Installing: /usr/local/bin/mlpack_local_coordinate_coding
-- Installing: /usr/local/bin/mlpack_logistic_regression
-- Installing: /usr/local/bin/mlpack_lsh
-- Installing: /usr/local/bin/mlpack_mean_shift
-- Installing: /usr/local/bin/mlpack_nbc
-- Installing: /usr/local/bin/mlpack_nca
-- Installing: /usr/local/bin/mlpack_knn
-- Installing: /usr/local/bin/mlpack_kfn
-- Installing: /usr/local/bin/mlpack_nmf
-- Installing: /usr/local/bin/mlpack_pca
-- Installing: /usr/local/bin/mlpack_perceptron
-- Installing: /usr/local/bin/mlpack_preprocess_split
-- Installing: /usr/local/bin/mlpack_preprocess_binarize
-- Installing: /usr/local/bin/mlpack_preprocess_describe
-- Installing: /usr/local/bin/mlpack_preprocess_imputer
-- Installing: /usr/local/bin/mlpack_radical
-- Installing: /usr/local/bin/mlpack_random_forest
-- Installing: /usr/local/bin/mlpack_range_search
-- Installing: /usr/local/bin/mlpack_krann
-- Installing: /usr/local/bin/mlpack_softmax_regression
-- Installing: /usr/local/bin/mlpack_sparse_coding

I just put the part which shows error here. Any suggestion, where went wrong? Thanks.

**Comment by rcurtin** [comment]
@karlzhang-hhg try using the git master branch, not 3.0.4.  This is a bug in 3.0.4 that got fixed in master (I can't remember exactly which PR though); then you can watch the output and you should see that setuptools doesn't give an error but instead correctly solves the issue.

@kumargopal I'm willing to bet you've encountered the exact same issue, so if you can try the git master branch too, I think it will solve your issue too. :+1:

**Comment by karlzhang-hhg** [comment]
Hi Ryan,
Thanks for quick replying. Actually, Marcus suggested me to do so but I encounter lots of errors didn't encountered when building from 3.0.4 so that I turned back to 3.0.4. I opened a separate issue, and waiting for response. 

To confirm, all I need to do is to download master branch zip, unzip it and follow the building from source instruction in the page https://www.mlpack.org/doc/mlpack-3.0.4/doxygen/build.html, and it should work out? 

Thanks

**Comment by rcurtin** [comment]
Right, the master branch should work, but I took a look at the other issue you opened and I'm not too sure what the issue is.  I saw also the IRC debugging, but I'm not an OS X expert so I don't have too much to add there; sorry about that.

**Comment by karlzhang-hhg** [comment]
> Right, the master branch should work, but I took a look at the other issue you opened and I'm not too sure what the issue is. I saw also the IRC debugging, but I'm not an OS X expert so I don't have too much to add there; sorry about that.

Hi Ryan,
No worry. I will focus on finishing the GSoC2019 proposal first and then I will come back to solve this. I will get a linux system and I think it should work out.

**Comment by Mainak431** [comment]
If 
"sudo make install" was a success. Then just 
execute the three lines below

export LD_LIBRARY_PATH=/usr/local/lib
export LD_LIBRARY_PATH=lib/
export PYTHONPATH=src/mlpack/bindings/python/

then 
python
and in python shell 
import mlpack 

It must be a success. Still if it is not working. Please check your cython version. Maybe you have an outdated cython.

**Comment by kolbma** [comment]
@rcurtin Can you try to find the commit between 3.0.4 and master responsible to get the python binding to work?!

I try to package an RPM for openSUSE. So for this I'd like to have a stable working version. Or do you know when version 3.0.5 would be released?

My import error looks like this:
```
Python 3.6.5 (default, Mar 31 2018, 19:45:04) [GCC] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from mlpack import knn
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib64/python3.6/site-packages/mlpack/__init__.py", line 11, in <module>
    from .adaboost import adaboost
ImportError: cannot import name 'adaboost'
```

Also `from .adaboost import adaboost` looks strange for me!

**Comment by daowanpeng** [comment]
> I built mlpack from source as documented. In python 'import mlpack' doesn't show any error but I can't import any of the modules. Here is the full error:-
> 
> Python 3.6.8 |Anaconda, Inc.| (default, Dec 30 2018, 01:22:34)
> [GCC 7.3.0] on linux
> Type "help", "copyright", "credits" or "license" for more information.
> 
> > > > from mlpack import knn
> > > > Traceback (most recent call last):
> > > > File "", line 1, in 
> > > > ImportError: cannot import name 'knn'
> > > > import mlpack

I have the same problem as you, have you resolve it ?

**Comment by rcurtin** [comment]
@kolbma sorry for the slow response here.  In the time since then we did release mlpack 3.1.0, so I think that should solve your problem (and all the problems here, I hope).  Let me know if there is still an issue.  @daowanpeng can you also try with mlpack 3.1.0?

> Also `from .adaboost import adaboost` looks strange for me!

What's going on here is that we compile a Cython library `adaboost.so` from `adaboost.pyx` which contains just one function, `adaboost()`, so that import just grabs `adaboost()` out of the compiled `adaboost.so`.  If you are saying that there is a better way to do this, I have no idea about that, so if you have a better idea I am all ears. :)

**Comment by AjitDingankar** [comment]
I get the same symptom as @karlzhang-hhg i.e. 
`AttributeError: module 'mlpack' has no attribute 'preprocess_split'`
I installed mlpack 3.1.1 on Windows 10 with vcpkg and bindings in Python 3.7.3 with
`python -m pip install mlpack`
I can only see linear_regression and logistic_regression when I `import mlpack` and look at `dir(mlpack)`

**Comment by rcurtin** [comment]
@AjitDingankar unfortunately the `mlpack` pip package does not refer to this library, so those `linear_regression` and `logistic_regression` functions you are referring to are not from here.  We have had an issue open with PyPI for many months now to request the `mlpack` name (since the existing `mlpack` package is untouched for many years), but this issue has not been responded to.

Instead, you would need the `mlpack3` package.  But, also unfortunately, that isn't currently available on Windows (we are working on it but it isn't ready yet).  If you are on OS X or Linux, though, `pip install mlpack3` should work just fine.

Sorry that I can't provide a better solution at the moment...

**Comment by AjitDingankar** [comment]
Thanks a lot, Ryan for a quick reply! I'll try to move to Linux while waiting for the mlpack3 package to be available for Windows. 

It may be a good idea to clean up the documentation at http://mlpack.org/doc/stable/doxygen/python_quickstart.html 
but I know from another bug report that you're also working on streamlining the docs, so it may not make sense to add another band-aid! :-) 

Thanks,
Ajit
====
