### ISSUE TITLE
Potential bug in Probability function for regression distribution.

### ISSUE THREAD

**Issue by mirraaj** [mlpack/mlpack#1797]

**Comment by rcurtin** [comment]
Hey @mirraaj, thanks for opening the clear issue.  I took a look at `RegressionDistribution` and think I have an idea of what's going on.

 * I think the documentation for `RegressionDistribution` isn't very clear, and you're right, it doesn't seem to have any testing.  If you like, we can leave this issue open after we solve the immediate problem you've had to add tests for it.

 * When `Train()` is called, it uses the first row of the observations as regressors for `LinearRegression`.  See `regression_distribution.hpp` line 48.  So, basically, the `lr` object will expect to receive a point to `Predict()` with one row fewer than `RegressionDistribution` receives.  The only way `Log::Assert()` will get called in this code path is in `LinearRegression::Predict()`, so the problem is in that function.

If you can take a look with a debugger (or just print) the sizes of everything when you call `lr.Predict()`, it should probably become clear exactly what the problem is.  Let me know what you find if you do that. :+1:

**Comment by mirraaj** [comment]
Hello @rcurtin, I studied this error in detail a few days back. I noticed that the error existed in https://github.com/mlpack/mlpack/blob/febc8e312dd2b360e1f26a6bc1a8bdd24164c8e7/src/mlpack/core/dists/regression_distribution.cpp#L64 .  On further exploring I noticed that the major issue lies at https://github.com/mlpack/mlpack/blob/febc8e312dd2b360e1f26a6bc1a8bdd24164c8e7/src/mlpack/methods/linear_regression/linear_regression.cpp#L98 . Training with a `15 feature` dataset (also implemented in #1768 ),` Probability` function reveals that the authors send `14 feature` data for prediction and completely ignore the first observation from each set of observation. The predict function expects a `15 feature` dataset. Here the issue occurs and hence the bug. I am not sure about this distribution and hence I am reading the HMMR paper. In the meantime, could you let me know is there any way around to solve this issue.

**Comment by phantomcoder1996** [comment]
I can try to work on this issue if no one is currently working on it

**Comment by mirraaj** [comment]
@phantomcoder1996 I am already working on it. Is it fine if I continue the work?

**Comment by phantomcoder1996** [comment]
Of course😅
