### ISSUE TITLE
Build problem $ENV{DESTDIR} got expanded on cmake call

### ISSUE THREAD

**Issue by kolbma** [mlpack/mlpack#1834]
#### Issue description

I think you have a mistake in your cmake scripts.
You use `$ENV{DESTDIR}`.
This gets expanded during cmake generating the files for Unix make.
So it gets set to the value the env-var has when calling `cmake`.
But this should be set to the DESTDIR variable when calling `DESTDIR=... make install`!
I need this escaped in the form `\$ENV{DESTDIR}`.

**Comment by chandramoulirajagopalan** [comment]
I would like to work on this issue. Where did you find that $ENV{DESTDIR} in the source code.

**Comment by kolbma** [comment]
[01-fix-lib-path.patch.txt](https://github.com/mlpack/mlpack/files/3046943/01-fix-lib-path.patch.txt)

Hi @chandramoulirajagopalan,
this is my current patch against 3.0.4 tag to support 64-bit arch targets and to make it install in DESTDIR for bundling.

Although up-to-now the python bindings doesn't work on import. But there is another issue for this at https://github.com/mlpack/mlpack/issues/1760#issuecomment-479570820

The `$ENV{DESTDIR}` is in `src/mlpack/bindings/python/CMakeLists.txt`. You can find in patch-file.

br

**Comment by rcurtin** [comment]
Hey @kolbma, thanks for the report.  Have you tried against the git master branch?  There were some fixes for this in the time past.  I understand the report and you are right that at least in 3.0.4 the problem exists exactly as you describe it.  However, newer versions use `PythonInstall.cmake` as a script that's called directly at install time, and I think this may not have the problem you described.  Can you give it a shot and let us know if the problem is still there?  Thanks!

**Comment by kolbma** [comment]
> Can you give it a shot and let us know if the problem is still there? Thanks!

Ok. I'll have a look in the next days...
