### ISSUE TITLE
crash due to not checking eig_sym() for failure in PositiveDefiniteConstraint::ApplyConstraint()

### ISSUE THREAD

**Issue by conradsnicta** [mlpack/mlpack#1840]
`arma::eig_sym()` is not checked for failure in `PositiveDefiniteConstraint::ApplyConstraint()`.
This can lead to a crash due to accessing non-existent eigenvalues.

mlpack/src/mlpack/methods/gmm/positive_definite_constraint.hpp
https://github.com/mlpack/mlpack/blob/2326bf8bd0b380c17eed6b5b1c34fbfab1563774/src/mlpack/methods/gmm/positive_definite_constraint.hpp#L44

The code in `PositiveDefiniteConstraint::ApplyConstraint()` assumes that the `eigval` vector has at least one element, which is a false assumption. If `arma::eig_sym()` fails, `eigval` is reset so that it has no elements -- see the [eig_sym() documentation](http://arma.sourceforge.net/docs.html#eig_sym).

Decomposing a non-symmetric matrix with `arma::eig_sym()` is not guaranteed to work. Furthermore, Armadillo 9.400 will have a rudimentary check for symmetry on the input matrix, which makes failure more likely here.

**Comment by conradsnicta** [comment]
Similar problems with eig_sym():
* https://github.com/mlpack/mlpack/blob/master/src/mlpack/core/math/lin_alg.cpp#L88
* https://github.com/mlpack/mlpack/blob/master/src/mlpack/methods/gmm/eigenvalue_ratio_constraint.hpp#L67
* https://github.com/mlpack/mlpack/blob/master/src/mlpack/methods/kernel_pca/kernel_rules/nystroem_method.hpp#L67
* https://github.com/mlpack/mlpack/blob/master/src/mlpack/methods/kernel_pca/kernel_rules/naive_method.hpp#L76
* https://github.com/mlpack/mlpack/blob/master/src/mlpack/tests/gmm_test.cpp#L629

Similar problems with chol():
* https://github.com/mlpack/mlpack/blob/master/src/mlpack/core/dists/gaussian_distribution.cpp#L42
* https://github.com/mlpack/mlpack/blob/master/src/mlpack/methods/gmm/gmm.cpp#L120

**Comment by chandramoulirajagopalan** [comment]
Can I work on this issue ?

**Comment by zoq** [comment]
Sure, feel free to work on the issue.

**Comment by chandramoulirajagopalan** [comment]
How about writing a try catch block in order to make the code free from generating runtime exceptions ? Will that work or any other idea ?

**Comment by chandramoulirajagopalan** [comment]
Generating an error output and then asking it to be fixed will work right ? Instead of getting a runtime exception.

**Comment by rcurtin** [comment]
@chandramoulirajagopalan: Conrad just opened a PR in ensmallen with an example of how we should handle these issues.  You can adapt that strategy.

**Comment by conradsnicta** [comment]
For the specific case of `PositiveDefiniteConstraint::ApplyConstraint()`, I suggest calling [`arma::symmatu()`](http://arma.sourceforge.net/docs.html#symmat) or [`arma::symmatl()`](http://arma.sourceforge.net/docs.html#symmat) before doing the eigen decomposition via [`eig_sym()`](http://arma.sourceforge.net/docs.html#eig_sym).  This is in addition to checking whether the eigen decomposition succeeded.

Example: `covariance = arma::symmatu(covariance);`

One problem with `PositiveDefiniteConstraint::ApplyConstraint()` is that there is no way for the function to tell the caller that applying to constraint could not be accomplished. I also suggest refactoring it so  a `bool` is returned indicating success.

**Comment by chandramoulirajagopalan** [comment]
Should I give an error output if the values don't exist ?

**Comment by chandramoulirajagopalan** [comment]
For Cholesky Decomposition the method returns a double value what to return if it fails, apart from an error message ?

**Comment by chandramoulirajagopalan** [comment]
Created a pull request can someone check that out ? Any improvements needed ?

**Comment by chandramoulirajagopalan** [comment]
Should we use is_empty() to check if the matrix is reset or not for chol() function to prevent from runtime error ?

**Comment by conradsnicta** [comment]
@chandramoulirajagopalan You may have used an old version of mlpack as the base for your work. For example, why are you modifying the following files ?
src/mlpack/methods/ann/layer/lstm.hpp  
src/mlpack/methods/ann/layer/lstm_impl.hpp  
src/mlpack/tests/ann_layer_test.cpp  
src/mlpack/methods/reinforcement_learning/q_learning_impl.hpp  

Also, it's not clear why you have `#include <iostream>`, and use the `cerr` stream. mlpack already has its own specific streams for logging, such as `Log::Fatal`, `Log::Debug`, `Log::Info`, `Log::Warn`. Example:

    Log::Warn << "message" << std::endl;

**Comment by chandramoulirajagopalan** [comment]
That was my first pull request so did not know how to do it. I will fix them now and make a new pull request.

**Comment by conradsnicta** [comment]
@chandramoulirajagopalan You may also want to have a look at the documentation for arma::chol(). There is a form which outputs a bool to indicate success.

**Comment by chandramoulirajagopalan** [comment]
@conradsnicta The documentation under arma::chol() doesnot have any boolean functions to check if it succeeded or not. Maybe checking if the decomposed matrix is empty or not would work fine I guess.

**Comment by conradsnicta** [comment]
@chandramoulirajagopalan Your code is still not right.  The documentation for [chol()](http://arma.sourceforge.net/docs.html#chol) states:
> If the decomposition fails:
> - R = chol(X) resets R and throws a std::runtime_error exception
> - chol(R,X) resets R and returns a bool set to false (exception is not thrown)

The following will throw an exception if the decomposition fails:

    covLower = arma::chol(covariance, "lower");

so it will never reach this point:

    // Check if Cholesky Decomposition exists, if not raise an error log.
    if (covLower.is_empty())
    {
      Log::Fatal << "Cholesky Decomposition failed as Matrix is Empty ." << std::endl;
      return;
    }

To do this properly, use this code along these lines:

     mat covLower;
     
     if(arma::chol(covLower, covariance, "lower") == false)
     { ... handle failure here ... }

Handling `eig_sym()` failures can be done in a similar manner.

**Comment by chandramoulirajagopalan** [comment]
okay thanks yeah will modify that

**Comment by chandramoulirajagopalan** [comment]
But according to the decomposition the matrix will be reset right ? So what if we check if it is empty or not after the decomposition ? It is not safe to access memory locations that aren't present but here if the decomposition fails it is being reset so checking after the assignment will affect the program ?

**Comment by conradsnicta** [comment]
@chandramoulirajagopalan Make sure you only modify the files that are specific to fixing these bugs. In your PR you modified `src/mlpack/methods/linear_svm/linear_svm_impl.hpp`, which is not related to these bugs.

In the function `PositiveDefiniteConstraint::ApplyConstraint()`, I recommend to explicitly enforce symmetry on the given matrix via `symmatu()` or `symmatl()`.

**Comment by conradsnicta** [comment]
@chandramoulirajagopalan As the documentation states, if `R = chol(X)` fails, R is reset _and_ and exception is thrown. The exception will cause the program to be immediately aborted, as the exception is not caught.

**Comment by chandramoulirajagopalan** [comment]
I modified src/mlpack/methods/linear_svm/linear_svm_impl.hpp because the style checks wasn't building properly and there was some extra space inside the function arguments, so I just deleted it to make sure it was passing the build and yes I will make exceptions for that as you said. I have one more problem http://ci.mlpack.org/job/pull-requests-mlpack-static-code-analysis/1469/cppcheckResult/ I didn't even change anything about logDetCov. Static Code analysis is not building at all

**Comment by chandramoulirajagopalan** [comment]
Can you verify the commit? Is it as required or any other changes to be done ?

**Comment by conradsnicta** [comment]
@chandramoulirajagopalan Your code still has lots of mistakes.  I suggest you thoroughly analyse the program flow, and run tests on each function that you change, before submitting pull requests.

**Comment by chandramoulirajagopalan** [comment]
I am closing the pull request for now. Can you please review the code I commit into my forked repository so that it will be easy instead of building it every time I commit.

**Comment by conradsnicta** [comment]
@chandramoulirajagopalan sorry, I won't have time to go through your repo. I suggest you submit another PR after you have fixed all the problems and thoroughly tested the code (both automatically and manually, by carefully analysing the program flow).

**Comment by chandramoulirajagopalan** [comment]
okay thanks will do that.

**Comment by chandramoulirajagopalan** [comment]
@conradsnicta https://math.stackexchange.com/questions/654465/do-all-square-matrices-have-eigenvectors This link above says every matrix has eigenvalues but it depends whether it is real or complex. So I think the issue here is to check whether the eigenvalue returned is complex or not ? If there are any matrix which do not have eigen values.So the condition here is to check whether the input matrix is symmetrix and is not empty. 
Even this code mat covLower;
 
 if(arma::chol(covLower, covariance, "lower") == false)
 { ... handle failure here ... }

Will not work as we are executing the function chol() inside if statement if it fails it will still throw an error. So we should try doing try catch instead.

**Comment by chandramoulirajagopalan** [comment]
I think this should do
```
if ((mat.is_empty() ==  true) || (mat.is_symmetric() == false))
    {
      Log::Fatal << "Eigen Decomposition failed as Eigen Value "
            << "does not exists ." << std::endl;
      return;
    }
```
This should be fine before executing eig_sym().

**Comment by chandramoulirajagopalan** [comment]
@rcurtin Will that idea work ? Because when I tested it locally I got error while executing the following [code](https://github.com/mlpack/mlpack/issues/1840#issuecomment-480798003) So I just went through the stackoverflow [link] (https://math.stackexchange.com/questions/654465/do-all-square-matrices-have-eigenvectors) , since arma:: matrices can return complex numbers too there is always eigenvalues for every matrix that is square, symmetrical and is not empty. So I guess the ideal case would be to check if the matrix is symmetrical and not empty since it is square we need not bother about it. So I guess these checks are good enough to avoid the decomposition runtime error ? Should I proceed further implementing the code everywhere.

**Comment by chandramoulirajagopalan** [comment]
@rcurtin Will that idea work ? Because when I tested it locally I experienced runtime errors while executing the following [idea](https://github.com/mlpack/mlpack/issues/1840#issuecomment-480798003). So I just went through this stackoverflow [link](https://math.stackexchange.com/questions/654465/do-all-square-matrices-have-eigenvectors), since arma:: matrices can return complex numbers too there is always eigenvalues for every matrix that is square, symmetrical and is not empty. So I guess the ideal case would be to check if the matrix is symmetrical and not empty since it is square we need not bother about it. So I guess these checks are good enough to avoid the decomposition runtime error ? Should I proceed further implementing the code everywhere.

**Comment by conradsnicta** [comment]
@chandramoulirajagopalan I suggest you re-read the docs for chol(), eig_sym() and eig_gen().

**Comment by chandramoulirajagopalan** [comment]
I have gone through the docs @conradsnicta but while I try to execute it under cases where eigenvalues do not exist I still get runtime error.  Log::Fatal does not get executed. The block inside if is returning a runtime exception. So instead of running the function eig_sym() the only way I thought to avoid the runtime error is by checking if the matrix is empty or if it is not symmetrical or if it is not square shaped. So if these three basic conditions are met it is compiling. According to the link  https://math.stackexchange.com/questions/654465/do-all-square-matrices-have-eigenvectors every matrix has eigen values I tried using the example from the above link it still executes. So I thought it would be easy to check if they are empty or not.

**Comment by chandramoulirajagopalan** [comment]
@conradsnicta 
https://gitlab.com/conradsnicta/armadillo-code/blob/9.400.x/include/armadillo_bits/auxlib_meat.hpp#L1698
the if condition in the library is returning true if the eigenvec is empty and the size of eigenval depends on the size of eigenvec https://gitlab.com/conradsnicta/armadillo-code/blob/9.400.x/include/armadillo_bits/auxlib_meat.hpp#L1707 so the size of eigenval will be zero only when eigenvec is zero (i.e. if eigenvec is empty) but when eigenvec is empty the code returns true so the if condition which we wrote does not execute since it returns true and eigenval[0] gets called and we are getting runtime error once again. I think  https://gitlab.com/conradsnicta/armadillo-code/blob/9.400.x/include/armadillo_bits/auxlib_meat.hpp#L1698 it should return false here which will fix our issue.

**Comment by conradsnicta** [comment]
@chandramoulirajagopalan You're not understanding how the code works.  What does `return (info == 0)` do?  Where is the variable `info` modified?  Please trust the documentation instead of reading through internal armadillo code.

**Comment by chandramoulirajagopalan** [comment]
I get eig_sym() value to be true even if the input matrix is empty while executing the code. So and then while calling eigval[0] it returns a runtime error again.

**Comment by conradsnicta** [comment]
That's a separate issue from an actual eigen decomposition failure.

**Comment by chandramoulirajagopalan** [comment]
what should I return for a vector when there is failure in eigen decomposition.

**Comment by chandramoulirajagopalan** [comment]
I get failure in the test cases. What's to be done and the spaces in one of the file ? Can someone help me with that  please ?

**Comment by conradsnicta** [comment]
Closing as the discussion has veered off into tutorials on linear algebra and how to code. Feel free to open as a fresh new issue.

**Comment by conradsnicta** [comment]
Reopening as #2088 is being worked on.
