### ISSUE TITLE
mlpack_test.exe fails for some tests when running on Windows [3.1.1 release]

### ISSUE THREAD

**Issue by gmanlan** [mlpack/mlpack#1863]
When building mlpack x64 from source, some tests fail when executed in a local Windows 10 system. These errors are diverse so if required, we can split them into different submissions.

**Build configuration:**
- mlpack 3.1.1 release or master branch
- Boost 1_65_1 (lib64-msvc-14.1)
- armadillo-9.300.2
- OpenBLAS built using msvc - branch develop (April 2019)
- Visual Studio 15 2017 Win64
- x64
 
**Tests Errors:**
1) unknown location(0): fatal error: in "ConvolutionalNetworkTest/VanillaNetworkTest": memory access violation
**Possible workaround:** manually unzip the .arm dataset from mnist_first250_training_4s_and_9s.tar, then the test will pass

2) unknown location(0): fatal error: in "LoadSaveTest/CaseTest": class std::runtime_error: Parse error at line 13 token 0: "TA".
Context: this is trying to parse the file casecheck.arff

3) parallel_sgd_test.cpp(100): fatal error: in "ParallelSGDTest/GeneralizedRosenbrockTest": absolute value of result{-nan(ind)} exceeds 1e-08

4) unknown location(0): fatal error: in "SdpPrimalDualTest/SmallLovaszThetaSdp": memory access violation occurred at address 0xfcfc4000, while attempting to  write to an inaccessible (or protected) address. sdp_primal_dual_test.cpp(278): last checkpoint: "SmallLovaszThetaSdp" test entry

5) input stream error tests/serialization.hpp(235): fatal error: in "SerializationTest/LayerNormSerializationTest": critical check success == true has failed [false != true]

6) main_tests/decision_tree_test.cpp(103): fatal error: in "DecisionTreeMainTest/DecisionTreeCategoricalOutputDimensionTest": Cannot load train dataset braziltourism.arff!

I made an effort to go over open/closed issues and although I found some references, I couldn't find exact matches with these errors. If somebody has seen some of this issues before, please link them here.

I have also checked one of the last AppVeyor builds and the tests seem to be passing fine, so I'm trying to understand if these failures are because:
- Something is wrong with my local system?
- Boost version? (AppVeyor build script is using 1.60)
- Armadillo version? (AppVeyor build script is using 7.800.2)
- Visual Studio version? (for some reason AppVeyor build script is using Visual Studio 14 2015 Win64 for both the Jobs? If so, the VS2017 job is useless?)

Thanks

**Comment by jeffin143** [comment]
@gmanlan , did u reproduce the issue with 3.1.0 ?

**Comment by gmanlan** [comment]
I have tried again using the master-branch and I got the "VanillaNetworkTest: memory access violation" error again - which I can workaround by unzipping the dataset (although the error description doesn't make sense). Then I get the following errors:

```
Running 1607 test cases...
[FATAL] Cannot open file 'nonexistentfile.arff'.

unknown location(0): fatal error: in "RBMNetworkTest/BinaryRBMClassificationTest": integer divide by zero
C:\mlpack\mlpack-python-windows-fix\src\mlpack\tests\rbm_network_test.cpp(42): last checkpoint: "BinaryRBMClassificationTest" test entry
unknown location(0): fatal error: in "RBMNetworkTest/ssRBMClassificationTest": integer divide by zero
C:\mlpack\mlpack-python-windows-fix\src\mlpack\tests\rbm_network_test.cpp(127): last checkpoint: "ssRBMClassificationTest" test entry

*** 2 failures are detected in the test module "mlpackTest"
```

**Comment by rcurtin** [comment]
Sorry for the slow response---I know that `[FATAL] Cannot open file 'nonexistentfile.arff'.` is actually not a problem: the tests check that that file doesn't exist.

But the RBM tests are a bit more problematic.  However, I haven't seen this problem.  On my Windows VM (which ended up being Windows 7 just because that happened to get set up ok...) I have the following versions of packages:

 - Armadillo 9.600-RC3
 - Boost 1.70.0
 - OpenBLAS 0.2.14.1
 - Visual Studio Community 2019, version 16.1.6

Of those I would expect the only two to make a difference would be Armadillo and possibly the Visual Studio version.  The output I get for the RBM tests when I build the "RUN_TESTS" target is that they pass in ~15 seconds; no `integer divide by zero` issue or anything.

If AppVeyor is not successfully building on Visual Studio 2017, we should definitely get that fixed for sure.  I think I see the issue: the `build_script` section uses `Visual Studio 14 2015 Win64` hardcoded, but it should actually be using the `VSVER` variable.  I'm not sure exactly how that works in the AppVeyor config, but I'll see if I can find a minute to put into it in the near-term future.

**Comment by rcurtin** [comment]
I opened #1971 to handle the Visual Studio version issues, so now AppVeyor will build mlpack on VS2015, VS2017, and VS2019.
