### ISSUE TITLE
Code of Conduct

### ISSUE THREAD

**Issue by zoq** [mlpack/mlpack#1894]
One of the requirements to become a sponsored project of NumFOCUS (see [1] for more details) is to have a Code of Conduct. After some research, I would adopt the Contributor Covenant CoC (see [2] for more details), which is a drop-in code of conduct that is used by over 40,000 open source projects, including Kubernetes and Rails. The document covers the main points and is clearly written. In addition, I would adopt the reporting document of the Django project (see [3] for more details), it's not necessarily necessary to have reporting guidelines but I think it does lower the burden for reporting incidents and is definitely helpful to resolve issues.

I think it's reasonable to leave this open for a week, and if there is
no objection I can start to incorporate the documents.

[1] http://knife.lugatgt.org/pipermail/mlpack/2019-April/004058.html
[2] https://www.contributor-covenant.org/version/1/4/code-of-conduct
[3] https://www.djangoproject.com/conduct/reporting/

**Comment by conradsnicta** [comment]
In principle I'm okay with most of the CoC. However, the following clause/point is problematic: "Other conduct which could reasonably be considered inappropriate in a professional setting".

I agree with the spirit of the clause, but not the letter.  Putting on a lawyer hat, the problem is that the clause is too open ended, subject to interpretation, and context dependent (eg. "what" professional setting?). This in turn can create a bunch of loop holes that can be exploited in bad faith. 

The CoC also has another clause/point with similar problems: "Focusing on what is best for the community".  Here, "best" is subject to interpretation and context dependent.

In contrast, most of the other points/clauses tend to be more specific, reducing wiggle room.

I'd suggest to adopt a modified form of the CoC, leaving out the problematic points.

**Comment by zoq** [comment]
Agreed, we should probably remove the points from the document. I think you can say each point in the "Our Standards" section is somewhat vague. But the two points mentioned might be to open ended.

**Comment by rcurtin** [comment]
I feel somewhat lucky that we've never needed a code of conduct (or at least I have never perceived a serious and urgent need for one); I've seen some really harsh and awful conduct on other repositories in the past.  So, having a CoC is definitely a good thing, and I think it is the norm for projects to include these now.  The CoC you linked to is just fine to me, though Conrad does have a point about the subjective nature of a few of those points.  I'm ambivalent on the inclusion or exclusion of those specific clauses; either way is just fine with me.

Thanks for taking the initiative to do this. :+1:

**Comment by zoq** [comment]
Thanks for the reminder.

**Comment by rcurtin** [comment]
Do you want to open a PR to add the code of conduct?  I'm fine with what we've discussed here. :+1:

**Comment by zoq** [comment]
Yes, will open a PR soon.

**Comment by ShikharJ** [comment]
Fixed via #1925.
