### ISSUE TITLE
Problem while trying MLPACK as a library in CMAKE project

### ISSUE THREAD

**Issue by MounaKaroui** [mlpack/mlpack#1938]
Hello,
I added ML pack as a library in a Cmake project, when I  tried to use MLpack in my C++ project, I obtained the error below:
![mlpackTest](https://user-images.githubusercontent.com/11929939/60000273-2a2d0400-9664-11e9-8387-e60c74af3494.png)
I didn't understand what is the source of this problem

Regards,

**Comment by zoq** [comment]
Do you link against armadillo as well? Perhaps you can post a simplified project to reproduce the issue? Here is a more or less simple CMake file that links against mlpack/armadillo.

**Comment by rcurtin** [comment]
This looks like a rather strange issue, and my initial feeling is that this may be caused by some incorrect code just before `#include <mlpack/core.hpp>`.  In any case, a reproducible example code snippet (i.e. we can try compiling it ourselves and see the failure) and more information on your system, like the compiler version and the command you are using to compile, could be really helpful. :+1:
