### ISSUE TITLE
Make Action.action a double in mlpack 4.0.0

### ISSUE THREAD

**Issue by favre49** [mlpack/mlpack#2003]
Following discussion in IRC, this change was reverted in PR #1996 . We should make this change once more when we release mlpack 4.0.0, since it removes backwards compatibility.

**Comment by himanshupathak21061998** [comment]
@favre49 Can I work on this

**Comment by favre49** [comment]
This was a change that was made to the API last year, that was reverted on realizing it would result in a major version bump. Seeing as there are no plans on releasing a `4.0.0` version yet, there is no reason to work on this. If you are looking for issues to work on, perhaps issues tagged "Good first issue" would be of interest to you :)

**Comment by rcurtin** [comment]
I think this one still needs to be handled, so I'll reopen it :+1:

**Comment by IWNMWE** [comment]
Hey @favre49 for this issue we just need to bring back the changes that were reverted rightt??

**Comment by IWNMWE** [comment]
@rcurtin  Hey Ryan, I would like to know whether it was decide that all continuous env action were decide to be of type array as mentioned in #2497 or do we still need to change it because the type used in https://github.com/mlpack/mlpack/blob/master/src/mlpack/methods/reinforcement_learning/sac_impl.hpp
is also of type double vector and would require changes
