### ISSUE TITLE
Setting up mlpack on Windows

### ISSUE THREAD

**Issue by jzy95310** [mlpack/mlpack#2105]
Hi Developers,

I think the tutorial of building mlpack on Windows is not friendly to users who is not familiar with bash commands and Visual Studio. 

It took me 4 days to install the mlpack and its dependencies, and up to now I still cannot make it work in Visual Studio. At first I tried installing mlpack with vcpkg, and it took about 7GB space to download and install the whole package. Then it says "the library is ready to be included", but I copy and paste the code in the given C++ sample, it still cannot compile.

Then I re-read the tutorials and re-installed the dependencies, but I got stuck on the step using CMake. It always prompted out an error saying "C:/CMake does not appear to contain CMakeLists.txt", and I did not know why this happened.

I also went through the tutorials written by other developers, and it seems very different with the one on the official website. I don't know which tutorial I should follow, and I think it would be great if you can post a step-by-step tutorial with images on your website instead of just putting code here and there and saying something like "Run CMake". This is very confusing.

Thanks in advance.

**Comment by rcurtin** [comment]
Hey @jzy95310, thanks for the feedback and sorry that things were frustrating.  The "official" tutorial at http://mlpack.org/doc/mlpack-3.2.2/doxygen/build_windows.html is the best that we have to offer.  Unfortunately, very few of mlpack's developers use Windows natively, and doing development on Windows is *just plain hard* due to the unsuitability of the environment.  That's not a knock against Windows in general, but objectively speaking, I can't think of a harder ecosystem in which to build mlpack.  The ecosystems in OS X and Linux are much more suited not just to mlpack development but to development in general.  Maybe you might consider switching?  (I realize that that may not be possible, but I'm trying to give the best suggestions I can :))

Personally, if you don't have familiarity with bash or Visual Studio, I'd advise against compiling mlpack and see if instead you can find a way to download a precompiled version.  The website has an installable MSI that you can download:

http://www.mlpack.org/ -- you can see the link 'mlpack-3.2.2.msi'

I'm happy to try and help you through the confusing parts of the tutorial, but I would say that it would be important to be familiar with Visual Studio and the general C++ compilation process, otherwise I think basically no matter what it will be a really difficult thing to do.

**Comment by zoq** [comment]
I guess an option would be a guided batch file, that installs and configures all dependencies. Do you think that would be helpful? But I agree Windows improved over the years but I don't think it matches the simplicity of other systems.

**Comment by jzy95310** [comment]
Hi @rcurtin,

Thank you so much for your advice! I think I can try building mlpack on Linux using VitualBox. Currently I have Ubuntu 18.04 installed. However, the sudo command still does not seem to work for me. It always prompts me an error saying "E: Could not open lock file /var/lib/dpkg/lock-frontend - open" when I try installing dependencies with apt-get. Shall I change to a lower version of Ubuntu in this case?

**Comment by zoq** [comment]
This is an Ubuntu related issue, https://itsfoss.com/could-not-get-lock-error/ might be helpful. Also maybe instead of using VirtualBox, you could use Windows Subsystem for Linux?

**Comment by jzy95310** [comment]
@zoq Thank you! I will give it a try.
