### ISSUE TITLE
Implementing Attention layer for CNN

### ISSUE THREAD

**Issue by himanshupathak21061998** [mlpack/mlpack#2177]
Right now we don't have implementation of attention layer for CNN. We can add this layer as it will help the user to make use attention mechanism based CNN.

**Comment by kartikdutt18** [comment]
Hi @himanshupathak21061998 , Could refer a library where they have a attention layer specifically for CNN because from what I understand we can use a model such as VGG and use output of CNN layer at different points across a model and use recurrent_attention_layer. I think tensorflow or pytorch do the same-thing where they have attention layer whose input is output of cnn. So I maybe wrong but this is already implemented, However it might find a better place in model project. However a member of this organization will provide better insight.

**Comment by kartikdutt18** [comment]
Hi @himanshupathak21061998, I was working on making a generalized structure on models library where people could import models and use them by making changes required for their dataset and such a block would make a nice addition. However,  I think a member of this organization will provide better insight.

**Comment by himanshupathak21061998** [comment]
Hello @kartikdutt18 Yes, you are right it is already implemented another oops moment from my side it's not good. I specifically mentioned CNN because it is most useful for CNN. That's a good idea of generalized structure on models library may be should talk to member about this. However I am closing this issue.

**Comment by kartikdutt18** [comment]
Not an issue.

**Comment by pmixer** [comment]
There are different kinds of Attention https://lilianweng.github.io/lil-log/2018/06/24/attention-attention.html
