### ISSUE TITLE
Website missing math symbols

### ISSUE THREAD

**Issue by jamiebullock** [mlpack/mlpack#2190]
#### Problem location

https://mlpack.org/doc/mlpack-3.0.4/doxygen/nstutorial.html

#### Description of problem

It seems like math symbols are not being rendered on the website.  So there are gaps in the text as shown below.

<img width="1029" alt="Screen Shot 2020-02-09 at 11 40 37" src="https://user-images.githubusercontent.com/579188/74101397-51700d00-4b31-11ea-8075-23a5af4a0cce.png">

**Comment by zoq** [comment]
Thanks for the report, will look into the issue.

**Comment by rcurtin** [comment]
Ha, I know why this happened.  We switched from a white-on-black to black-on-white website, but the scripts still invert the Doxygen images.  Fixed in https://github.com/mlpack/mlpack.org/compare/f054f4fc8486abe5a096649ad76aae121d51dcc0...3e86fe4fbf403d4a79f6b86eb80c01d8538d4164 and I redeployed the site.  Thanks for pointing it out! :+1:
