### ISSUE TITLE
Error while building mlpack - in visual studio 2019 windows

### ISSUE THREAD

**Issue by joeljosephjin** [mlpack/mlpack#2212]
#### Issue description

I want to build mlpack from source for windows. The error is coming up when i build it.
#### Your environment

 * version of mlpack: latest
 * operating system: windows
 * compiler: visual studio 2019 latest
 * version of dependencies (Boost/Armadillo): latest x64
 * any other environment information you think is relevant:

#### Actual behavior
Error in VS Windows:
"LINK2005	"public: __cdecl boost::program_options::error_with_option_name::error_with_option_name(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,int)" (??0error_with_option_name@program_options@boost@@QEAA@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@00H@Z) already defined in boost_program_options-vc140-mt-gd.lib(boost_program_options-vc142-mt-gd-x64-1_72.dll)	mlpack_adaboost	C:\mlpack\mlpack\src\mlpack\methods\adaboost\libboost_program_options-vc142-mt-gd-x64-1_71.lib(value_semantic.obj)	1	
"

**Comment by rcurtin** [comment]
Hmm, I think that this is similar to what @himanshupathak21061998 is fighting with for the Conda mlpack build in https://github.com/conda-forge/mlpack-feedstock/pull/18.  I have two ideas, but I'm not sure how well either will work...

 - Could you try building with a version of Boost older than 1.70?  e.g. Boost 1.69 would be fine, or older too
 - What happens if, when configuring with CMake, you set the variable `Boost_NO_BOOST_CMAKE` to `1` and then rebuild?  Does it link properly then?

**Comment by himanshupathak21061998** [comment]
@rcurtin May be Boost_NO_BOOST_CMAKE would not work. @joeljosephjin I think you should try different version of Boost.

**Comment by himanshupathak21061998** [comment]
@rcurtin I think we should keep this once I found a workaround for this we will close it.
