### ISSUE TITLE
Incremental Epsilon-neighbors

### ISSUE THREAD

**Issue by JohnLangford** [mlpack/mlpack#2322]
I have a neighbor problem with reference and query sets, so naturally I looked into mlpack.  However, I'm not quite finding what I was hoping for, so I wanted to check if I'm missing something after my documentation + code skim.  Am I?

The problem in more detail:
I have a reference set which grows over time, so I want to have a reference tree supporting incremental insertion.  I have a query set which grows over time, so I want to have a query tree supporting incremental insertion.  I want to be able to query for whether or not the reference set contains points within epsilon (under my chosen metric) of points in the query set. 

Is this possible now?  If not, what's the delta to make it happen?

**Comment by rcurtin** [comment]
Hey John, hope you're doing well.

What we found over time is that insertion into kd-trees degrades performance, enough so that when growing a reference set it's often best to simply rebuild the tree from scratch.  But in your situation, if lots of points are being incrementally inserted, the kd-tree would definitely be a bad choice.  I think that what might be better here is a structure like the R tree, which was intended for incremental insertions and mlpack does implement as the `RectangleTree` class (it's typedef'ed to `RTree`, and there are other variants too, like the R* tree, etc.).

However, there are some trickinesses to actually making this work, and this is because Armadillo matrices aren't particularly conducive to incremental insertion (i.e., there's no functionality like `push_back()`, and if you do do `join_cols()` or something, the entire matrix ends up being reallocated).  But I think it's possible.  Here's some code:

```
using namespace mlpack;
using namespace mlpack::tree;
using namespace mlpack::neighbor;
using namespace mlpack::metric;

arma::mat dataset; // This should be filled with the initial reference set.

// Create the initial KNN object on an R tree. (Easy to change to R* tree, X tree, etc.).
// This will build the initial R tree.
NeighborSearch<NearestNeighborSort, EuclideanDistance, RTree> knn(std::move(dataset));

// Now the tree is accessed via knn.ReferenceTree(), and its dataset is accessed via knn.ReferenceTree().Dataset().

// If we wanted to add a point, we should be able to do this...
arma::vec newPoint; // This can represent a new point we want to add.  (Change to arma::mat for a new set of points.)
const size_t numPoints = knn.ReferenceTree().Dataset().n_cols;
knn.ReferenceTree().Dataset().insert_cols(numPoints - 1 /* I think this is right */, newPoint);
// Now make the tree insert the point too.
knn.ReferenceTree().InsertPoint(numPoints /* this is the index of the new point */);
```

Then, I *think*, after you do this, if you ran `knn.Search()`, it would give updated results.  I haven't tried the code, though, so no guarantees. :)

I have noticed in the past that the R-trees tend to give worse performance than the kd-tree for nearest neighbor search tasks, but, I think that's the price to be paid for the incremental insertion ability.  If you can say that the problem is such that you'll be reinserting lots of points and then only querying the updated tree every now and then, it's possible that you may be better off just rebuilding that kd-tree in bulk.

Let me know if I can clarify anything, this is a bit of an "off the top of my head" response. :+1:

**Comment by rcurtin** [comment]
Also, perhaps @lozhnikov might have some comments on this one, he wrote a lot of the R tree support.  (No worries if not, but I figured the tag might be useful.)

**Comment by JohnLangford** [comment]
Thanks Ryan.   

Does knn.search() support epsilon-neighbors instead of nearest neighbors?  Basically, I want the computation to be approximately zero when query and reference trees are far apart rather than substantially more when a nearest neighbor search struggles to find the nearest of many far-away neighbors.

**Comment by rcurtin** [comment]
Yeah, you can set relative error either as an argument to the constructor of `NeighborSearch`, or call `knn.Epsilon() = relative_error_tolerance`.  You could also set the search mode to `GREEDY_SINGLE_TREE_MODE` to avoid any backtracking at all, but then there's no error guarantee: `knn.SearchMode() = GREEDY_SINGLE_TREE_MODE`. :+1:

**Comment by JohnLangford** [comment]
I'm not looking for relative error here---in fact I'd like no error at all.  I just want to answer the question: "Is there a point in set A which is within epsilon of a point in set B?"  The identity of such points is optional but welcome.   Make sense?

**Comment by rcurtin** [comment]
Oh, I see---sorry, I misunderstood the problem.  I know how this can be done, but the nearest neighbors implementation won't support it.  Correct me if I'm still off, but I believe the problem is, given sets A and B, determine if there exists a pair (q, r) where q \in A, r \in B such that d(q, r) < epsilon.  Is that right?  If so, this could be solved efficiently in low(ish) dimensions by dual-tree range count, but at the moment that isn't implemented.

**Comment by JohnLangford** [comment]
Right, thanks.

**Comment by rcurtin** [comment]
:+1: sounds good.  In any case, happy to talk more about the fast range count algorithm if you like---it wouldn't be hard to implement.
