### ISSUE TITLE
Logistic Regression Test Fails on Azure.

### ISSUE THREAD

**Issue by kartikdutt18** [mlpack/mlpack#2366]
The Logistic Regression Test fails on azure for most PRs that made a commit today. Here is the link to one of [them](https://dev.azure.com/mlpack/mlpack/_build/results?buildId=1429&view=logs&j=1b38ea94-fede-5667-20eb-44d3de1ec085&t=72087b03-c17c-5a26-b713-236d9bb6c096&l=149). Locally they run fine alteast on my machine. This might be a good first issue to get started with testing. This issue is open for taking up. Let me know if you need any help. Thanks a ton.

**Comment by jeffin143** [comment]
Might be because of https://github.com/mlpack/mlpack/pull/2359 , not sure 


Taking a guess

**Comment by kartikdutt18** [comment]
Think so too. Also not sure.

**Comment by rcurtin** [comment]
Interesting, it passed the build in that PR though.  I'll try to investigate tonight.  Does it happen on every PR or only sometimes?

**Comment by kartikdutt18** [comment]
I think it failed on the last 4 PRs (maybe all).

**Comment by rcurtin** [comment]
Ok, I'll take a look.  Sorry about that...

**Comment by kartikdutt18** [comment]
I think this fails on all PRs. Just checked it failed on the last 5 PRs.

**Comment by rcurtin** [comment]
I've been looking into this over the weekend.  It's not at all straightforward.  But I'm able to reproduce it, though only on an OS X system.  In short, for some reason, an Armadillo expression that is `vector * sparse_matrix` gets interpreted as `diagmat(vector) * sparse_matrix`, which leads to incorrect results.  That only seems to happen on OS X, and only with Armadillo 9.860.1.  So, I haven't gotten to the bottom of it quite yet, I'm still digging...  I'm interested to see what the issue is when I finally do get there. :)

**Comment by jeffin143** [comment]
I guess this happens to many of those , IG my brnn callback pr would fail in osx for similar reasons

**Comment by rcurtin** [comment]
Right, all of the OS X builds will currently fail with this error. :+1:

**Comment by kartikdutt18** [comment]
> That only seems to happen on OS X, and only with Armadillo 9.860.1. So, I haven't gotten to the bottom of it quite yet, I'm still digging... I'm interested to see what the issue is when I finally do get there. :)

Great, Thanks a lot.

**Comment by conradsnicta** [comment]
> an Armadillo expression that is `vector * sparse_matrix` gets interpreted as `diagmat(vector) * sparse_matrix`, which leads to incorrect results. That only seems to happen on OS X, and only with Armadillo 9.860.1.

@rcurtin It's a bug in Armadillo 9.860.1.  Fixed in 9.860.2.  The bug is not present in earlier versions (eg. 9.850.x, 9.800.x, etc). MacPorts has already updated its Armadillo [package](https://www.macports.org/ports.php?by=name&substr=armadillo). Homebrew [package](https://formulae.brew.sh/formula/armadillo) still at 9.860.1.

More info on the bug: https://sourceforge.net/p/arma/news/2020/04/armadillo-c-linear-algebra-version-98602-bug-fix-release-/

**Comment by rcurtin** [comment]
@conradsnicta beat me to it. :)  I had mostly stepped through the code to figure out what is going on, but I never got to the point of understanding why 9.860.1 didn't fail in the same way on OS X.  (Not sure if it's a clang issue or what, hadn't gotten that far.)

I see you literally just opened https://github.com/Homebrew/homebrew-core/pull/53139; once that's merged, our builds should be fixed and then we can close this issue.

Thanks! :100:

**Comment by kartikdutt18** [comment]
I am closing this then. Thanks a lot.

**Comment by jeffin143** [comment]
I don't think so we should close this soon , let it sit there until that pr is merged so that if some else faces the issue , they can know what's the reason

**Comment by bisakhmondal** [comment]
Great work @conradsnicta, but still it's failing in #2370.

**Comment by kartikdutt18** [comment]
Hey @jeffin143, I think Homebrew/homebrew-core#53139 this PR is merged.

**Comment by jeffin143** [comment]
I would recommend this to let sit for some more time , it won't harm IG

**Comment by rcurtin** [comment]
@bisakhmondal we're probably just a bit too fast---from the build log:
```
==> Pouring armadillo-9.860.1.mojave.bottle.tar.gz
```
so I guess it's still using the old version.  We can try again tomorrow :)

**Comment by bisakhmondal** [comment]
Yup😅, it seems so. Sorry, my bad :)

**Comment by kartikdutt18** [comment]
I guess its okay to close this now. Thanks a lot everyone!
