### ISSUE TITLE
Port to MLJ.jl

### ISSUE THREAD

**Issue by azev77** [mlpack/mlpack#2388]
Hi and thank you for this package!
Is it possible to port your models to [MLJ](https://github.com/alan-turing-institute/MLJ.jl).jl?

**Comment by rcurtin** [comment]
Hi @azev77, what would need to be done for that?  I agree it would definitely be cool, the only problem is that the interface we can provide to Julia is somewhat limited because it's automatically generated.  The main drawback is that models are "black boxes"; i.e., if I train a logistic regression model in Julia, I can predict new points with it, but I can't look at the coefficients of the model.  This is restrictive but it's a requirement, unfortunately, because we can't provide arbitrary introspection to C++ types to all of the languages we bind to via our automatic binding generation system.

Sorry if the paragraph above is a little dense, but in any case, if we provide the equivalent of a "fit" and "predict" function, would it then be possible to wrap easily into `MLJ`?  (I don't think we could generate that automatically, but a "downstream" package that wraps `mlpack.jl` into `MLJ.jl` could be manually maintained, perhaps.)

**Comment by azev77** [comment]
@rcurtin  porting a package to MLJ usually involves adding one script to the repo.
For example: [ParallelKmeans](https://github.com/PyDataBlog/ParallelKMeans.jl/tree/master/src).jl does this in [mlj_interface](https://github.com/PyDataBlog/ParallelKMeans.jl/blob/master/src/mlj_interface.jl).jl.

**Comment by rcurtin** [comment]
@azev77 thanks for the clarification.  That does seem not too hard, although our automatic binding generation system would make it tricky, so it may be a while until this can be done.  However I will mark this keep-open, because at least for the work I am doing for my company I think it would be useful, and I also think it would be good overall to provide an MLJ interface. :+1:

**Comment by azev77** [comment]
@tlienart @ablaom 
FYI: mlpack can be accessed via [mlpack](https://github.com/mlpack/mlpack.jl).jl, w/ `Pkg.add("mlpack")`. 
Here is a link to the [Julia quickstart](https://www.mlpack.org/doc/mlpack-git/doxygen/julia_quickstart.html).

**Comment by rcurtin** [comment]
Just as a note, some of the work that @NippunSharma is doing for his GSoC project will allow the mlpack Julia bindings to be adaptable into MLJ.jl. :+1:
