### ISSUE TITLE
Feat : Addition of Load() for Audio Files 

### ISSUE THREAD

**Issue by jeffin143** [mlpack/mlpack#2480]
Currently we can load images and major file formats , but may be a good addition for mlpack would be to load audio files, Since we all are of strong belief not to add dependency, A header only library for the support could be : https://github.com/adamstark/AudioFile 

Open to any suggestion or also to know everyone's thought whether to really add the support or would it be really worth adding the support for loading of sound files ?

**Comment by rcurtin** [comment]
So, technically, even just adding a header file is adding a dependency.  It's an easy dependency, since we can just package the header file, but that actually has its own difficulties: we have to keep up to do with the header file, we have to maintain the header file if it starts to be unmaintained, we have to ensure that the header file itself is distributed with mlpack, we have to consider the license, etc., etc.

In this particular case the library you've suggested is actually licensed under the GPL, not BSD or MIT.  Thus I don't think that we can depend on it---if we depend on a GPL'ed library, then anyone who uses mlpack has to adhere to the terms of the GPL.  Although it is possible to set up configuration options so we can build with or without the dependency (and thus change the license terms of mlpack's distribution), that really makes things complex for users and so I'd prefer to avoid it.

So, personally, I don't think that we should add this particular dependency because of those licensing issues.  For other dependencies, I have to ask, is it worthwhile?  I'm not sure how many people are using mlpack to work on audio.  And, if they are, I'm not sure we actually have to integrate directly with another library.  You can just use, e.g., `libsndfile` (https://github.com/erikd/libsndfile) to get the bytes associated with an audio file, then wrap an Armadillo matrix around it with the "advanced constructor" (http://arma.sourceforge.net/docs.html#Mat).

I wonder if maybe the better thing to do on our side, then, is just add some tutorials about how one might load a sound file in mlpack, and then leave it up to the user to install and configure libsndfile (or whatever library).  What do you think?

**Comment by jeffin143** [comment]
> I wonder if maybe the better thing to do on our side, then, is just add some tutorials about how one might load a sound file in mlpack, and then leave it up to the user to install and configure libsndfile (or whatever library). What do you think?

Sound good :)

Thanks for the write up

I will go ahead and close it
