### ISSUE TITLE
Equations do not render.

### ISSUE THREAD

**Issue by danishbelal** [mlpack/mlpack#2485]
#### Problem location

https://www.mlpack.org/doc/mlpack-git/doxygen/lrtutorial.html

#### Description of problem

MathJax JS Library is not loaded, so that the equations do not render.  This is probably affecting multiple pages, however I checked only said page.

**Comment by rcurtin** [comment]
Thanks for the report.  I think actually this is something slightly different.  It looks like some of the equations---which should be compiled as `.png`s---aren't actually being created due to Doxygen not successfully compiling them as LaTeX formulas.  I found a bug in the Doxygen documentation (#2488) and after fixing that I'm rebuilding the 3.2.2 documentation now.  Hopefully, when that's done, everything will work (I'll provide another update then). :+1:

If it does work, the mlpack-git documentation will automatically rebuild and be fixed once #2488 is merged.

**Comment by rcurtin** [comment]
Ok, this seems to render fine now: https://www.mlpack.org/doc/mlpack-3.3.2/doxygen/lrtutorial.html

It may still be better to switch to using MathJax at some point, but this is at least adequate in my opinion.

Unless you find any other errors, I'll go ahead and close this once #2488 is merged and the mlpack-git documentation rebuilds. :+1:

**Comment by rcurtin** [comment]
Thanks @birm, forgot to close this one. :)
