### ISSUE TITLE
How to use concat layer? Any example

### ISSUE THREAD

**Issue by brightprogrammer** [mlpack/mlpack#2547]
Can you please show an example or give hint on how to use Concat. By reading the source I came to following conclusions :
1-> Concat joins two layers in the FFN
2-> I have to predefine the layers I want to concatenate instead of creating them on the run in the add function of `mlpack::ann::FFN<>` 
3-> There is an Add function in Concat class that I have to use to concatenate the layers. 

Now there are few things that I don't understand :
1-> What is the use of `model` and `run` boolean variables? 
2-> I understand what is the use of `axis`variable but I don't understand how to use it? ( 0=col, 1=row?) 
3->Am I correct about any point above?

**Comment by mrityunjay-tripathi** [comment]
@brightprogrammer : Maybe [this](https://github.com/mlpack/mlpack/blob/master/src/mlpack/tests/ann_layer_test.cpp#L1393-L1513) is helpful?

**Comment by brightprogrammer** [comment]
@mrityunjay-tripathi sure that helped a lot but i still don't understand what's the use of `model` and `run` booleans in the following code :
```
Concat(arma::Row<size_t>& inputSize, const size_t axis, const bool model = false, const bool run = true);
```

**Comment by zoq** [comment]
The `model` parameter specifies if the `Concat` layer should expose the wrapped layers via the `Model` function, which s used to initialize the weights or set specific states for layers. As an example once we added the layers to the `FFN` class, we will go over each layer and initialize the weights, since there could be a layers that is not directly added to the FFN class itself (via `.Add(...)`), we have to provide a method to the FFN class to see those layers.

In some cases, a layer could be wrapped multiple times, image you use the `Concat` layer to branch the network (the inception network is one example). In this case a layer could be part of multiple `Concat` layers, but you only want to initalize the layer once, in which case you can tell the `Concat` layer to not expose the layer.

The `run` parameter is similar, it wil skip the call to the `Forward` function of the wrapped layer if set to true.

I hope anything I said here makes sense, let me know if I should clarify anything.

**Comment by brightprogrammer** [comment]
Ok, I understand a few things now... Let's say that I want to implement the following network : 
![image](https://user-images.githubusercontent.com/37365905/89029863-ec151000-d34c-11ea-89ad-076ae8d6f97c.png)

How will the code look like?

**Comment by brightprogrammer** [comment]
What I am not understanding now is do I have write the forward pass sequence explicitly or is there some way to do it? Do I have to write my own train function that will pass the output from previous layer to the 4 layers in next layer (in the above picture)

**Comment by brightprogrammer** [comment]
Really? NO REPLY FOR 4 DAYS!! A good library need better support! You can make all fast and amazing libraries you want, if you are unable to give support to users then it's useless!! Idk whether you guys are ignoring or you just forgot how to use your own library... Whatever's the reason... This gesture will not be appreciated by anyone!

**Comment by zoq** [comment]
@brightprogrammer we don't ignore anyone, this is an open-source project; we work on the project in our free time, so providing an answer can take some time. A simple ping here on the issue or any other channel would have been more helpful than what you wrote above.

Anyway, if you search for "inception" you get https://github.com/mlpack/mlpack/pull/1950 as a result, the second comment https://github.com/mlpack/mlpack/pull/1950#issuecomment-511765865 provides the answer to your question, the PR has another example about how to use the `Concat` layer to implement what you asked for.

**Comment by rcurtin** [comment]
> This gesture will not be appreciated by anyone!

I assume by "this gesture" you mean your post?

None of us get paid to work on this library---it's open-source.  Pretty much all of us have jobs or other work that take the majority of our time, and then we work on mlpack in our spare time, for fun.

Please be sure to follow the [code of conduct](https://github.com/mlpack/mlpack/blob/master/CODE_OF_CONDUCT.md) in your responses, otherwise we risk a toxic community where nobody is having any fun at all.

I can totally understand that you're frustrated that you haven't received a response, but please don't take out your frustration on a bunch of volunteers.  Try to work with the responses you've already gotten to figure out what to do.  We can try to help you out (and @zoq and @mrityunjay-tripathi did!), but it's up to you to really solve the problem that you're trying to solve.  Try some things and see if it works!  If you find bugs, maybe we can help with those.

**Comment by rcurtin** [comment]
For what it's worth, we are in the process of overhauling our examples and documentation, which should hopefully make things a bit clearer in the future.  See the https://github.com/mlpack/examples repository; note, it's still a work in progress. :+1:

**Comment by brightprogrammer** [comment]
Thanks for replying after so long time... You guys have a job so must understand the how important time is, better than me! I can really try to move but I need a vector! The code is not documented that well... You just get this as documentation :
`this is the definition of Linear class` and then `an odinary feed forward pass function`... No documentation on how anything works... I get that you guys have jobs but 4 days is a lot of time to reply!... Reply anything..!

**Comment by zoq** [comment]
@brightprogrammer have you seen https://github.com/mlpack/mlpack/pull/1950#issuecomment-511765865 (the comment I posted above), the comment includes the answer to what you asked "What will the code look like?", as well as a test case.

Also regarding "Do I have to write my own train function that will pass the output from previous layer to the 4 layers in next layer (in the above picture)", not at all, that is handled by the `FFN` class. https://www.mlpack.org/doc/mlpack-3.3.2/doxygen/anntutorial.html should be helpful as well to get a general overview.
