### ISSUE TITLE
Implement the centroid finding part of the `KMeans` as a separate class and pass it as a template parameter

### ISSUE THREAD

**Issue by DiscreteLogarithm** [mlpack/mlpack#2592]
### What is the desired addition or change?

The algorithm for finding the centroids of clusters should be customizable similar to the way metric is.

### What is the motivation for this feature?

This will allow implementation of weighted k-means algorithm as well algorithms such as k-medians.

### If applicable, describe how this feature would be implemented.

Similar to the way metric is implemented, by implementing it as a separate class and passing the type as template parameter to the `KMeans`. The constructor of `KMeans` could default construct it or get an instance if needed. The instance is passed to the Lloyd step classes as needed.

**Comment by rcurtin** [comment]
@DiscreteLogarithm this would definitely be a nice addition!  See also #2582.

For an API, it *might* be possible to simply add another overload of `Cluster()` to `KMeans<>` that takes weights, but I am not sure if that will cause ambiguity (there are already a few overloads there).  If it is ambiguous, then I think a `WeightedKMeans<>` class is just fine.

We implement each of the strategies for k-means via the use of the `LloydStepType` template parameter, for which the default is `NaiveKMeans`.  We could use the same strategy for weighted variants of each of these rules.  I think, it might not look like it, but it should actually be easy to adapt the rules for each strategy.  If anyone wants to give this a shot, we could start with the `NaiveKMeans` (simple Lloyd) strategy, and then start to add more advanced strategies like Elkan, Hamerly, Pelleg-Moore, and dual-tree.  I'm happy to help describe the modifications to the algorithms that would be necessary.

Lastly, we'd want to update `kmeans_main.cpp` to add a parameter `weights` that would allow the user to specify weights for their points, and if the weights are specified, we'd use the `WeightedKMeans<>` class.

Thank you for suggesting this @DiscreteLogarithm!  I've marked it as a "good first issue" because if someone has a decent knowledge of k-means, C++, and basic machine learning algorithms, I think this would be a great way to dive into the library. :+1:

**Comment by DiscreteLogarithm** [comment]
Thanks for your reply and sorry about my late answer. I've already modified naive and dual tree algorithms for the weighted case for my own use but unfortunately not in a general and elegant manner because I'm in a rush to meet a deadline but hopefully I will have time for this in 3 weeks and will implement it if still not done.

By the way I have two more observations about the KMeans code. Consider this part of the `kmeans_impl.hpp`:
```
    // We have two centroid matrices.  We don't want to copy anything, so,
    // depending on the iteration number, we use a different centroid matrix...
    if (iteration % 2 == 0)
      cNorm = lloydStep.Iterate(centroids, centroidsOther, counts);
    else
      cNorm = lloydStep.Iterate(centroidsOther, centroids, counts);

    // If we are not allowing empty clusters, then check that all of our
    // clusters have points.
    for (size_t i = 0; i < counts.n_elem; i++)
    {
      if (counts[i] == 0)
      {
        Log::Info << "Cluster " << i << " is empty.\n";
        if (iteration % 2 == 0)
          emptyClusterAction.EmptyCluster(data, i, centroids, centroidsOther,
              counts, metric, iteration);
        else
          emptyClusterAction.EmptyCluster(data, i, centroidsOther, centroids,
              counts, metric, iteration);
      }
    }
```
On even iterations `lloydStep.Iterate` reads previous centroids from `centroids` and writes new centroids `centroidsOther`. Now `emptyClusterAction.EmptyCluster` does the same ignoring the new centroids computed by `lloydStep.Iterate`. Isn't this a bug? On even iterations `centroids` holds the previous iteration centroids, which the `emptyClusterAction.EmptyCluster` does not need and should not use, therefore why pass it?

Second, `kmeans::SampleInitialization` uses a random index array to select initial centroids from the data points. There's a possibility that a data point is selected more than once as a centroid. This is fine because all but one of such points form empty clusters but dealing with empty clusters could be time consuming depending on the empty cluster policy and problem size. In large problems when ratio of clusters to data points is not small, a random sampling scheme without replacement improves runtime considerably. This could be implemented easily with the help of one of these functions: `std::random_shuffle` (until C++17), `std::shuffle` (since C++11), `std::sample` (since C++17), `arma::shuffle`, or `arma::randperm`.

PS: @rcurtin Your dual-tree algorithm is great and very fast. I'm a fan.

**Comment by Aakash-kaushik** [comment]
Is anyone working on this ?

**Comment by zoq** [comment]
@Aakash-kaushik please feel free to work on this.

**Comment by Aakash-kaushik** [comment]
So i am taking up the implementation of this.

**Comment by rcurtin** [comment]
@Aakash-kaushik didn't @DiscreteLogarithm say above that he wanted to work on this in three weeks?  Maybe finding a different issue would be a better idea.

@DiscreteLogarithm I'll answer your comment more completely soon. :+1:

**Comment by Aakash-kaushik** [comment]
@rcurtin I missed that part. Will take up something else.

**Comment by DiscreteLogarithm** [comment]
@rcurtin Thanks.

Personally I don't mind others working on this.

**Comment by rcurtin** [comment]
Hey @DiscreteLogarithm, sorry it took me a little while to get to these questions:

> On even iterations lloydStep.Iterate reads previous centroids from centroids and writes new centroids to centroidsOther. Now emptyClusterAction.EmptyCluster does the same ignoring the new centroids computed by lloydStep.Iterate. Isn't this a bug? On even iterations centroids holds the previous iteration centroids, which the emptyClusterAction.EmptyCluster does not need and should not use, therefore why pass it?

So, the `EmptyCluster` policy is actually looking to receive the centroids from the previous iteration.  This comment is from `MaxVarianceNewCluster`.

```
  /**
   * Take the point furthest from the centroid of the cluster with maximum
   * variance to be a new cluster.
   *
   * @tparam MatType Type of data (arma::mat or arma::spmat).
   * @param data Dataset on which clustering is being performed.
   * @param emptyCluster Index of cluster which is empty.
   * @param oldCentroids Centroids of each cluster (one per column) at the start
   *      of the iteration.
   * @param newCentroids Centroids of each cluster (one per column) at the end
   *      of the iteration.
   * @param clusterCounts Number of points in each cluster.
   * @param metric The Metric to use.
   * @param iteration Number of iteration.
   */
```

Anyway, when I designed that policy, I thought it could be useful to have both `oldCentroids` and `newCentroids`; for instance, you might want to choose to revert an empty centroid to its location in the previous iteration, or something like this.

> Second, kmeans::SampleInitialization uses a random index array to select initial centroids from the data points. There's a possibility that a data point is selected more than once as a centroid. This is fine because all but one of such points form empty clusters but dealing with empty clusters could be time consuming depending on the empty cluster policy and problem size. In large problems when ratio of clusters to data points is not small, a random sampling scheme without replacement improves runtime considerably. This could be implemented easily with the help of one of these functions: std::random_shuffle (until C++17), std::shuffle (since C++11), std::sample (since C++17), arma::shuffle, or arma::randperm.

Agreed, that would be great!  Actually `RandomPartition` has code that is just like a strategy for sampling randomly without replacement from Armadillo: `arma::shuffle(arma::linspace(...))` (but that code actually abuses `linspace` on integer elements).  I'm not sure how that would perform compared to the other alternatives you suggested; I think in most use cases, `k` is small, so the best algorithm may not be to instantiate an entire array of length `N` and then shuffle it, taking only `k` elements from it.

If you (or anyone) wanted to implement that change, I think it would be a nice improvement. :+1:

> PS: @rcurtin Your dual-tree algorithm is great and very fast. I'm a fan.

Thanks!  The drawback is that the utility is somewhat limited: it requires both large k and large N (and low dimensionality of the data) in order to be effective.  If those things are not true, then the Elkan/Hamerly/Pelleg-Moore algorithms will dominate.  However, when they are true, the overhead of maintaining two trees and doing all kinds of complicated things to them can pay off. :+1:

**Comment by DiscreteLogarithm** [comment]
> So, the `EmptyCluster` policy is actually looking to receive the centroids from the previous iteration.

That makes sense. Some policies may make use of the old centroids. `MaxVarianceNewCluster` uses old centroids for computation of variances and assignments. It might make little difference but is it intentional?

> I'm not sure how that would perform compared to the other alternatives you suggested; I think in most use cases, k is small, so the best algorithm may not be to instantiate an entire array of length N and then shuffle it, taking only k elements from it.

You're right. It is not necessary to shuffle the entire array. Iterating the Fisher-Yates shuffle `k` times produces the sample. It's still necessary to instantiate an array of length `N` but it only needs `k` random numbers and swaps. There are also reservoir sampling algorithms that don't require instantiating an array of size `N` but require more random numbers.

> If you (or anyone) wanted to implement that change, I think it would be a nice improvement.

Yes I will implement it.

> The drawback is that the utility is somewhat limited: it requires both large k and large N (and low dimensionality of the data) in order to be effective.

We use it to partition an image into Voronoi cells of (approximately) equal intensity. This helps finding the optimal transport map between two images in a multi-scale way. At fine-detail levels there are hundreds of thousands of pixels and tens of thousands of clusters and only 2 dimensions. These optimal transport maps are then used to design custom optical elements.

**Comment by rcurtin** [comment]
> That makes sense. Some policies may make use of the old centroids. MaxVarianceNewCluster uses old centroids for computation of variances and assignments. It might make little difference but is it intentional?

Ah, sorry, it has been ten years since I wrote this so I had to refresh my memory a bit. :)  In this situation, yes, the old centroids are used to compute the cluster in the previous iteration that had the maximum variance, and then we pull the point that's farthest from the maximum variance centroid for the empty cluster out of that centroids.  I suppose it could work either with the new centroids or the old centroids, but either way is effective.  There's not any particular theoretical results on the technique that mean it has to be done in a particular way; it's just a heuristic.

> You're right. It is not necessary to shuffle the entire array. Iterating the Fisher-Yates shuffle k times produces the sample. It's still necessary to instantiate an array of length N but it only needs k random numbers and swaps. There are also reservoir sampling algorithms that don't require instantiating an array of size N but require more random numbers.

Yes, any of these would be great; I'm not sure if Armadillo implements any of these techniques though.  Anyway, if you want to give it a shot and see what happens, I think it would be great. :+1:

> We use it to partition an image into Voronoi cells of (approximately) equal intensity. This helps finding the optimal transport map between two images in a multi-scale way. At fine-detail levels there are hundreds of thousands of pixels and tens of thousands of clusters and only 2 dimensions. These optimal transport maps are then used to design custom optical elements.

Awesome!  I am really glad that it is useful.  The "typical" textbook use-case of k-means generally has rather small k, but, like you just pointed out, that's not always the case in practice.

**Comment by Aakash-kaushik** [comment]
Keep open
