### ISSUE TITLE
Compatibility with the new Apple M1 architecture

### ISSUE THREAD

**Issue by laszlzso** [mlpack/mlpack#2791]
Was wondering to what extent mlpack supports the new M1 architecture of Apple machines (or the other way around) released in November 2020. I presume that everything should work just fine on M1 (perhaps via the Rosetta 2 compatibility layer?), however, note that the library is built on top of a few dependencies (especially Armadillo and Boost) and comes with a couple of bindings (Python/R/Julia/Go) - so it may make sense to raise the question/conduct some tests using M1.

If someone already employs an M1-powered machine for mlpack development, please, let us know whether you encountered any basic usage/performance/something else related issues (with either the dependencies/building process or the actual applications/bindings).

**Comment by rcurtin** [comment]
I don't have an M1 machine, but at least from the mlpack level I would expect everything to work fine.  The only "tricky" dependency might be OpenBLAS since it's often tuned specifically to architectures, but it looks like it at least works fine based on this issue: https://github.com/xianyi/OpenBLAS/issues/2814
