### ISSUE TITLE
[Question] C bindings to mlpack

### ISSUE THREAD

**Issue by ananis25** [mlpack/mlpack#2812]
Hi 
I wanted to use the mlpack library from a C runtime (Dlang specifically, which has very convenient interop with C). The C++ library code doesn't look to have C linkage, but looking at the PR history, Go and Julia bindings apparently auto generate C header files which can then be used by tools like `cgo` at runtime to use mlpack methods. 

Is it possible to use those C header files along with a prebuilt installation of mlpack available from the OS package manager? Or do I always need to compile the go bindings from source to get a binary compatible with those headers?

(Apologies if the question is silly. I tried to build the go bindings but running into boost version errors there, so I wanted to check first.)

**Comment by rcurtin** [comment]
Hey @ananis25, I had been thinking about this exact issue some months ago.  You are exactly right that both the Go and Julia bindings first generate C bindings, then turn around and bind those C bindings into Go or Julia respectively.

I believe that it is possible to do exactly what you are hoping to do, but a little bit of fighting might be needed to make it work.  So here are two possible directions:

*1. Use go infrastructure to build the mlpack bindings*.  The first couple steps of the [Go quickstart tutorial](https://www.mlpack.org/doc/mlpack-git/doxygen/go_quickstart.html) show how to download and build the mlpack Go bindings:

```
go get -u -d mlpack.org/v1/mlpack
cd ${GOPATH}/src/mlpack.org/v1/mlpack
make install
```

That `make install` step effectively builds all of mlpack (currently version 3.4.2) and I think that during the process it will build shared objects for each of those generated C bindings.

*2. Hand-compile Julia bindings and use those directly.*

The Julia bindings only halfheartedly check for a working Julia version.  In fact, it's pretty easy to trick CMake into building the Julia bindings even if you don't have Julia installed.  Just do this in your CMake build directory:

```
echo "#!/bin/bash" > julia
echo "echo \"Fake Julia version 1.3.0\"" >> julia
chmod +x julia
```

```
cmake -DBUILD_JULIA_BINDINGS=ON -DJULIA_EXECUTABLE="${PWD}/julia" ..
```

Then, you can do `make julia`, and you'll end up with those C bindings in `build/src/mlpack/bindings/julia/`.  The `.h` files will be in `mlpack/build/` (under that path), and the `.so` files will be in `src/`.

I think that should be sufficient.  I know it's a bit tedious to make that work.  I'd like to eventually think about how we can actually formally provide the C bindings (instead of building them twice, one for Go and one for Julia), but I'm not sure what the best way to do that yet is.

**Comment by ananis25** [comment]
Thank you @rcurtin , I used to go infrastructure to build the bindings which was easy enough.

**Comment by rcurtin** [comment]
@ananis25 awesome that you got it worked out! :+1:  Hopefully someday we will be able to provide C bindings in a more robust way.
