### ISSUE TITLE
Building python bindings from source

### ISSUE THREAD

**Issue by onikolskyy** [mlpack/mlpack#2842]
#### Problem location

https://www.mlpack.org/doc/mlpack-git/doxygen/build.html

#### Description of problem
The Documentation says, that cmake will preconfigure python bindings by default. (`BUILD_PYTHON_BINDINGS=(ON/OFF): compile the bindings for Python, if the necessary Python libraries are available (default ON except on Windows)`).
However on ubuntu 18.04 `BUILD_PYTHON_BINDINGS` needs to be set to `ON` for a proper build of Python bindings

**Comment by rcurtin** [comment]
Thanks for pointing that out!  You're right.  We recently disabled the bindings (since most people probably install Python bindings via pip or conda), but forgot to update the documentation.  Would you be interested in opening a PR to fix the docs?  If not that's perfectly okay---I'm happy to do it. :+1:

**Comment by onikolskyy** [comment]
Cool, I would like to -- but rather at the end of the week, after my exams.

**Comment by onikolskyy** [comment]
https://github.com/mlpack/mlpack/pull/2853#issue-582088792

**Comment by rcurtin** [comment]
Thanks @onikolskyy!
