### ISSUE TITLE
Modification methods for LARS/LASSO/ElasticNet?

### ISSUE THREAD

**Issue by xlindo** [mlpack/mlpack#2857]
When I use LARS, I found NO set/get methods for hyper-parameters, such as lambda1, lambda2. I am not sure if it should be so.

I want to use the default constructor of LARS, and set the parameters later. This means I need a set of setter and getter methods, like

```cpp
mlpack::regressions::LARS *lars = new mlpack::regressions::LARS;
lars.set_lambda1( ... );
double lambda1_ = lars.get_lambda1();
```

Can anyone tell me how to accomplish this without a modification on source code?

Ref:
[https://www.mlpack.org/doc/stable/doxygen/lars_8hpp_source.html](https://www.mlpack.org/doc/stable/doxygen/lars_8hpp_source.html)

**Comment by rcurtin** [comment]
Hey @xlindo, thanks for the report.  You're right that there are not `Lambda1()` or `Lambda2()` members.  I opened a PR to fix that: #2861.

At the same time, it's very cheap to construct a LARS object without training.  So if you want to use the current version of mlpack that you have without updating to include #2861, you can just do something like this:

```
using namespace mlpack::regression;

double lambda1 = 0.5;
double lambda2 = 1.0;
LARS l(false, lambda1, lambda2);

// Now we want to modify lambda1 or lambda2... let's just reconstruct the object:
l = LARS(false, newLambda1, newLambda2);
```

Since LARS doesn't support incremental training, there's no need to avoid calling the constructor again before training.

I hope this helps---let me know if there's anything else I can clarify. :+1:
