### ISSUE TITLE
Some questions about Hoeffding Tree Example

### ISSUE THREAD

**Issue by DylanWangWQF** [mlpack/mlpack#2950]
Hi, everyone! I have some questions about the Hoeffding Tree example.

1. When will the training process end?  (out of the expected memory?)
```
//! Train on one point.
Train(const VecType& point, const size_t label){
if (splitDimension == size_t(-1))
  {
    ..........
    // Check for a split, if we should.
    if (numSamples % checkInterval == 0)
    {
      const size_t numChildren = SplitCheck();
      if (numChildren > 0)
      {
        // We need to add a bunch of children.
        // Delete children, if we have them.
        children.clear();
        CreateChildren();
      }
    }
  }
  else
  {
    // Already split.  Pass the training point to the relevant child.
    size_t direction = CalculateDirection(point);
    children[direction]->Train(point, label);
  }
}
```
2. Does the `clear()` work here? (Since it's class object in the vector)
```
//! If the split has occurred, these are the children.
std::vector<HoeffdingTree*> children;
children.push_back(new HoeffdingTree(*datasetInfo, numClasses, successProbability, maxSamples, checkInterval, minSamples, CategoricalSplitType<FitnessFunction>(0, numClasses), numericSplits[0], dimensionMappings, false));
children.clear();

//! Information for splitting of categorical features (used before split).
std::vector<CategoricalSplitType<FitnessFunction>> categoricalSplits;
categoricalSplits.push_back(CategoricalSplitType<FitnessFunction>(datasetInfo.NumMappings(i), numClasses, categoricalSplitIn));
// Eliminate now-unnecessary split information.
  numericSplits.clear();
  categoricalSplits.clear();
```

3. I want to modify this part of the codes (only work on categorical features). During the training, we will directly transfer the counting matrix of each feature (dimension) to the training procedure instead of each data point. (Bypass the classification of each data point).
Then I have some questions in the function `CreateChiledren()`, we will push each child into the `vector<> chileren`, `children.push_back(new HoeffdingTree(........));`.
Then, when we create this child, we will push all of the features into `vector<> categoricalSplits`.
```
categoricalSplits.push_back(CategoricalSplitType<FitnessFunction>(
            datasetInfo.NumMappings(i), numClasses, categoricalSplitIn));
```

Here, I have a question. If some features have been used as split features, then in above operation, we will still push all of the features into `categoricalSplits`?

Additionally, why do we put `categoricalSplits[0]` into all of the new children?  `categoricalSplits[0]` just stores the split information of one feature (dimension) ?
```
// Pass both splits that we already have.
children.push_back(new HoeffdingTree(*datasetInfo, numClasses,
          successProbability, maxSamples, checkInterval, minSamples,
          categoricalSplits[0], numericSplits[0], dimensionMappings, false));
```

**Comment by DylanWangWQF** [comment]
In `CreateChiledren()`, we will push each child into the `vector<> chileren`, `children.push_back(new HoeffdingTree(........));`.
Then, when we create this child, we will push all of the features into `vector<> categoricalSplits`.
```
categoricalSplits.push_back(CategoricalSplitType<FitnessFunction>(
            datasetInfo.NumMappings(i), numClasses, categoricalSplitIn));
```

Here, I have a question. If some features have been used as split features, then in above operation, we will still push all of the features into `categoricalSplits`?

Additionally, why do we put `categoricalSplits[0]` into all of the new children?
```
// Pass both splits that we already have.
children.push_back(new HoeffdingTree(*datasetInfo, numClasses,
          successProbability, maxSamples, checkInterval, minSamples,
          categoricalSplits[0], numericSplits[0], dimensionMappings, false));
```

**Comment by DylanWangWQF** [comment]
Hi, @rcurtin  Many thanks for your reply and help! 
> > 1. When will the training process end? (out of the expected memory?)
> 
> If you call `Train()`, it will only take one pass over the points you give it. So if you want the Hoeffding tree to be trained with, e.g., 10 passes over your data, just do this:
> 
> ```
> for (size_t i = 0; i < 10; ++i)
>   tree.Train(data, labels);
> ```
If all of the features are split and the hoeffding tree is completed, will the remaining data continue to be scanned?

> > 2. Does the clear() work here? (Since it's class object in the vector)
> 
> Do you mean that you want to reset the tree? Just call the constructor again---that should work.
>
Sry, my question here was not clear.  `clear()` will clear the split information of the current split node `(vector<HoeffdingCategoricalSplit> categoricalSplits)` ?
```
numericSplits.clear();
categoricalSplits.clear();
```
 Thanks! I update the third question.

**Comment by rcurtin** [comment]
> If all of the features are split and the hoeffding tree is completed, will the remaining data continue to be scanned?

The Hoeffding tree is never "complete"---so if, e.g., you pass 1M points, but the last split made according to the Hoeffding bound is done after seeing the 10th point, the training procedure will still scan the remaining 999,990 points.  That's just how the algorithm works---as you pass it more points, it checks to see if they can be split.

> Sry, my question here was not clear. clear() will clear the split information of the current split node (vector<HoeffdingCategoricalSplit> categoricalSplits) ?

I am not sure that it is a good idea to do this, but if you want to reset the cached split information for a node (so that it looks like it has never seen any points during training), then yes, you could clear the `numericSplits` and `categoricalSplits` vectors... but you will also need to reinitialize them to the correct dimensionality:

```
// Generate dimension mappings and create split objects.
  for (size_t i = 0; i < datasetInfo.Dimensionality(); ++i)
  {
    if (datasetInfo.Type(i) == data::Datatype::categorical)
    {
      categoricalSplits.push_back(CategoricalSplitType<FitnessFunction>(
          datasetInfo.NumMappings(i), numClasses));
      (*dimensionMappings)[i] = std::make_pair(data::Datatype::categorical,
          categoricalSplits.size() - 1);
    }
    else
    {
      numericSplits.push_back(NumericSplitType<FitnessFunction>(numClasses));
      (*dimensionMappings)[i] = std::make_pair(data::Datatype::numeric,
          numericSplits.size() - 1);
    }
  }
```

I adapted that code from the HoeffdingTree constructor.  You'll have to adapt it further if you want to use it from outside the class.  Honestly, if you wanted to add this as a function to the `HoeffdingTree` class, I think it might be a nice addition, so if you wanted to open a PR we could merge it in.

> Here, I have a question. If some features have been used as split features, then in above operation, we will still push all of the features into categoricalSplits?

I believe what you are suggesting here is that if we split once on a categorical dimension, we cannot split on it again.  But this is only true if our categorical splitting strategy on a given dimension splits into `C` children, where `C` is the number of categories in that dimension.  That is indeed the strategy used by the default categorical split type (`HoeffdingCategoricalSplit`), but it is not necessary to split this way: in fact, the user can pass a categorical split type that does a one-vs.-all split; e.g., there would only be two children resulting from that kind of split.  If the categorical split is one-vs.-all, for instance, there is the possibility that there can be another split in that categorical dimension.  Therefore, we still push all features into all children.

Now, there is an optimization possibility here---it would be possible to add some constant `bool` to every categorical split type indicating whether further splits can be made in that dimension, and then take some different behavior if no more splits can be made.  However, that idea is not currently implemented. :)

> Additionally, why do we put categoricalSplits[0] into all of the new children? categoricalSplits[0] just stores the split information of one feature (dimension) ?

Yes, actually this is to provide flexibility for split types.  The idea is just that `categoricalSplits[0]` might hold some metadata about the splitting strategy that the user gave.  Thus, each split type has a constructor that takes in another split to extract any metadata.  You can see that for `HoeffdingCategoricalSplit`, there is no metadata to extract, and thus the parameter is unused:

```
template<typename FitnessFunction>
HoeffdingCategoricalSplit<FitnessFunction>::HoeffdingCategoricalSplit(
    const size_t numCategories,
    const size_t numClasses,
    const HoeffdingCategoricalSplit& /* other */) :
    sufficientStatistics(numClasses, numCategories)
{
  sufficientStatistics.zeros();
}
```

I hope this is helpful!  If you want to contribute some improvements to the `HoeffdingTree` class, it would be great. :smile:

**Comment by DylanWangWQF** [comment]
Hi, @rcurtin This is really helpful! Many thanks for your help!
Currently, I'm trying to modify the part of Hoeffding Tree Training to complete my experiment as soon as possible. When I finish this part, I'm glad to contribute some improvements if these  improvements did work in  this project.

More details: I have to implement the training process in a non-recursive way. That is, I store and update all of the current leaf nodes in a structure (e.g., List<HoeffdingTree*>).
