### ISSUE TITLE
change matrix constructors to use arma::fill:none

### ISSUE THREAD

**Issue by conradsnicta** [mlpack/mlpack#2958]
In Armadillo 10.5 the default behaviour of [Mat](http://arma.sourceforge.net/docs.html#Mat), Row, Col, and Cube constructors has been changed compared to earlier versions of Armadillo. The constructors now set all elements to zero by default. In other words, a declaration like `arma::mat X(4,5)` is now equivalent to `arma::mat X(4,5,arma::fill::zeros)`.

This was done for consistency with the SpMat class, and to avoid user confusion.  Many users were getting tripped up that a matrix declaration (without `arma::fill`) can end up with garbage values (like NaN), even though this was explicitly noted in the documentation.

In certain cases the default initialisation to zero may be suboptimal. To avoid zeroing elements at construction, the "arma::fill::none" fill option can be used.  This option should work with older versions of Armadillo that support `arma::fill`.

Example case.  In the file `methods/ann/layer/lp_pooling.hpp` we have this code:

    unpooledError = arma::Mat<eT>(InputArea.n_rows, InputArea.n_cols);
    unpooledError.fill(error(rowidx, colidx) / InputArea.n_elem);

Since the `unpooledError` matrix is immediately overwritten after construction, it would be more efficient to avoid zeroing at construction:

    unpooledError = arma::Mat<eT>(InputArea.n_rows, InputArea.n_cols, arma::fill::none);
    unpooledError.fill(error(rowidx, colidx) / InputArea.n_elem);

**Comment by rcurtin** [comment]
@conradsnicta was there any reason to close this one? This seems like a relatively straightforward (albeit tedious) change. It looks like `fill::none` has been around for a long time, so there shouldn't be any reverse compatibility issues.

For anyone interested in contributing, the pattern here is that we need to change, e.g., `arma::mat(r, c)` to `arma::mat(r, c, arma::fill::none)`. It may be a bit more complicated than that, because sometimes we use different types like `arma::fmat` or `arma::Mat<size_t>` or `arma::vec`, and also sometimes the types are template parameters that are intended to be matrices, like `MatType`.
