### ISSUE TITLE
Class Probabilities for Softmax_Regression in R

### ISSUE THREAD

**Issue by nkanrar** [mlpack/mlpack#2997]
Hi! Thanks for this great package. I am using mlpack in R to do multiclass classification, specifically with the softmax_regression function. I was wondering if there is any way to obtain the probabilities for belonging to each class for the test data? The documentation shows that we can get the predicted classes for test data, but I was wondering if we could essentially get the matrix of probabilities for each class?

Thanks!

**Comment by rcurtin** [comment]
Hey there @nkanrar, you're right that the softmax regression binding does not make this information available, and that is unfortunate!

I've opened a PR to fix the issue in #3001.

However, it will not immediately solve your problem once merged... you will either have to wait until the next stable release of mlpack makes it to CRAN, or manually install a new version.  But, it may be some months before the next stable release of mlpack, as we are in the process of a pretty intensive refactoring to remove some of our dependencies (as a bonus, that should also help the long compilation times that are present with mlpack!).  I am not very knowledgeable about R, but I *think* that you can download a prebuilt package and install it with `install.packages()` by specifying the name of the file, instead of the name of the package.  However, I still need to find the link to the right file... I believe that our CI infrastructure will build it in the PR (or after the PR is merged), so I may not be able to provide a link until then.

Anyway, thank you for reporting the issue!  I hope that at least one of the options here is able to let you proceed with what you are trying to do. :)

**Comment by rcurtin** [comment]
With #3001 merged, this should be fixed now and this option will be available in the next mlpack release. :+1:
