### ISSUE TITLE
bump minimum version of Armadillo to 9.800

### ISSUE THREAD

**Issue by conradsnicta** [mlpack/mlpack#3033]
Given the huge amount of code refactoring for mlpack 4 (eg. removal of Boost) and introduction of new functionality, it may take quite some time before mlpack 4 is ready and polished enough for release.  I suspect it may be well into next year (2022), probably around the release of Ubuntu 22.04 LTS.

Currently mlpack requires the minimum version of Armadillo to be 8.400, which results in a lot of useful functionality in newer versions of Armadillo to be ignored by mlpack.  This is already causing problems (eg. https://github.com/mlpack/ensmallen/pull/315).

I propose that the minimum version of Armadillo is bumped from 8.400 to 9.800.  Armadillo 9.800 is available in Ubuntu 20.04 LTS.  The list of newer functionality compared to 8.400 is quite large (http://arma.sourceforge.net/docs.html#api_additions) and can be helpful to simplify the mlpack codebase (eg. removal of any backports and/or workarounds), allow mlpack to provide enhanced functionality, as well as allow speedups (eg. use of the `solve_opts::likely_sympd` option to [solve()](http://arma.sourceforge.net/docs.html#solve)).

CC: @rcurtin @zoq @shrit

**Comment by shrit** [comment]
I would not mind bumping the minimum version for armadillo, for two reasons, first, it can be used as a header-only library if the user does not have root access on their machine, or they can download it and build it locally, and second, I do not think there is a difference between armadillo versions for the minimum requirement of OpenBLAS.
Finally, I do not know if it is possible for users to find armadillo 8.400 in nature apart from Ubuntu 16.04 repository :smiley:

**Comment by zoq** [comment]
Agreed, if we bump the version on the ensmallen side, that basically means we automatically have to bump it for mlpack as well.

**Comment by rcurtin** [comment]
I think this issue comes up from time to time with slightly different but generally similar responses.  Maybe it makes sense to codify our process here for how far back we try to support and then write it down somewhere so we know when we can and can't update things?  I *think* I typically say something like "I'd like to support recent Ubuntu LTS and RHEL", but I'm not really sure if 'recent' Ubuntu LTS means 18.04 or 20.04 now, or if recent RHEL means 7 or 8.  18.04 only has 8.400 which I think is why we chose it, but now 2018 is somehow three years behind us...

Any thoughts?  And "let's not make a process for this" is totally a reasonable thought!  I don't have any problem if the strategy we adopt is what we've been doing, which I think is essentially "upgrade when @conradsnicta pokes us about it after some discussion" :smile:

I think we'll have to bump the EPEL8 package if we do 9.800 (but that's not hard, I am a maintainer there), and we'd lose RHEL7, but I mean realistically I suppose a RHEL7 user could just depend on the autodownloader since our use of Armadillo can be header-only...

**Comment by shrit** [comment]
I think we can create a good set of tutorials to describe in detail how to install the mlpack, whether if it is on RHEL7, or on the newest distros. Since we are moving toward a header-only quasi-dependency-free library, we can be sure that we can build it anywhere, even on very old systems as long as they have C++11.
Therefore, this will accelerate the development of the library allowing the users to build it anywhere anytime even with the latest features.

**Comment by shrit** [comment]
I really do think we need a GSoC project called  ¨Document the mlpack library¨. I know it is not related to this issue, but it might help us a lot with special cases like this one.

**Comment by jeffin143** [comment]
+1 on it , We should decide it sooner so that we can adapt changes in that direction. On most occasion we discuss and then drop off until the next time the discussion is brought up :)

**Comment by conradsnicta** [comment]
> (rcurtin) I'm not really sure if 'recent' Ubuntu LTS means 18.04 or 20.04 now, or if recent RHEL means 7 or 8. 

As a general policy, I vote for the current Ubuntu LTS (20.04 as of now), as well as the current RHEL (8 as of now).  The gaps between RHEL releases are quite long (4+ years), necessitating updates of the Armadillo EPEL packages anyway.

> (rcurtin) we'd lose RHEL7

The default installation of RHEL 7 is lost anyway, as mlpack no longer compiles on RHEL 7 / CentOS 7 (https://github.com/mlpack/mlpack/issues/2939; TLDR: gcc 4.8 is too old to handle C++11 properly).

A simple though effective solution is to tell folks that still use RHEL 7 to use mlpack 3.4.2, which is known to work on that platform.  Same recommendation can be done for Ubuntu 18.04.

I suspect that by the time mlpack 4 is released, RHEL 9 will be close to release, putting RHEL 7 in legacy status.
Full support for RHEL 7 has stopped as of 6 Aug 2019.  RHEL 7 is currently in "Maintenance Support 2" phase (aka "product retirement" phase).  See https://en.wikipedia.org/wiki/Red_Hat_Enterprise_Linux#Product_life_cycle

> (rcurtin) I think we'll have to bump the EPEL8 package if we do 9.800 (but that's not hard, I am a maintainer there),

Since the EPEL8 Armadillo package would need to be updated anyway, I suggest bumping to 9.900.x, as that maintains API compatibility with the 9.x series, and provides nice improvements and speedups over 9.800.
