### ISSUE TITLE
R Logistic Regression handles labels incorrectly

### ISSUE THREAD

**Issue by david-cortes** [mlpack/mlpack#3053]
The documentation for `mlpack::logistic_regression` says that labels should be 0 or 1, but it doesn't actually work with zeros and ones, rather it needs ones and twos, otherwise ends up with an integer overflow:
```r
set.seed(1)
group1 <- data.frame(x = rnorm(1000, -1, .4),
					 y = rnorm(1000, -1, .2))
group2 <- data.frame(x = rnorm(1000, +1, .2),
					 y = rnorm(1000, +1, .4))
X = rbind(group1, group2)
X = rbind(X, c(-1, 1))

library(mlpack)
m = logistic_regression(training = as.matrix(X),
                        labels = as.matrix(as.numeric(X[,1] > 0)),
                        verbose = FALSE)
```
```
[FATAL] The labels must be either 0 or 1, not 18446744073709551615!

Error in logistic_regression_mlpackMain() : 
  fatal error; see Log::Fatal output
```

Adding +1 to the labels (which is wrong according to the documentation) avoids this problem:
```r
m = logistic_regression(training = as.matrix(X),
                        labels = 1+as.matrix(as.numeric(X[,1] > 0)),
                        verbose = FALSE)
```

**Comment by rcurtin** [comment]
Hey @david-cortes, thanks for the report.  I opened a PR, #3057, that at least fixes the documentation associated with logistic regression.  Actually, this is a little difficult to fix, because we generate bindings for lots of languages (including documentation) with the same input code.  It's a neat system, but we have to make sure our documentation is "agnostic" to the choice of language.

However, actually, even fixing the documentation isn't a total fix here, because what you encountered is a runtime error.  So I also opened #3059, which will now show an error that is a bit more helpful from the R side when `0` is passed as a label.

Hopefully this is all helpful!  Let me know if I've overlooked something.

**Comment by david-cortes** [comment]
> Hey @david-cortes, thanks for the report. I opened a PR, #3057, that at least fixes the documentation associated with logistic regression. Actually, this is a little difficult to fix, because we generate bindings for lots of languages (including documentation) with the same input code. It's a neat system, but we have to make sure our documentation is "agnostic" to the choice of language.
> 
> However, actually, even fixing the documentation isn't a total fix here, because what you encountered is a runtime error. So I also opened #3059, which will now show an error that is a bit more helpful from the R side when `0` is passed as a label.
> 
> Hopefully this is all helpful! Let me know if I've overlooked something.

Why not better modify the R code to make it take the labels as 0/1? I'll have to guess this comes from applying `factor` somewhere and then taking that output as an integer, and the fix would simply be to remove that coercion.

**Comment by rcurtin** [comment]
Honestly, I am not an expert at R (I can barely write it), so if you can tell me what would be more typical in R, that could be really helpful.  When the R bindings were written, the intention was to reflect whatever the "usual" usage in R would be.

@coatless any additional thoughts here on how we should represent labels numerically in R?  (e.g. `[0, numClasses)` or `[1, numClasses]`)

**Comment by david-cortes** [comment]
I guess the idiomatic way would be to only accept a "factor" type (at least that's how it's done in base R, in popular packages such as `glmnet`, `ranger`, `kernlab`, etc., and in less popular packages such as `LiblineaR`, `biglasso`, etc.), which behind the scenes is typically an integer type with numeration starting at 1, at the positive class is usually considered to be the last class in the factor encoding.

However if it's only going to take integers then yes it's trickier. If I were doing binary logistic regression and was told that the labels are to be integers, I'd expect them to be either 0/1 or -1/1, but for multi-class I'd expect them to be a range starting at 1. So not sure anymore.

**Comment by coatless** [comment]
@rcurtin thanks for the ping. Could you configure the mlpack bot to tag dirk or myself for future R questions? 

> When the R bindings were written, the intention was to reflect whatever the "usual" usage in R would be.

Correct. Glancing back at a PR from Yashwant: 

https://github.com/Yashwants19/RcppMLPACK/pull/6
https://github.com/Yashwants19/mlpack/pull/10#discussion_r462515076

We made an assumption that labels were coming in from a `matrix()` or `data.frame()`. If not, we cast them to integers when we were constructing inputs via the `data.matrix()`. At the time, R 4.0.0 was just released, which included factor coercion support to integers. This would map labels in factors from 0/1 to 1/2:

```r
R> factor(c(0,1))
[1] 0 1
Levels: 0 1
R> as.integer(factor(c(0,1)))
[1] 1 2
```

The issue here is the labels passed in as purely integer-based, e.g. 

```r
R> y = as.matrix(as.integer(X[, 1] > 0)) 
R> str(y)
 int [1:2001, 1] 0 0 0 0 0 0 0 0 0 0 
```

Thus, we're not hitting the factor conversion prior to mlpack. 

> @coatless any additional thoughts here on how we should represent labels numerically in R? (e.g. `[0, numClasses)` or `[1, numClasses]`)

From old PRs, I think we wanted to enforce `{0, 1}` labels to match with mlpack `{1, 2}` convention.

**Comment by coatless** [comment]
Adding the +1 to the integer labels, does yield the correct output: 

```r
R> # Initial data generation 
R> set.seed(1)
R> group1 <- data.frame(x = rnorm(1000,-1, .4),
+                      y = rnorm(1000,-1, .2))
R> group2 <- data.frame(x = rnorm(1000,+1, .2),
+                      y = rnorm(1000,+1, .4))
R> X = rbind(group1, group2)
R> X = rbind(X, c(-1, 1))
R> 
R> # Pull out from the function call label/design creation
R> y = as.matrix(as.integer(X[, 1] > 0)) + 1
R> design_matrix = as.matrix(X)
R> 
R> # Enter into debug mode
R> #debugonce(mlpack::logistic_regression)
R> 
R> m = mlpack::logistic_regression(
+     training = design_matrix,
+     labels = y,
+     verbose = TRUE
+ )
[INFO ] Training model with L-BFGS optimizer.
[INFO ] LogisticRegression::LogisticRegression(): final objective of trained model is 3.39528e-10.
```

**Comment by coatless** [comment]
That said, on the fatal error, I think we're trying to subtract 1 from the integer label which causes the large value:

```r
[FATAL] The labels must be either 0 or 1, not 18446744073709551615!
```

**Comment by rcurtin** [comment]
> @rcurtin thanks for the ping. Could you configure the mlpack bot to tag dirk or myself for future R questions?

Hehe, that actually would be nontrivial, so the easier thing would be to reconfigure myself to tag you when I see any R issues. :smiley: 

> I guess the idiomatic way would be to only accept a "factor" type (at least that's how it's done in base R, in popular packages such as glmnet, ranger, kernlab, etc., and in less popular packages such as LiblineaR, biglasso, etc.), which behind the scenes is typically an integer type with numeration starting at 1, at the positive class is usually considered to be the last class in the factor encoding.

I don't necessarily have a problem with that.  We use this utility function `to_matrix`: https://github.com/mlpack/mlpack/blob/master/src/mlpack/bindings/R/mlpack/R/matrix_utils.R#L19 --- I suppose that we could refactor it to allow only factor types for labels.

Based on what you wrote there, it seems like the easiest thing to do would be to keep the current range `[1, numClasses]`, since we don't have any mechanism to distinguish between binary classifiers and multiclass classifiers (these bindings are entirely generated from [C++ code like this](https://github.com/mlpack/mlpack/blob/master/src/mlpack/methods/logistic_regression/logistic_regression_main.cpp), so we have a somewhat generic interface from the C++ side, which limits what we can easily do).

>> @coatless any additional thoughts here on how we should represent labels numerically in R? (e.g. [0, numClasses) or [1, numClasses])
>
> From old PRs, I think we wanted to enforce {0, 1} labels. My memory escapes me, but I think this is the preferred class encodings for mlpack.  

By the time we get to C++, definitely we need classes starting from 0, but here we have the flexibility to choose something different for what we expect from R users.  Right now in the C++ conversion, we subtract 1 from whatever labels we got, which leads exactly to the issue you pointed out:

> That said, on the fatal error, I think we're trying to subtract 1 from the integer label which causes the large value:
>
> ```
> [FATAL] The labels must be either 0 or 1, not 18446744073709551615!
> ```

Exactly. :)  That's fixed in #3059, but before we merge that I wanted to see what we thought of @david-cortes's suggestion to switch the accepted labels to the range `[0, numClasses)`.

**Comment by coatless** [comment]
@rcurtin maybe we should opt to instead require a factor? This would allow us to abstract away from the 0/1 specification.

**Comment by rcurtin** [comment]
Are factors in widespread use by users of R?  (And I think that requires R 4.x, so are most users transitioned to that by now?)  If you don't think it would be inconvenient for users to force that restriction, then we can do that.

**Comment by coatless** [comment]
@rcurtin we already enforce the R 4.0.0 requirement. We never added strict type enforcement inside of the labeling section.

**Comment by david-cortes** [comment]
> Are factors in widespread use by users of R? (And I think that requires R 4.x, so are most users transitioned to that by now?) If you don't think it would be inconvenient for users to force that restriction, then we can do that.

It is indeed very typical to use factors, which have been supported since the beginning of R, and are passed as vectors (not matrices). The only libraries that I can think of which do not accept factors are gradient boosting ones like xgboost which take 0/1 labels instead (also as vectors). Libraries such as `ranger` or `e1071` will do regression if the label is numeric and classification if it is factor.

However some libraries which have classification-only models will also accept passing labels as integer or numeric, converting them to factors along the way and thus accepting any numbering for the labels.

The other thing with factors is that then when calling `predict` with something like `type="class"` it then returns classes from the factor encodings that were passed for fitting the model.
