### ISSUE TITLE
Korean translation

### ISSUE THREAD

**Issue by chws0508** [mlpack/mlpack#3092]
I want to contribute to this project. So can I translate the README document into Korean? Or is there a document that needs translation?

**Comment by shrit** [comment]
@chws0508 Thank you for your interest in mlpack.
I think it would be a great idea to provide a translation in Korean for mlpack documentations.
I think you can start by looking at the mlpack website, and translating installation tutorials since it is easier to publish the translation on the website rather than the README.
Let me know if you need any further clarification.

**Comment by rcurtin** [comment]
Hey @chws0508, thanks so much for volunteering.  I agree with @shrit that this would be a nice idea, but the problem is that I don't think we have the resources to maintain a Korean translation.  Very few mlpack contributors speak Korean, and so when we change the English documentation, we would have a difficult time keeping the Korean documentation up to date.  So, I don't think we should keep Korean resources directly in our repository at this time.  (Again my reasoning is entirely the difficulty of maintaining that and keeping it up to date.)

I think maybe it might be better to make some blog posts or similar, and then we can link to them from our documentation.  It would be easy to add some links on our documentation pages to some Korean versions or similar. :+1:

**Comment by zoq** [comment]
I think the tutorials are somewhat save in terms of text changes in the future, but I agree the code documentation would be difficult. Especially since we generate the documentation from the code itself.

That said, I don't see a problem if we have a direct translation of the tutorials (as long as we crediting the source) and put it into the wiki or medium or whatever.
