### ISSUE TITLE
How to use the optimizer in the ensmallen library for sparse datasets?

### ISSUE THREAD

**Issue by gzhwanghub** [mlpack/mlpack#3101]
`arma::sp_mat trainingData;`
`trainingData.load("../features.mat", arma::arma_binary);`
`arma::sp_mat trainingDataT = trainingData.t();`
`Row<size_t> trainingLabels;`
`trainingLabels.load("../labels.mat", arma::arma_binary);`
`ens::test::LogisticRegressionFunction<sp_mat> lrfTrain(trainingDataT, trainingLabels);`
`arma::sp_mat coordinates = lrfTrain.GetInitialPoint();`
`ens::IQN optimizer;`
`optimizer.Optimize(lrfTrain, coordinates);`

I read the sparse dataset into trainingData by referring to the website https://ensmallen.org/docs.html#built-in-callbacks example, and instantiated the LogisticRegressionFunction class. When I instantiated IQN and called the optimize() method, an error occurred: "In template: no viable conversion from'const Gen<arma::Mat< double>, arma::gen_randn>' to'BaseMatType' (aka'arma::SpMat<double>')", why can't I use the optimizer with sparse data sp_mat? How can I solve the problem?  Thanks.

**Comment by rcurtin** [comment]
Thanks for pointing this out!

I don't have a moment right now to write a patch and test case, but I can at least point you in the right direction---take a look at `iqn_impl.hpp`:

https://github.com/mlpack/ensmallen/blob/master/include/ensmallen_bits/iqn/iqn_impl.hpp#L84

That line probably needs to change to:

```
  BaseMatType initialIterate(iterate.n_rows, iterate.n_cols);
  initialIterate.randn();
```

However!  That is not a completely great solution, since it will initialize a `sp_mat` to be completely dense.  For the purposes of your work, you may want to use `sprandn()` or something like that.

When someone is able to actually fix this issue, we are probably going to need some more modification to `IQN` so that users can specify their desired initial point.

Anyway, I hope this at least helps you keep going for now, and we will get an actual solution into the codebase soon. :+1:
