### ISSUE TITLE
getting all class prediction with probability score for classification model like random forest

### ISSUE THREAD

**Issue by aminul-palash** [mlpack/mlpack#3138]
#### Problem location

Hi, I need **urgent help**, please help me to solve this, I'm working on random forest implementation for the prediction dataset. 
I'm following this tutorial. 
https://www.mlpack.org/doc/stable/doxygen/sample_ml_app.html

#### Description of problem
for a single data sample inference, it gives one predicted class label. But I want to get the other class prediction for the same sample sort with probability score, like the Sklearn function model.predict_proba(). But I did not find any way to get the prediction. but failed to do that. could you please help me with this?

**Comment by rcurtin** [comment]
> Hi, I need *urgent help*

What makes this request urgent?  You realize that we are all volunteers, right?  I would suggest not writing things like this in your issue reports---it doesn't exactly motivate me to help you more, especially since you could have solved this problem by looking through the documentation.

The [random forest documentation](https://www.mlpack.org/doc/mlpack-git/doxygen/classmlpack_1_1tree_1_1RandomForest.html) shows methods to do exactly what you are trying to do here.

**Comment by aminul-palash** [comment]
> > Hi, I need _urgent help_
> 
> What makes this request urgent? You realize that we are all volunteers, right? I would suggest not writing things like this in your issue reports---it doesn't exactly motivate me to help you more, especially since you could have solved this problem by looking through the documentation.
> 
> The [random forest documentation](https://www.mlpack.org/doc/mlpack-git/doxygen/classmlpack_1_1tree_1_1RandomForest.html) shows methods to do exactly what you are trying to do here.

sure, thanks. I'll try!
