### ISSUE TITLE
MLPack build for android clang++: error: unknown argument: '-fno-allow-half-arguments-and-returns'

### ISSUE THREAD

**Issue by robi56** [mlpack/mlpack#3160]
#### Issue description

I am trying to build mlpack from Android arm64-v8a  architecture using Android-NDK and mlpack cross-compile cmake file.  
During the **make** command, the following error is introduced. 

error: half args and returns was disabled in PCH file but is currently enabled

![problem](https://user-images.githubusercontent.com/2936512/156559531-cc52021e-e0ae-4161-9a87-eab490c9a120.png)

To resolve the issue I added 
`set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -fno-allow-half-arguments-and-returns")`

at CMakeLists.txt file , but it introduces the following error. 

`clang++: error: unknown argument: '-fno-allow-half-arguments-and-returns'`

![problem-1](https://user-images.githubusercontent.com/2936512/156559591-d045dd2b-7bd6-4d7c-9d65-497a3db7bce6.png)

Also there is another problem , `error: PCH file was compiled for the target 'x86_64-unknown-linux-gnu' but the current translation unit is being compiled for target 'aarch64-none-linux-android21'`

#### Your environment

 * version of mlpack: latest version 
 * operating system: linux 
 * compiler:  glang++
 * version of dependencies (Boost/Armadillo): 
 * any other environment information you think is relevant:

**Comment by shrit** [comment]
This is interesting, what is the command you used for the cross-compilation?
I never tried to do the cross-compilation with clang, in the case of mlpack.
As you are on Linux, do you mind using the g++ compiler?

**Comment by robi56** [comment]
> This is interesting, what is the command you used for the cross-compilation? I never tried to do the cross-compilation with clang, in the case of mlpack. As you are on Linux, do you mind using the g++ compiler?

I have used the following command 

`cmake ../   -DCMAKE_SYSTEM_NAME=Android   -DCMAKE_SYSTEM_VERSION=21   -DCMAKE_ANDROID_ARCH_ABI=arm64-v8a   -DCMAKE_ANDROID_NDK=../android-ndk-r21e-linux-x86_64/android-ndk-r21e/   -DCMAKE_ANDROID_STL_TYPE=gnustl_static -DLLVM_INCLUDE_TESTS=OFF -DCMAKE_ANDROID_STL_TYPE=c++_static -DCMAKE_SYSROOT=../android-ndk-r21e-linux-x86_64/android-ndk-r21e/toolchains/llvm/prebuilt/linux-x86_64/sysroot -DTOOLCHAIN_PREFIX=../android-ndk-r21e-linux-x86_64/android-ndk-r21e/toolchains/ -DBLAS_LIBRARIES=../OpenBLAS-0.3.20/libopenblas_haswellp-r0.3.20.a -DUSE_OPENMP=OFF -DGFORTRAN=./gcc-7/libgfortran.a -DBOARD_NAME=RPI0 -DCMAKE_CXX_FLAGS="-std=libc++" -DCMAKE_CXX_FLAGS="-std=gnu++11" -DCMAKE_CXX_FLAGS="-fsigned-char"  -DCMAKE_CXX_FLAGS="-fmath-errno" -DCMAKE_ANDROID_NATIVE_API_LEVEL="android-21" -DCMAKE_CXX_FLAGS="-std=c++14"
`

**Comment by shrit** [comment]
how did you download mlpack dependencies?

**Comment by robi56** [comment]
> how did you download mlpack dependencies?
armadillo is downloaded when compiling **cmake** command  under the deps folder 
.....build_android/deps/armadillo-10.3.0/include (found version "10.3.0") 

Other   dependencies are from taken from system 

-- Found StbImage: /usr/local/include/stb/  
-- Found Ensmallen: /usr/local/include (found suitable version "2.14.2", minimum required is "2.10.0") 
-- Found cereal: /usr/include (found suitable version "1.3.0", minimum required is "1.1.2") 
-- Found Boost: /usr/include (found suitable version "1.71.0", minimum required is "1.58")  
-- Found Git: /usr/bin/git (found version "2.25.1") 
-- Found Doxygen: /usr/bin/doxygen 

For cross compiling ,  I downloaded OpenBLAS
deps/OpenBLAS-0.3.20/libopenblas_haswellp-r0.3.20.a

**Comment by shrit** [comment]
You can not take other dependencies from the host root filesystem, you need to download them locally and point out the path for each of them, or integrate them with the target SYSROOT.
The compiler will eventually at some point mix the paths and will include the C++ header from the main root file system.
You were lucky in the case of android as you have pointed out to basically everything the compiler needs for Android.

The PCH's are precompiled headers. mlpack uses these to reduce the compilation time. The error means that these headers have been compiled for x86 which can not be used eventually for arm architectures.

To avoid this error, please start with a new build directory each time you want to compile. It might increase the required time since you are losing the CMake caching but will be much safer, especially with CMake.

We use this command to cross-compile at mlpack:

```
cmake -DDEBUG=OFF -DPROFILE=OFF -DBUILD_MARKDOWN_BINDINGS=OFF -DBUILD_PYTHON_BINDINGS=OFF -DBUILD_GO_BINDINGS=OFF -DBUILD_JULIA_BINDINGS=OFF -DBUILD_R_BINDINGS=OFF -DCMAKE_TOOLCHAIN_FILE=../board/crosscompile-toolchain.cmake -DBOARD_NAME="RPI4" -DDISABLE_DOWNLOADS=OFF -DTOOLCHAIN_PREFIX=/path/to/CrossCompile-mlpack-for-embedded-aarch64/aarch64--glibc--stable-2020.08-1/bin/aarch64-buildroot-linux-gnu- -DCMAKE_SYSROOT=/path/to/CrossCompile-mlpack-for-embedded-aarch64/aarch64--glibc--stable-2020.08-1/aarch64-buildroot-linux-gnu/sysroot ../
```

We do have an auto downloader to take care of this specific issue, it downloads these deps and cross-compile OpenBLAS for you.

In the above command, I have disabled bindings, as they are not supported directly yet.

In addition to the above command add what you think is good for your Android environment.

To be honest with you I never tried to cross-compile with clang, so this is interesting. However, I might think that the precompiled headers are the origin of the problem, Would you please try to integrate this command with your Andriod flags? give it a try and then let me know what will happen?
