### ISSUE TITLE
cmake missing ARMADILLO_LIBRARY

### ISSUE THREAD

**Issue by winckrc** [mlpack/mlpack#3166]
#### Issue description

CMakeLists.txt does not use ARMADILLO_LIBRARY.

#### Your environment

 * 3.6
 * Ubuntu 18.04.6
 
#### Steps to reproduce

Install Armadillo in a custom location and use 
run cmake -D ARMADILLO_LIBRARY=(/path/to/armadillo/libarmadillo.so) ../
to try to install mlpack

#### Expected behavior

mlpack successfully installs using the version of Armadillo in the custom location

#### Actual behavior

cmake error

**Comment by winckrc** [comment]
Actually, it appears that the name in CMakeLists.txt is ARMADILLO_LIBRARIES instead of ARMADILLO_LIBRARY as in the ReadMe instructions.

**Comment by zoq** [comment]
`ARMADILLO_LIBRARY` is used in the cmake module: https://github.com/mlpack/mlpack/blob/master/CMake/FindArmadillo.cmake

When you use ` cmake -D ARMADILLO_LIBRARY=(/path/to/armadillo/libarmadillo.so) ../` it's not picking up the custom location?

**Comment by shrit** [comment]
There is no bug, it is indeed `ARMADILLO_LIBRARIES`

**Comment by rcurtin** [comment]
There's more complexity here than meets the eye.  Armadillo *optionally* uses `libarmadillo.so`, depending on the configuration of the library.  So you can use Armadillo in header-only 'mode'---and it doesn't need to link against `libarmadillo.so`---or you can use Armadillo with `ARMA_USE_WRAPPER` and then it will use the wrapper library and link against `libarmadillo.so`.

Now for the CMake search process, CMake will first find the Armadillo include directories and then look in `armadillo_bits/config.hpp` in order to determine if `ARMA_USE_WRAPPER` is set.  *Only* in the case where it is set will CMake then attempt to find `ARMADILLO_LIBRARY`.  When `ARMADILLO_LIBRARY` is found, it is then appended to the list of other things that may need to be linked against in order to form `ARMADILLO_LIBRARIES`.

Thus, you must ensure that `ARMA_USE_WRAPPER` is set in whatever include directory Armadillo is in if you want `ARMADILLO_LIBRARY` to be used.  If I am correctly guessing that you have built Armadillo from source with `./configure && make` and are trying to use the `include/` path in the Armadillo source directory as the Armadillo include directory, you should instead use `tmp/include/`, which contains the configured `armadillo_bits/config.hpp` with `ARMA_USE_WRAPPER` set.

That's probably a more complicated answer than you were hoping for, but there is a lot of complexity in how Armadillo links, and thus this is a little complex.  Hopefully it helps---let me know if I can clarify anything. :+1:
