### ISSUE TITLE
C++17 switch

### ISSUE THREAD

**Issue by Alessandro-Barbieri** [mlpack/mlpack#3183]
### What is the desired addition or change?

provide a cmake c++17 switch

### What is the motivation for this feature?

to not depend on the std_backport

### If applicable, describe how this feature would be implemented.

change those lines from `11` to `17` conditional to a global define

https://github.com/mlpack/mlpack/blob/de94eee6881e33f1145d9d4a8b5380a5be8af36a/CMakeLists.txt#L113
https://github.com/mlpack/mlpack/blob/de94eee6881e33f1145d9d4a8b5380a5be8af36a/src/mlpack/bindings/R/mlpack/src/Makevars#L3
https://github.com/mlpack/mlpack/blob/de94eee6881e33f1145d9d4a8b5380a5be8af36a/src/mlpack/bindings/R/mlpack/src/Makevars.win#L3
https://github.com/mlpack/mlpack/blob/de94eee6881e33f1145d9d4a8b5380a5be8af36a/src/mlpack/bindings/python/setup.py.in#L55

**Comment by zoq** [comment]
Hello @Alessandro-Barbieri is that something you like to add, or a feature request?

**Comment by Alessandro-Barbieri** [comment]
It's a feature request

**Comment by Davidportlouis** [comment]
@zoq I would like to work on this

**Comment by Wansh619** [comment]
Hi is anyone working on this issue ?
I am a newcomer in open source and i want to learn so can snyone provide me some resources regarding  this issue

**Comment by zoq** [comment]
@Davidportlouis gave this a shot in https://github.com/mlpack/mlpack/pull/3185 but it was going in another direction, @Davidportlouis let us know if you like to continue with it.

**Comment by Davidportlouis** [comment]
@zoq, you can assign @Wansh619 on this issue, I'll follow up with it later on.

**Comment by Wansh619** [comment]
But please  someone give me resources  to solve this issue

**Comment by Davidportlouis** [comment]
> But please  someone give me resources  to solve this issue

Take a look at comments in PR #3185. My understanding is that we cannot simply bump C++ version to 17 since it is not fully supported in some platforms such as RHEL. As a makeshift solution @rcurtin  suggested in #3185 that we can add a cmake option to use C++17 when explicitly make option is set by the user while building provided that the platform supports C++17. @zoq @rcurtin, is that right or am I missing something else ?

**Comment by zoq** [comment]
That is correct, also take a look at the first comment, it has some good pointers in that direction. Ideally it should be possible to define the standard with `cmake -D CXX_STANDARD=17`, however as pointed out in the first comment, in several places the standard is hard-coded, which needs to be updated.

**Comment by shrit** [comment]
I think when @conradsnicta shift armadillo to C++17 we will shift mlpack to the same standard.

**Comment by conradsnicta** [comment]
@shrit That may be a while yet.  Armadillo aims to support the current and previous version of RHEL and Ubuntu LTS.  At the time of writing, this is RHEL 8 and 9, as well as Ubuntu 20.04 and 22.04.

The oldest out of these is RHEL 8, which has gcc 8.x as the default compiler.  That version of gcc has only experimental support for C++17.  RHEL 9 uses gcc 11, which has C++17 as the default standard.  RHEL 10 will probably be released in about 3 years (~2025?), so that's the earliest Armadillo may switch to the C++17 standard.  

However, I currently do not see a need to switch to C++17, as the vast majority of Armadillo codebase only requires features provided by the C++11 standard.  Internally the codebase optionally uses C++14/C++17/C++20/C++23 features for convenience.

It's more likely that Armadillo would switch to C++14, maybe next year, mainly to reduce the maintenance burden of the codebase.

The above is a long winded way of saying that Armadillo is not meant to be stopping mlpack from moving to C++17 earlier, if it's deemed advantageous.  At the same time, there is benefit in providing support for existing platforms (ie. RHEL 8/9 and Ubuntu 20.04/22.04), in order to maximise utility by the mlpack userbase.
