### ISSUE TITLE
assert(splitCol > begin) failed when constructing a ball tree

### ISSUE THREAD

**Issue by zouxianghong** [mlpack/mlpack#3205]
here is my code:

```
// Custom metric type
class WeightedCosineMetric {
public:
    WeightedCosineMetric() {}
    template<typename VecTypeA, typename VecTypeB>
    static double Evaluate(const VecTypeA& a, const VecTypeB& b) {
        const auto diff = a - b;
        std::vector<double> weights;
        for (size_t i = 0; i < diff.get_n_elem(); ++i) {
            weights.push_back(std::exp(-lambda_ * diff[i] * diff[i]));
        }
        double sum_w_u_v = 0.0;  // sum(Wi * Ui * Vi)
        for (int i = 0; i < weights.size(); ++i) {
            sum_w_u_v += weights[i] * a[i] * b[i];
        }
        double sum_w_u_u = 0.0;
        for (int i = 0; i < weights.size(); ++i) {
            sum_w_u_u += weights[i] * a[i] * a[i];
        }
        double sum_w_v_v = 0.0;
        for (int i = 0; i < weights.size(); ++i) {
            sum_w_v_v += weights[i] * b[i] * b[i];
        }
        if (sum_w_u_u * sum_w_v_v < BaseType::Epsilond) {
            return 1.0;
        }
        double distance = 1.0 - sum_w_u_v / std::sqrt(sum_w_u_u * sum_w_v_v);
        return distance;
    }

    static double lambda_;
};

// data
arma::mat data;
// ... fill data here

// Tree construction
mlpack::neighbor::NeighborSearch<
    mlpack::neighbor::NearestNeighborSort,
    WeightedCosineMetric,
    arma::mat,
    mlpack::tree::BallTree> knn(data);
```

issue:
It failed when running 'SplitNode'
```
...
splitCol = splitter.PerformSplit(*dataset, begin, count, splitInfo. oldFromNew);

assert(splitCol > begin);  // Failed here !!!
```

**Comment by rcurtin** [comment]
I think the issue here is that the weighted cosine metric class you are using does not satisfy the triangle inequality.  I have not formally done the derivation, but it is at least worth pointing out that the cosine similarity `X Y / (||X|| ||Y||)` does not satisfy the triangle inequality, and it looks like that is roughly what you have implemented here.

If you can re-cast your problem such that you are using a metric that *does* satisfy the triangle inequality, then the code should work.

If you want to do neighbor searching with trees using a distance measure that does not satisfy the triangle inequality, you could try the `FastMKS` class, which is made for similarity searching when the measure is only a Mercer kernel: https://www.mlpack.org/doc/stable/doxygen/fmkstutorial.html

I hope this helps!  Let me know if I can clarify anything. :+1:

**Comment by zouxianghong** [comment]
谢谢，收到

**Comment by zouxianghong** [comment]
谢谢，收到

**Comment by rcurtin** [comment]
Ok, I will go ahead and close this issue then. :+1:
