### ISSUE TITLE
Unable to install MLPACK on windows...please help..

### ISSUE THREAD

**Issue by rcurtin** [mlpack/mlpack#325]
**Reported by dineshj92 on 29 Dec 44200834 09:08 UTC**
I was nearly working for a week day and night to install & configure the mlpack in my windows 8 OS and I could not do so. When I ran the sparsecoding.cpp, I got tons of error, however, after providing 'include' paths for armadillo,libxml,iconv etc., the error list got reduced. All I need to know is that, how can I build and generate mlpack.lib file on windows. Please help!!!

**Comment by II-Matto** [comment]
Hi, the problem for me is that I could not find the *.lib files of libxml2. There is only *.a files (I downloaded the 2.9.2 version).

When compiling Armadillo with Visual Studio 2013 and Intel C++ 15.0, only a very small *.dll is generated (no symbols are exported), and I can only generate a *.lib from the *.dll compiled with mingw64. Is there a better way to deal with this?

As for the iconv, I downloaded the 1.9.2 version and there is only libiconv2.dll instead of the mentioned iconv.dll. In addition, I have no clue whether this is for x86 or x64.

I really hope someone could share the dependency *.lib and *.dll with version information clearly stated as well as which version of the boost lib is used.

**Comment by rcurtin** [comment]
The libxml2 version I used (a long time ago) I obtained from here:
ftp://ftp.zlatkovic.com/libxml/
You can get a pre-compiled iconv version from the same place, and there should be a .lib file in each of those.

Unfortunately I have not compiled mlpack on Windows in quite some time, so I am not too much help.  I am hopeful that I will have time to get a Windows build working and stable; however, it is unfortunately somewhat low on my priority list...

**Comment by II-Matto** [comment]
@rcurtin I checked the link again. The win32 packages contain *.lib files. I downloaded the x64 files previously and there are only *.a files. I will try to compile a x86 version.
