### ISSUE TITLE
Discussion: everything into one namespace for mlpack 4?

### ISSUE THREAD

**Issue by rcurtin** [mlpack/mlpack#3261]
As part of the transition to a header-only library, a number of changes are being made to simplify includes (#3255 and discussion), build configuration (#3256), and many other parts of the library.  This is meant to make things easier on the user.

But there is one additional consideration, though it will break pretty much all user programs: putting *everything* non-internal into the `mlpack` namespace, instead of having many sub-namespaces.  Originally we used namespaces to separate the methods entirely, but I'm not convinced this is necessary anymore, and it results in users needing to know a lot about the different namespaces inside of mlpack; for instance, `mlpack::tree` stores both space partitioning trees and decision trees, `mlpack::regression` stores some regression algorithms, so on and so forth.

Now a user would only need to add `using namespace mlpack` to their program, not a bunch of `using` declarations for different sub-namespaces.

The only namespaces I would keep would be the ones in `core/`, many of which aren't really touched by users.  One exception is `mlpack::data`, which I think is better to leave as-is, because that is very specifically about dataset loading/saving operations and similar (and honestly perhaps should be its own standalone library!  But that can wait until some other time).

Before I pull the trigger on this, I'd like to collect some thoughts, so if anyone has any thoughts please speak up!  I'm virtually certain @conradsnicta will support the idea :smile:

**Comment by shrit** [comment]
Yes, let us do this, but let us name the common namespace `ml` instead of `mlpack` for the following reasons:

1. This will be similar to Armadillo, just `arma`, and that is all.
2. Some people like me prefer to use the namespace in their software, probably because this will tell you where the function is coming from.
3. Using `ml` is shorter and directed to the point and reduce the burden of writing `mlpack` all the time if you would like to type the namespace
4. The `data` namespace is not necessary as well, exposing an additional one to the user is confusing.

When the `data` lib becomes standalone then we can give it another namespace but for now, removing `data` gives more consistency.

**Comment by conradsnicta** [comment]
@rcurtin I certainly support this idea :)  In general, I support the notion that simplicity of use should be weighted at least as equally (and preferably more) than the internal development/maintenance effort, all within reasonable limits.

With the above in mind, I also like the proposal by @shrit to shorten the namespace to simply `ml`.  Note that `ml` and `mlpack` may possibly co-exist, by employing the namespace alias mechanism (https://en.cppreference.com/w/cpp/language/namespace_alias).  This could be done directly by mlpack, or we can leave the choice to users.

I'm also a big proponent of keeping backwards compatibility wherever possible (while allowing evolution), and where there is no heavy burden on developers for creating/maintaining the backwards compatibility. Rather than completely breaking user code, mechanisms and workarounds are possible to ameliorate and/or prevent breaks.  Smooth changes may also be preferred, where old code is deprecated and compile time warnings are issued.

Given the breaking nature of the proposed changes, it may be possible to provide a degree of user code compatibility between mlpack-3 and mlpack-4 by making the old nested namespaces empty, except for `using namespace` declarations.  For example:

    namespace mlpack
    {
      namespace tree { using namespace mlpack; }  // may need to be ::mlpack ?
      namespace regression { using namespace mlpack; }
    }

The above code is not tested, so there may be issues such as clashes within user code.  If there is user code which already has `using namespce mlpack::tree`, the above may in effect "import" stuff from the mlpack namespace twice.  This is just speculation at this point, as I haven't explored this corner of C++.  More details at cppreference:  https://en.cppreference.com/w/cpp/language/namespace

An alternative approach to prevent breaks would be to keep all of the nested namespaces (and the code within) as is, and then simply add `using namespace` declarations within the enveloping mlpack namespace.  For example:

    namespace mlpack
    {
      namespace tree { /* code goes here as in mlpack-3 */ }
      using namespace tree; // import all stuff from the tree namespace to make it easier for users
    }

**Comment by zoq** [comment]
I'm not in favour of using `ml` over `mlpack` for branding reasons, in case of armadillo or ensmallen, I think the alias is unique enough so people will associate it with the project, but I don't think it's the case for `ml = mlpack`. Otherwise putting the code into a single namespace makes things easier, especially if we are strict about it e.g. not having another `data` namespace.

**Comment by rcurtin** [comment]
Ok---sounds like support is positive for the idea.  I like the reverse compatibility trick.  For now I guess let's call it `mlpack` instead of `ml`, but, I guess someone could do `namespace mlpack = ml` in their code if they wanted to shorten the name.

**Comment by rcurtin** [comment]
#3269 implements the changes here, so once that's merged, I guess we can close this issue. :)

**Comment by conradsnicta** [comment]
for posterity: also minor followup in #3279
