### ISSUE TITLE
Upgrade Catch to latest version

### ISSUE THREAD

**Issue by shubham1206agra** [mlpack/mlpack#3262]
Since mlpack migrated to use C++14 as the minimum version. Maybe we should upgrade to the latest Catch version.
https://github.com/catchorg/Catch2/releases/tag/v3.0.1

**Comment by conradsnicta** [comment]
Catch v3 has changed considerably compared to v2, and is (in my opinion) now unnecessarily more difficult to use.  It also appears that mlpack tests would need to me reworked in order to migrate to catch v3.

I'm not sure that catch v3 brings in any new functionality that would be required by mlpack tests.  It is a testing framework, so it's not critical.  Migrating to catch v3 would only be required if catch v2 "breaks" due to bit rot (https://en.wikipedia.org/wiki/Software_rot).

Catch v2 still works, and is likely to be supported for a considerable amount of time: https://github.com/catchorg/Catch2/commits/v2.x

**Comment by shrit** [comment]
There is no need for such an upgrade. Catch is header-only, that is one of the reasons that you do not have to upgrade as long as it no longer compiles or the current features are not working anymore.
