### ISSUE TITLE
Can mlpack use hardware acceleration such as AMD GPUs via OpenCL?

### ISSUE THREAD

**Issue by rajhlinux** [mlpack/mlpack#3272]
Would like to offload CPU and wondering if mlpack can use AMD GPUs via OpenCL.

**Comment by conradsnicta** [comment]
Currently it's not done directly.  There is related effort to make Bandicoot, a library that has Armadillo-like API and runs on GPUs: https://gitlab.com/conradsnicta/bandicoot-code

**Comment by rajhlinux** [comment]
So how do I interface MLPack with Bandicoot?

Thanks.

**Comment by rcurtin** [comment]
Unfortunately at this point that's not likely to work very well, since Bandicoot doesn't implement most of the operations that mlpack uses.  The vision is that where you might currently write, say, `mlpack::FFN<LossType, InitType>` to represent a neural network, you could write `mlpack::FFN<LossType, InitType, coot::mat>` to indicate that you want the network to use `double`-type Bandicoot matrices, where the memory is stored on the GPU.

However, there is still quite a ways to go until that all works!
