### ISSUE TITLE
No libraries after build on MacOS

### ISSUE THREAD

**Issue by DavitMob** [mlpack/mlpack#3273]
#### Issue description

Hi. I am trying to build mlpack master branch on MacOS. I am particularly interested in mlpack_random_forest. Building on windows it outputs both .lib and .exe files. On MacOS after the build, there are only executables. Do I miss something? How/where can I get libraries to use it in my project?

#### Your environment

 * version of mlpack: master
 * operating system: MacOS Monterey

#### Steps to reproduce

clone repo, install dependencies, build.

#### Expected behavior

Libraries should be available after the build.

#### Actual behavior

No library found.

**Comment by conradsnicta** [comment]
The code in the master branch has recently changed so that mlpack is header only.  There shouldn't be an mlpack runtime library anymore.

On top of that, the header structure has also changed, so now it's only necessary to have `#include <mlpack.hpp>` instead of numerous includes.

There are further changes in the works, where everything is placed in the mlpack namespace, instead of numerous namespaces.

**Comment by DavitMob** [comment]
Thanks @conradsnicta
