### ISSUE TITLE
Too many Broken Links

### ISSUE THREAD

**Issue by jsauermann** [mlpack/mlpack#3284]
#### Problem location

Actually many. Several links are broken and return nothing. For example
https://www.mlpack.org/doc/stable/cli_documentation.html#perceptron exists,
but clicking "Detailed Description" on that page does not work. Same for many
(but not all) Detailed Descrtiptions.

#### Description of problem

Since Perceptron is a fairly old method, I suppose that the documentation actually exists,
but the generation of the links is faulty. I tried a number of variants (CLI, Python etc) as well
as releases (mlpack-git, mlpack-3.4.2, etc.), and mlpack-git seems to work best (but still
having many missing links).

Thank you for providing mlpack,
Dr. Jürgen Sauermann
GNU APL

**Comment by rcurtin** [comment]
Thank you so much for the report!  I can see that the URL for `detailed description` is `https://www.mlpack.org/doc/stable/perceptron_detailed-documentation`, which is definitely incorrect---it is supposed to be an anchor in the current page.  So there is a `#` missing.  However, this documentation is all auto-generated, so instead of fixing it directly, I have to go find the code to fix so that the output is correct. :)  I'll start digging!

**Comment by rcurtin** [comment]
Thank you again for reporting this!  I did get it resolved in #3290, and now the fixed links are deployed to the website.  Please don't hesitate to open more issues in the future if you find more issues! :+1:
