### ISSUE TITLE
C++ Doxygen documentation returns empty response

### ISSUE THREAD

**Issue by dibalikpohon** [mlpack/mlpack#3289]
#### Problem location

Here's the link of the broken web. [C++ Doxygen Documentation Index](https://www.mlpack.org/doc/stable/doxygen/index.html)

#### Description of problem
It seems like the website that I open returns only a blank page without any errors on the console. This also happens on the other website that is under the `/doxygen` path like [https://www.mlpack.org/doc/mlpack-3.1.1/doxygen/classmlpack_1_1ann_1_1FFN.html](https://www.mlpack.org/doc/mlpack-3.1.1/doxygen/classmlpack_1_1ann_1_1FFN.html).

**Comment by dibalikpohon** [comment]
Apparently, this issue should be in this [repository](https://github.com/mlpack/mlpack.org/issues?q=is%3Aopen+is%3Aissue). Since it is related to the web, not the mlpack itself. I apologize.

**Comment by rcurtin** [comment]
No worries!  The report got to us either way. :)  It took a little while, but I got the website to build again properly: https://www.mlpack.org/doc/stable/doxygen/index.html  Now, the link that you gave works correctly.  Sorry for the inconvenience!

**Comment by mhudnell** [comment]
Also, the doxygen link on this github's readme leads to a 404. https://www.mlpack.org/doc/mlpack-git/doxygen/index.html

**Comment by rcurtin** [comment]
Thanks for the report @mhudnell; actually in #3265 we moved away from Doxygen because it was a huge amount of maintenance burden, and honestly the output it generated was pretty ugly given all the templates that are in use in mlpack.  I think it is easier to browse and search the source than to use Doxygen... that said, I do hope to provide better user documentation for the C++ classes overall, kind of like we do for [ensmallen](https://www.ensmallen.org/docs.html).  Anyway, I opened #3299 to fix the bad links.
