### ISSUE TITLE
Gaussian Process Regression

### ISSUE THREAD

**Issue by plugyawn** [mlpack/mlpack#3319]
### What is the desired addition or change?

Wanted a Gaussian Process Regressor in C++. I have some experience in writing GPs from scratch in python, so if possible, I would love to contribute.

### What is the motivation for this feature?

Probabilistic methods and uncertainty metrics are important parts of an ML library, so I wanted MLPack to have this as well.

**Comment by rcurtin** [comment]
Hi there @plugyawn!  This would be a nice addition.  If you want to implement it, it should be a relatively simple review.  Ideally the API should match that of the `BayesianLinearRegression`, `LinearRegression`, and `LARS` classes (although there might be slight variation), so that a user can easily switch between all these methods. :+1:

**Comment by plugyawn** [comment]
Hi @rcurtin! That sounds great! I'll look into the code and try my best to implement a compliant GPR implementation.

**Comment by chetanpandey1266** [comment]
I have also read about GPR, can I also try and implement this?

**Comment by plugyawn** [comment]
My exams just finished, so I'm trying to work on it at the moment. Let me give it a go first, if that's fine? 

Sorry it's taking time. Needed to do some cursory reading.

**Comment by chetanpandey1266** [comment]
Okay, by the time I'll also try to implement and we can discuss about if we are stuck at some point
