### ISSUE TITLE
Some code examples in approx_kfn tut giving errors

### ISSUE THREAD

**Issue by AdarshSantoria** [mlpack/mlpack#3397]
#### Problem location

(https://github.com/mlpack/mlpack/blob/master/doc/tutorials/approx_kfn.md)

#### Description of problem

1. Code examples in "Approximate furthest neighbors with defaults" are not working as l (number of projections) and m (number of points) are not set default by value in codebase and that's why throwing errors. Though these parameters depend on other parameters like dataset, if we want to give some default values to them then I think `**l=10**` and `**m=3**` will be a good option for ```DrusillaSelect``` implementation ( `l=10` and `m=l/3` ,that is 3, produces acceptably good approximations for most datasets) and for ```QDAFN```, `**m=l**` will be a good option but not able to figure out any exact value as their default ones.

2. `KFN::DUAL_TREE_MODE` is used in  "Simple furthest neighbors example", this must be replaced with `DUAL_TREE_MODE` as code was updated.

**Comment by rcurtin** [comment]
When I worked on those approximate furthest neighbor search algorithms years ago, I found it very difficult to find a specific setting of `l` and `m` that worked well across datasets.  That's why I didn't add a default value to those classes in C++.  However, it looks like I was inconsistent, and I added default parameters to the bindings (5 for both `l` and `m`).  I'm not quite sure why I did that.

Did you try your values of `l = 10` and `m = 3` and `l = m = 10` for a number of different datasets?  If they work "well" (or at least reasonably), I don't mind updating the bindings to have those new values, and updating the classes to use those default parameters.

Agreed that `DUAL_TREE_MODE` is a change we should make.

Thanks for looking into these!

**Comment by AdarshSantoria** [comment]
Based on some articles and papers which I read and after trying it out on some datasets, I felt that the values for l and m as 10 and 3 respectively give appreciable results. I have not tried these values on multiple dataset so I am not sure if this is a genralisation but I feel these values of l and m give good results. I also tried with `l=5`sets. and `m=5` as in your code as this also gives good results on similar datasets.

**Comment by rcurtin** [comment]
At least personally I'm not too picky about what we choose so long as the documentation makes clear that the values often need tuning for particular datasets.  If you want to open a PR to make those changes (and also the tree change) please feel free. :+1:

**Comment by AdarshSantoria** [comment]
I feel the same. I don't think there is a requirement of pr for the default parameters. I will raise a pr for tree change.
