### ISSUE TITLE
Adding Predict function

### ISSUE THREAD

**Issue by aadi-raj** [mlpack/mlpack#3418]
### Feature Request:
While going through various source files for implementing sanity check as mentioned in #2820, I noticed that some of the key methods lack Predict function. Few methods that came under my notice:
 
- Kmeans
- Adaboost
- DBSCAN

I have not gone through every method, so it is not the complete list.
It would be a nice addition to the library since many people prefer to use it.

Thanks,
Adi

**Comment by conradsnicta** [comment]
If there is a compelling use case for adding specific functionality (eg. likely to be used by many people), I suggest to open a PR which provides the reasoning as well as the proposed code, along with associated documentation.  The reasoning should provide clear use cases.

**Comment by rcurtin** [comment]
What does "predicting" with DBSCAN or k-means mean?  The use of that term is an artifact of the decisions of the scikit maintainers, who shoved everything into this fit/predict model.  That's fine, and it's standard now, and I get why they did that, but that's not what we chose to do for mlpack in part because that model doesn't make sense for every machine learning algorithm (it *really* doesn't make sense for nearest neighbor search (note that I mean nearest neighbor search, not the nearest neighbor search classifier), which was one of the core functionalities of mlpack many years ago when these decisions were made).

`AdaBoost` does have a method `Classify()` which serves the same purpose.  k-means and DBSCAN don't have `Train()` (or "fit") methods, they have `Cluster()` methods because they're clustering algorithms, not supervised or unsupervised learning algorithms.

For k-means or DBSCAN, I don't mind adding functionality that would return the cluster of a new point that was not a part of the set that was originally used for clustering.  It seems like it would be a useful addition. :+1:

**Comment by rcurtin** [comment]
No worries, and there's definitely no hurry.  It can be hard for me to find free time to keep up with all the reviews. :)

**Comment by rcurtin** [comment]
Definitely global variables are not the way to go.

Honestly I think the right way with mlpack to do cluster assignments is to use mlpack's k-nearest-neighbor search.  However even that class has lots of bells and whistles of its own, and we probably don't want to replicate all of those as options in whatever function we implement in the `KMeans` class.  So my suggestion would be this: add an `Assign()` method (not `Predict`, the terminology does not make sense) that internally uses the `kNN` class.  Users will have to pass the centroids and the data points they want cluster assignments for.  `KMeans` does not store data points or centroids internally.  The documentation should make it clear to users that if they want more control over how the nearest neighbor search is done, they should use the k-nearest-neighbor search class instead, and an example of how to do so should be provided.

I'm going to be honest: I can't keep up with all of the PRs that have been opened.  If you open this one, I have no idea when---or if---I'll even be able to get to it.  Maybe someone else will be able to, but don't be surprised if a very long time passes.

**Comment by aryaman1202** [comment]
@rcurtin Can I work over this issue? I am eager to solve this problem and contribute towards mlpack.
