### ISSUE TITLE
Loading dat  files

### ISSUE THREAD

**Issue by nevoliu** [mlpack/mlpack#3425]
Hello, your work is very good！
How to modify the source code to support loading dat files?

**Comment by rcurtin** [comment]
I'm not sure precisely the format you need for `.dat` files, but if Armadillo does not already support that format, you would want to look at how `data::Load()` is implemented, and add a new format there.  Basically if you read the code in `src/mlpack/core/data/load_impl.hpp` you will see that the type of file is chosen based on the extension (unless the user provided a specific extension) and then specific loading functions are used for each type of data. :+1:

**Comment by nevoliu** [comment]
> 

Thank you very much for your reply. If I change the code, does mlpack need to be rebuilt on one side? Or do I just need to regenerate the solution in Visual Studio?

**Comment by conradsnicta** [comment]
@nevoliu To expand on rcurtin's comment, see also the `.load()` and `.save()` functions in Armadillo: https://arma.sourceforge.net/docs.html#save_load_mat

Rather than adding another file format to mlpack or Armadillo, it might be easier to store data in the portable HDF5 format.  For example, Matlab can read/write HDF5 files:
* https://www.mathworks.com/help/matlab/ref/h5read.html
* https://www.mathworks.com/help/matlab/ref/h5write.html

[Octave](https://octave.org/) can read HDF5 files by specifying the -hdf5 option to the load command: https://octave.sourceforge.io/octave/function/load.html
