### ISSUE TITLE
Ball trees are not guaranteed to have decreasing child furthest descendant distances

### ISSUE THREAD

**Issue by rcurtin** [mlpack/mlpack#349]
**Reported by rcurtin on 2 Feb 44653621 04:25 UTC**
The BallBound class uses an iterative algorithm to determine a bounding ball of a set of points.  But this is not guaranteed to be the minimum bounding ball.  This means that a parent node may end up with a bounding ball that has radius smaller than the bounding balls of its children!  This may break the assumption that the FurthestDescendantDistance() of a child is smaller than the FurthestDescendantDistance() of the parent.

In r17121 I have committed a workaround fix, which makes NeighborSearch work correctly with ball trees, but that workaround (the use of std::min()) should be removed when this bug is resolved.

For this bug to be resolved, we must be able to guarantee that any `BinarySpaceTree<BallBound<...>, ...>` tree is such that the parent node's furthest descendant distance is _always_ larger than any child's furthest descendant distance.  This probably requires a rewrite and rethink of the algorithm implemented in `BallBound<>::operator|=(MatType&)`.

Migrated-From: http://trac.research.cc.gatech.edu/fastlab/ticket/367

**Comment by parijat10** [comment]
I would like to work on this if no one else is working. 
Let me go to through the code and think of an idea for improving BallBound<>::operator|=(MatType&).
I'll update you soon.

**Comment by rcurtin** [comment]
Sure, I don't think anyone else is working on this.  I would be happy to merge in a fix if you are able to fix it.  Also, the commit r17121 in the old svn repository is now 98dcfd6, I think (not certain, it may also be cae0701).

**Comment by Farqd** [comment]
I spent some time looking at this issue and I have some comment/questions.

1. Neither 98dcfd600d79302bcdddb18a39fbe6d1a95a6517 nor cae07019cd98a1221e374de33940fbbcbea4372f seem to contain the fix with std::min you mentioned in the first post.
* 98dcfd600d79302bcdddb18a39fbe6d1a95a6517 introduces MinimumBoundDistance (no new functionality) and adds some code in binary_space_tree_impl.hpp that is no longer present. 
* cae07019cd98a1221e374de33940fbbcbea4372f changes nothing in our case, because FurthestDescendantDistance equals MinimumBoundDistance for ball bounds.

2. I wonder if breaking the assumption that the FurthestDescendantDistance() of a child is smaller than the FurthestDescendantDistance() of a parent really changes anything. In the end the difference only comes from error in our approximation. NeighborSearch can safely discard whole parent tree even if a child tree would give it a false suggestion that some points may be closer. 
Or maybe it's just me not seeing the actual problem (because of point 1).

3. If we want to change algorithm to one that always calculates minimum bounding ball I suggest Emo Welzl’s randomized algorithm. It is mentioned on [Wikipedia ](https://en.wikipedia.org/wiki/Bounding_sphere)and you can also see the [paper](https://www.inf.ethz.ch/personal/emo/PublFiles/SmallEnclDisk_LNCS555_91.pdf).
According to publication it is faster in practice than linear programming solution (and also a lot easier to implement). However, it has some downsides: 
* For high dimensions, it will be significantly slower than the approximation we use right now.
* It is an offline algorithm and at the moment BallBound::operator| allows adding points one by one.
We could change it to either take always all the points and calculate new ball bound, or to store previous points and recalculate ball bound every time when new point is added. Second solution would require making sure that it doesn’t happen too often.

**Comment by rcurtin** [comment]
Hi there @Farqd!  Thank you for looking into this.  Some responses:

1.  I was wrong, the commit is actually 813441a; it's a change to `NeighborSearchRules` specifically, not the tree class itself.  The key part of the change is the `std::max(0.0, ...)`, so my comment about `std::min` is actually backwards.

2.  It actually does change things because of the strange parent-child pruning rules used by many of the dual-tree algorithms.  If the child has larger furthest descendant distance, then `queryNode.FurthestDescendantDistance() - queryNode.Child(i).FurthestDescendantDistance()` becomes negative.  This causes the pruning to be invalid.  If you are interested in the details, see http://proceedings.mlr.press/v28/curtin13.pdf ; the equation that becomes invalid is B_2(N_q) on page 4 (specifically, the second line becomes invalid).

3.  If you'd like to implement it we can try it.  When you say it will be slow in high dimensions, what do you have in mind for 'high dimension'?  If you are thinking 10k+ dimensions, that's not a problem since trees will typically perform very poorly in that regime anyway so we don't need to worry much about that.  But if you mean 10+ dimensions, then that would be a problem.  For what it's worth, typically tree construction is a small amount of time compared spent to the time performing the task with the tree (like nearest neighbor search) so it is not a huge deal if we slow down ball tree construction a little bit to get better bounds.

I wonder if another thing we could do, is to simply recalculate the radius given a fixed center right before the `return *this` in `BallBound::operator|=()`.  But I think also we would need some guarantee that the center we would choose could have radius less than or equal to the radius of the parent node.

**Comment by AbdealiJK** [comment]
Does this mean that the current implementation of Ball tree is invalid and if I use it when running knn I may get inaccurate results?

**Comment by rcurtin** [comment]
No, KNN works properly with `BallTree`, I just had to commit a workaround in 813441a.  `BallTree` is tested in `src/mlpack/tests/knn_test.cpp` in the `KNNModelTest`, and it passes the tests so there is no problem there.  (On the other hand, `BallTree` does not work with rank-approximate nearest neighbor search---see #338---but if you are just using `KNN` and not `KRANN` there is no problem.)

**Comment by AbdealiJK** [comment]
Got it - thanks a lot =)
