### ISSUE TITLE
Installing Python bindings when `pip` in `PYTHONPATH` but not in Python prefix

### ISSUE THREAD

**Issue by wdconinc** [mlpack/mlpack#3500]
#### Issue description

I am using (packaging) `mlpack` in [spack](https://github.com/spack/spack), a package manager often used in high performance computing contexts. Spack installs all packages in a unique prefix, so `python` and `pip` end up in different prefixes. The prefixes of loaded packages are added to the `PYTHONPATH`.

When installing the Python bindings, the installation CMake step overwrites the `PYTHONPATH` environment variable with a more limited version, in [`src/mlpack/bindings/python/CMakeLists.txt`](https://github.com/mlpack/mlpack/blob/master/src/mlpack/bindings/python/CMakeLists.txt#L206):
```cmake
install(CODE "set(ENV{PYTHONPATH} ${CMAKE_PYTHON_PATH})")
```
before going on to call the `python -m pip` installation step in [`PythonInstall.cmake`](https://github.com/mlpack/mlpack/blob/master/src/mlpack/bindings/python/PythonInstall.cmake).

Because Python can now not find the `pip` module in the limited `PYTHONPATH`, the installation fails, with for example:
```console
/opt/software/linux-ubuntu23.04-skylake/gcc-13.1.0/python-3.10.10-7w6otnb4s236ubcjs2tqlpfspufqbqlj/bin/python: No module named pip
CMake Error at /data/spack/stage/wdconinc/spack-stage-mlpack-4.1.0-cs2jxr2x757ue7ro7myvht2wq377rmsk/spack-src/src/mlpack/bindings/python/PythonInstall.cmake:24 (message):
  Error installing Python bindings!
Call Stack (most recent call first):
  src/mlpack/bindings/python/cmake_install.cmake:66 (include)
  src/mlpack/bindings/cmake_install.cmake:50 (include)
  src/mlpack/cmake_install.cmake:68 (include)
  cmake_install.cmake:51 (include)
```

#### Your environment

 * version of mlpack: master, 4.2.0, 4.1.0 all affected
 * operating system: linux ubuntu 23.04
 * compiler: gcc-12.3, gcc-13.1 both affected
 * version of dependencies (Boost/Armadillo): armadillo-12.4.0, 
 * any other environment information you think is relevant: see description above

#### Steps to reproduce

Naturally, I realize that it is a little cumbersome to install a different package manager just to reproduce this.

The following recreates this scenario on a regular ubuntu23.04 system:
```console
# setup pip in prefix
sudo apt-get install python3-pip
python -m pip --version # should find pip in /usr/lib/python3/dist-packages/pip
python -m pip install --force-reinstall --prefix /tmp/pip pip
sudo apt-get purge python3-pip
python -m pip --version # should fail to find pip
export PYTHONPATH=/tmp/pip/local/lib/python3.11/dist-packages/
python -m pip --version # should find pip in /tmp/pip
# build mlpack with python bindings
sudo apt-get install libarmadillo-dev libcereal-dev libensmallen-dev python3-pandas cython3
cmake -Bbuild -S. -DBUILD_PYTHON_BINDINGS=ON
make -Cbuild -j8 install
```

#### Expected behavior
Even with a `pip` module that is accessible to `python` in the calling environment, I expect the installation of the Python bindings to succeed.

#### Actual behavior
Installation fails to complete with logs ending like this:
```console
...
-- Up-to-date: /usr/local/include/mlpack/methods/kmeans/kmeans_main.cpp
-- Up-to-date: /usr/local/include/mlpack/methods/kmeans/pelleg_moore_kmeans_impl.hpp
-- Up-to-date: /usr/local/include/mlpack/methods/kmeans/hamerly_kmeans_impl.hpp
-- Up-to-date: /usr/local/include/mlpack/methods/kmeans/naive_kmeans_impl.hpp
-- Up-to-date: /usr/local/include/mlpack/methods/nmf
-- Up-to-date: /usr/local/include/mlpack/methods/nmf/nmf_main.cpp
-- Up-to-date: /usr/local/include/mlpack/methods/nmf/nmf.hpp
-- Up-to-date: /usr/local/include/mlpack/methods/lars.hpp
-- Up-to-date: /usr/local/include/mlpack/methods/bias_svd.hpp
-- Up-to-date: /usr/local/include/mlpack/methods/CMakeLists.txt
-- Up-to-date: /usr/local/include/mlpack/methods/svdplusplus.hpp
/usr/bin/python: No module named pip
CMake Error at /home/wdconinc/git/mlpack/src/mlpack/bindings/python/PythonInstall.cmake:23 (message):
  Error installing Python bindings!
Call Stack (most recent call first):
  src/mlpack/bindings/python/cmake_install.cmake:66 (include)
  src/mlpack/bindings/cmake_install.cmake:50 (include)
  src/mlpack/cmake_install.cmake:68 (include)
  cmake_install.cmake:51 (include)


make: *** [Makefile:110: install] Error 1
make: Leaving directory '/home/wdconinc/git/mlpack/build'

```

#### Possible solution
One approach that potentially address this (and that completes the install correctly) is the following patch:
```diff
diff --git a/src/mlpack/bindings/python/CMakeLists.txt b/src/mlpack/bindings/python/CMakeLists.txt
index e4b347447..3294f4152 100644
--- a/src/mlpack/bindings/python/CMakeLists.txt
+++ b/src/mlpack/bindings/python/CMakeLists.txt
@@ -203,7 +203,7 @@ execute_process(COMMAND ${PYTHON_EXECUTABLE}
     "${PYTHON_INSTALL_PREFIX}"
     OUTPUT_VARIABLE CMAKE_PYTHON_PATH)
 string(STRIP "${CMAKE_PYTHON_PATH}" CMAKE_PYTHON_PATH)
-install(CODE "set(ENV{PYTHONPATH} ${CMAKE_PYTHON_PATH})")
+install(CODE "set(ENV{PYTHONPATH} \"$ENV{PYTHONPATH}:${CMAKE_PYTHON_PATH}\")")
 install(CODE "set(PYTHON_EXECUTABLE \"${PYTHON_EXECUTABLE}\")")
 install(CODE "set(CMAKE_BINARY_DIR \"${CMAKE_BINARY_DIR}\")")

```
However, some care must probably be taken for when `PYTHONPATH` is undefined. This also may be better resolved in other ways.

**Comment by barak** [comment]
I am having similar issues packaging 4.2.0 for Debian. With the added caveat that network access during the build is **strictly forbidden**, so pip should not be invoked. (Well, maybe `pip show`, although that wouldn't really be definitive since python packages might be installed in other ways.) Perhaps a build option ```NET_ACCESS=OFF``` could be added to turn off anything that might access the internet, and just check for whether the thing it wants to download is already available on the system and if not give a cogent error message.

(This `NET_ACCESS=OFF` option might also be useful on my kids, but I digress.)

**Comment by rcurtin** [comment]
Thank you for opening this issue @wdconinc!  The Python installation step has always been something that I've been dubious about due to the huge amount of complexity in Python environments, so I'm hopeful that we can figure out a robust way forward here (and handle @barak's issue too).

First things first: @barak, what does the Debian project think about [the deprecation of setup.py install](https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html)?  That caused me to make #3313, which uses `pip` to install instead of the typical but apparently now deprecated `python setup.py install`.  So, I could make some CMake option that uses the old style of installation, or, I could perhaps add some pip options that [avoid the network entirely](https://stackoverflow.com/questions/36725843/installing-python-packages-without-internet-and-using-source-code-as-tar-gz-and): `--no-index --no-deps -f ./`.  What do you think on this one?

Next, on to the `PYTHONPATH` issue.  A bit of history: @wdconinc the code you found and patched (which nukes `PYTHONPATH` and replaces it with `CMAKE_PYTHON_PATH`) is necessary because setuptools and pip will refuse to install a package if the destination location is not in `PYTHONPATH`.  So, I think you are right that a good solution is appending the destination location to `PYTHONPATH` instead of totally overwriting it.  Do you want to open a PR with that patch?  If not I can do it.  It looks fine to me as-is.

Another note: we once had a situation where installing the Python bindings to `CMAKE_INSTALL_PREFIX` was incorrect (#2797), which is similar to your situation.  So, the `PYTHON_INSTALL_PREFIX` CMake option was added, so that you can directly install to that location.  I suspect that you could also solve your issue by simply specifying `-DPYTHON_INSTALL_PREFIX="$PYTHONPATH"`.

**Comment by wdconinc** [comment]
> huge amount of complexity in Python environments

Yeah... I am hardly an expert on Python packaging, let alone Python bindings packaging in CMake projects that is compliant with PEP517. A modernization of a similar Python bindings installation happened recently in another project I follow (but am not involved in), https://github.com/xrootd/xrootd/pull/2025. Maybe there is a use in looking at their approach. In particular they allow for a `set(PIP_OPTIONS "" CACHE STRING "pip options used during the Python bindings install.")` cache variable to pass `--no-deps`.

> Do you want to open a PR with that patch?

I will do so today.

**Comment by wdconinc** [comment]
@rcurtin See #3502.

**Comment by barak** [comment]
> First things first: @barak, what does the Debian project think about [the deprecation of setup.py install](https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html)? That caused me to make https://github.com/mlpack/mlpack/pull/3313, which uses pip to install instead of the typical but apparently now deprecated python setup.py install. So, I could make some CMake option that uses the old style of installation, or, I could perhaps add some pip options that [avoid the network entirely](https://stackoverflow.com/questions/36725843/installing-python-packages-without-internet-and-using-source-code-as-tar-gz-and): --no-index --no-deps -f ./. What do you think on this one?

Unfortunately, I treasure my ignorance of this Python packaging stuff.
