### ISSUE TITLE
 ‘class ens::Any’ has no member named ‘As’

### ISSUE THREAD

**Issue by flyingkukri** [mlpack/mlpack#3501]
#### Issue description

Hi, when I want to compile a project where I included mlpack.hpp, I get the error

"/usr/include/ensmallen_bits/svrg/svrg_impl.hpp:223:24: error: ‘class ens::Any’ has no member named ‘As’ "

My language server says "In included file: member '_As' declared as a templateclang(template_member)"

The full error output can be found under https://pastebin.com/UJjbj8X6.

#### Your environment

 * version of mlpack: 4.0.1-3.fc38
 * operating system: fedora 38
 * compiler: gcc 13.1.1-2.fc38
 * version of dependencies (Boost/Armadillo): armadillo 10.8.2-3.fc38, boost 1.78.0-11.fc38
 * any other environment information you think is relevant:

#### Steps to reproduce

1. Install storm,
The storm project is: https://github.com/moves-rwth/storm (takes 1 hour, so maybe just look at the repo below) maybe it is relevant that boost is a dependency of storm
The storm project is: https://github.com/moves-rwth/storm
2. build this project https://github.com/flyingkukri/error_mlpack  (main.cpp is minimal, cmakelists is maybe more relevant)

#### Expected behavior

it compiles successfully

#### Actual behavior

see description

**Comment by conradsnicta** [comment]
@rcurtin @zoq this looks like a problem with ensmallen.

possibly in https://github.com/mlpack/ensmallen/blob/4e36f115c75dfd5fe7c14abdf304aae4daea5881/include/ensmallen_bits/utility/any.hpp#L43-L79

**Comment by conradsnicta** [comment]
@flyingkukri Based on a quick look, the error may stem from a define/macro conflict.  I suspect there may be a `#define As` somewhere within your codebase, along these lines of `#define As cl_as_aux".

It may be possible to counteract this by undefining the As macro before including mlpack.hpp and ensmallen.hpp
Please try the following:

    #undef As
    #undef Any
    #include <mlpack.hpp>

**Comment by conradsnicta** [comment]
@flyingkukri The bug seems to be caused by Class Library for Numbers - CLN (https://www.ginac.de/CLN/), which is probably included (directly or indirectly) within your project.

See lines 269 and 274 in the following file, which define a macro named As 
https://www.ginac.de/CLN/cln.git/?p=cln.git;a=blob;f=include/cln/number.h;h=67f68899a6926eca49722f012d0a20d159162c57;hb=HEAD#l269

I suggest filing a bug with the developers of CLN.  It's strongly recommended that all macros have a unique prefix, in order to avoid clashes like this.  For example, the macro "As" should be defined as "CLN_As".  

Alternatively, the software should clean up after itself, so that all internal macros are undefined at the last point.  In other words, there should be an `#undef As` as the last thing done within the CLN header files.
