### ISSUE TITLE
add getter for classProbabilities, or how do I visualise a decision tree?

### ISSUE THREAD

**Issue by flyingkukri** [mlpack/mlpack#3509]
Hi,

I am currently working on a project where I need to learn decision trees and I would like to visualize these. However I lack the information for the value we are splitting on, which is in classProbabilities. Would it be possible to add a getter?

**Comment by rcurtin** [comment]
Would a getter for `classProbabilities` suffice?  I spent a while thinking about it and it would be tricky to add a getter for the split value, since `DecisionTree` is not guaranteed to have a single split value.  For instance, you could have an n-way split that split with (n - 1) different values into n children.  Or, there may be no split value at all: in categorical dimensions, by default (with `AllCategoricalSplit`), the tree will split into all possible categorical values.

Anyway, the easiest thing to do here would be to provide `ClassProbabilities()` with documentation pointing out that the values are not class probabilities unless the node is a leaf.  If that works for you, I'll open a PR (or you can open one, up to you).  Alternately, if you have a proposal for how to provide a `SplitValue()` member in a safe and flexible way, I'm all ears. :smile:

**Comment by flyingkukri** [comment]
Hi @rcurtin. Yes, that sounds good. Thaks a lot <3~! However I think it will be better if you open  a pull request as I don't have any experience with open source contribution.

**Comment by rcurtin** [comment]
Sounds good, I opened #3511 to add the new feature. :+1:

**Comment by rcurtin** [comment]
#3511 is merged, and so you can either use the git `master` branch, or wait for the next release of mlpack for the functionality to be stable. :+1:
