### ISSUE TITLE
Random Forest don't learn the data if max_depth > 0

### ISSUE THREAD

**Issue by GLmontanari** [mlpack/mlpack#3510]
#### Issue description
Hi! I am running this piece of code to train an Extra Trees classifier.

	mlpack::ExtraTrees<
		mlpack::GiniGain,
		mlpack::MultipleRandomDimensionSelect,
		mlpack::AllCategoricalSplit> clf;

```
size_t numClasses = 2;
size_t min_leaf_sz = 20;
double min_gain_split = 1e-7;
size_t numTrees = 24;
size_t max_depth = 4;  // must be = 0 otherwise it doesn't learn anything

clf.Train(traindata, trainlabel, numClasses, numTrees, min_leaf_sz, min_gain_split, max_depth);
clf.Classify(testdata, predictedLabels);
size_t amountOfCorrectPredictions = arma::sum(predictedLabels == testlabel);
double accuracy = (double)amountOfCorrectPredictions / testlabel.n_elem;
std::cout << accuracy << "\n";
```

When `size_t max_depth = 0;` I noticed that the xml file containing the model is quite big, like 800MB, and so I tought I could shrink the forest to save some disk space. The point is that if I set a non-zero value to the parameter, the model is very small, like 100k, but the generalization of the model is really bad. It seems that it didn't learn anything, even though the accuracy on the test set may be quite good.
Where did I go wrong? is 0 a default that must not be changed?

#### My environment

 * version of mlpack: 4.0.0
 * operating system: Windows 10
 * compiler: MSVC
 * version of dependencies (Boost/Armadillo): Armadillo 11.4.2
 * any other environment information you think is relevant: OpenBLAS-0.3.21, cereal-1.3.2, ensmallen-2.19.0

**Comment by GLmontanari** [comment]
Update. 
I tried to calculate the normalized confusion matrix using this function
```
void print_norm_confmat(arma::Row<size_t> &predictedLabels, arma::Row<size_t> &testlabel)
{
	arma::mat conf_mat;
	mlpack::data::ConfusionMatrix(predictedLabels, testlabel, conf_mat, 2);

	arma::colvec row_sums = arma::sum(conf_mat, 1);

	conf_mat.row(0) /= row_sums[0];
	conf_mat.row(1) /= row_sums[1];
	conf_mat.print();
}
```
And I noticed that for some values of `max_depth` the second row returns Nan, while the accuracy has some value:
![image](https://github.com/mlpack/mlpack/assets/43607219/9a6e2627-4b57-4ec0-94ed-b93a26639325)

**Comment by rcurtin** [comment]
What `max_depth` parameters did you try?  The extra trees algorithm uses a completely random binary split, so with a depth of only 4, there are at most 2^4 = 16 possible splits.  The whole idea of the extra trees algorithm is that the trees used are very large (but random, and thus quick to train).  I suspect you will see better performance with a maximum depth of more like 10 (and likely higher will be necessary to achieve very good performance, depending on the dataset).

If you want to save disk space, also, try saving as `.bin` instead of `.xml` (the XML representation is really huge).  But, at some level, the extra trees algorithm is just a large model.

For your confusion matrix, I am guessing you are seeing NaNs because `row_sums[1]` is `0`.

Hope that's helpful---let me konw if I can clarify anything.

**Comment by GLmontanari** [comment]
Thank you for your reply! Yes, I did some benchmarks with values of `max_depth` from 0 to 10 and I get reasonable values as soon as `max_depth` is 5 or more. I tried it also with the `RandomForest` algorithm and I have the same situation.
I don't understand why it works at ` max_detph = 0` which I read from the code is the default value and works if I set it by hand.

**Comment by GLmontanari** [comment]
I have another question: the number of trees in the forest you get with `NumTrees()` in most cases is not the number of trees you set when you train the classifier, like this 
`clf.Train(traindata, trainlabel, numClasses, num_trees, mleaf, mgain, max_depth, false);`

Is it because `max_depth` != 0 ?
