### ISSUE TITLE
Security improvement: get_deps with https urls?

### ISSUE THREAD

**Issue by ikbenkous** [mlpack/mlpack#3548]
`CMakeLists.txt` has multiple calls to `get_deps()` with `http://` URLs:
```
$ find -type f -print0 | egrep -iz "\.txt$" | xargs -0 egrep -i "http://"
...
./CMakeLists.txt:    get_deps(http://files.mlpack.org/armadillo-10.3.0.tar.gz armadillo armadillo-10.3.0.tar.gz)
./CMakeLists.txt:    get_deps(http://mlpack.org/files/stb.tar.gz stb stb.tar.gz)
./CMakeLists.txt:    get_deps(http://www.ensmallen.org/files/ensmallen-latest.tar.gz ensmallen ensmallen-latest.tar.gz)
...
```

Downloading source code from a _http_ url, not verifying checksums and using them in a automated way seems rather unwise and insecure.

There might be more URLs, but these three that I found can probably be upgraded to `https` without much work. Although that does not check signatures and still places trust in whatever the webserver is currently hosting...

**Comment by rcurtin** [comment]
> I could forgive this tomfoolery

You really expect people to react well when you write like this?

The documentation does say:

> `-DDOWNLOAD_DEPENDENCIES=ON` will automatically download mlpack's dependencies (ensmallen, Armadillo, and cereal). Installing Armadillo this way is not recommended and it is better to use your system package manager when possible (see [below](https://github.com/mlpack/mlpack/#31a-linking-with-autodownloaded-armadillo)).

I personally think that people who were concerned with security to begin with would kind of not be inclined to use the autodownloader, hence my original response.  But, I'm not every person, and perhaps you're right that other people wouldn't think that.  That's reasonable.

I don't mind changing to HTTPS.  I'm less excited about extra code to maintain for checksum verification.  If you want to open a PR, feel free.  I'll happily approve it.  But, don't expect me to thank you for it when you come post issues with such a negative attitude.  Please remember that this is a volunteer project... we do this for fun...

**Comment by ikbenkous** [comment]
> > I could forgive this tomfoolery
> 
> You really expect people to react well when you write like this?

By "`this` tomfoolery" I meant "whatever CMakeLists.txt is doing. Where `this` is not related to you personally in any way whatsoever.

If I wrote anything that insulted you, for that I _sincerely_ apologize. Us Dutchmen can be quite direct and confrontational. (Books have been written about this. See: _Dealing with the Dutch_.)

But with all due respect I can possibly have and confer: hand-waving away security issues and fixes with "people should read the recommendation and not rely on it" seems like insanity to me. The fix is simple and ignoring seems to neglect mlpack and leaves in what I consider a security problem. But hey. What do I know? You are the most active maintainer on this project and I just popped in and just grepped `CMakeLists.txt`.

I have no interest in arguing on the internet. This security thing just rattles my nerves. Do with this info as you must.

**Comment by rcurtin** [comment]
It's all good, no worries.  Thanks for clarifying what you meant.

> I have no interest in arguing on the internet.

+1 to that.  I'll keep my eyes open for a PR, and try to keep things like this more in mind in the future.  (For what mlpack actually does internally, it's pretty self-contained and doesn't access network, so web security is not something I often consider deeply.)

**Comment by shrit** [comment]
@ikbenkous I wrote the auto downloader code and it is probably me that you need to blame. However, keep in mind two things:

1.  You are pulling open-source libraries with no warranties.
2.  You are not downloading any binary.

Finally, if you like the project and you find a bug please do not complain, just be smart about it by opening a PR and trying to fix the issue. You probably put more energy into complaining rather than opening a PR and becoming a contributor and feeling good about it. 

Originally the auto downloader was written for those who would like to cross-compile things for embedded systems, but since then we discovered that it is so handful that everyone started using it for everything.

Please open a PR to fix things and we will be happy to merge it asap

With all warm regards

**Comment by ikbenkous** [comment]
> Finally, if you like the project and you find a bug please do not complain

I am not complaining. I'm merely reporting my findings so that a technical solution may be found, the technical merits of that solution be discussed or I get told that this is not an issue.
This is an established and time-honored procedure for how problems get fixed in F(L)OSS software:
Issue gets opened -> PR gets crafted -> merged / closed.

I feel insulted that you'd say what I am doing is _complaining_.
I'm completely new with mlpack and I don't have the experience or context to make an assessment on my own, so I create an issue to get some more eyes to look at this. And now I get told I'm _complaining_?

I'm all for non-violent communication, but this seems to escalate.
This has got to be in some way of violating the 'code of conduct' you folks set out.
I'm done arguing on the internet.

I promised Ryan in a private e-mail I'd make a PR and look around for some other tasks I can do to help out. Because quite frankly, I felt guilty for ruining the man's Monday somehow. But I'm not interested in contributing when I'm being treated this way over a damn bug report.

If reporting a security issue is 'complaining'? Count me out.

This is beneath the standard of respect I expect to be treated with.

**Comment by shrit** [comment]
@ikbenkous please do not put so many feelings about this discussion, feeling angry, guilty and insulted. The situation is simple, if you want to help you are welcome if not it is up to you to stay or leave.

Also, in open-source software, people would only open an issue if they request a feature that they can NOT contribute. Or if they found a bug that they can NOT fix because they do not have the expertise in the domain. Also, in some cases to discuss more complex issues, adding methods for example, seeking help, or working on a prototype for something, but not for adding `3 chars` in HTTP. Additionally, nothing is stopping you from opening a PR including your above description. 

I made myself clear here, hopefully, you do not get a _new feeling_ from my reply.

**Comment by rcurtin** [comment]
In the interest of keeping things productive and on topic, I just went ahead and opened #3550 with the three-character fix to HTTPS...

My Monday was just fine, but I'm hoping that my Tuesday will be too.  Personally I didn't see the original post as a complaint (only in the most technical sense of the term I suppose), but I also don't think anyone has interest in doing a play-by-play on who said what and who thought what and so forth.  If there is one thing I have learned in 15 years of open source development, it's that one has to have a hard head and try to focus only on the objective code-related outcomes.  (Which, given #3550, will be a success as soon as it's merged.)

We all come from different places and think different things, have different perspectives and reactions and standards, and so forth.  That means we all have something to learn from each other, so my suggestion is that we (including me) try to build some empathy, move on, and focus on the actual technical contributions with good-faith discussions.
