### ISSUE TITLE
Multi-head output network

### ISSUE THREAD

**Issue by AntoineDubois** [mlpack/mlpack#3574]
Hello,
I would like to build a network with this architecture:
$y=f(x, \theta), out_1 = h(y, \theta_h), out_2 = g(y, \theta_g) $
where f, h and g are FFN.
How to build this architecture so often used in deep RL?
Thanks!

**Comment by rcurtin** [comment]
Yes, this actually is a little difficult at this moment.  What we need to do is implement some kind of DAG network that allows you to take the output of a single layer and broadcast it to multiple layers, and then concatenate the layers back together.  There has been some discussion on this in the past, but I can't currently seem to find any.  In any case, what we need is a class like `FFN`, but it is not exactly the same: it holds a set of layers, but also allows the user to connect the layers in any way that forms a DAG.

If you're interested in helping out, I think it actually should not be too hard (though somewhat tedious); essentially one could start from the `FFN` class, hold a representation of the `DAG`, and then adapt the `Forward()` and `Backward()` passes to traverse the DAG instead of a linear traversal over layers.  There will be some trickiness with allocating the right amount of memory, and also with how to have the user select whether a layer with more than one input should be handled: should the inputs be concatenated, merged, etc.?  (Your example suggests concatenation for `out`, but that is not the only way someone might want to use a DAG network.)
