### ISSUE TITLE
RADICAL number of components

### ISSUE THREAD

**Issue by kevindtran1** [mlpack/mlpack#3583]
I am looking at trying the ICA implementation of RADICAL but I can't seem to find if there is a way to set the number of components to extract. Is this feature part of the RADICAL class?

**Comment by rcurtin** [comment]
By default RADICAL will extract all independent components.  I believe you could find the most important components by sequentially running `RADICAL::Vasicek()` on each column of the returned `matY` matrix to compute the entropy, and keeping the components with the largest entropy value.

However, it has been quite a long time since I looked at the RADICAL code, and I wasn't the person who implemented it originally, so, you should double-check whether or not my suggestion is right. :)

**Comment by kevindtran1** [comment]
Thanks for the suggestion! I'll look more into this.
