### ISSUE TITLE
mlpack / opencv namespace ambiguity?

### ISSUE THREAD

**Issue by IgorWojas** [mlpack/mlpack#3589]
Windows10, Visual Studio 2022, latest mlpack, latest openCV (4.8) 

Hey, im not sure it is a problem with mlpack or opencv but when I try to include openCV library along mlpack i get ambiguity errors.
For example:

#include <mlpack/mlpack.hpp>
#include <opencv2/opencv.hpp>

using namespace cv;

Visual studio underlines "cv" saying its ambiguous.

I have recently reinstalled opencv and when using it solely everything is fine. The same goes for mlpack when using solely. But together it's a no-go.

Am i missing something? Should i use full namespace names like "opencv::cv::Mat name" ?

Im a beginner so excuse me if its something simple.

Thanks in advance

EDIT: so I found this:
 https://stackoverflow.com/questions/67612941/when-two-libraries-have-variable-types-with-the-same-name-how-to-define-the-var 
but it also doesn't work.

**Comment by rcurtin** [comment]
Inside of the `mlpack` namespace there is `mlpack::cv` namespace defined for compatibility reasons (so that mlpack3 and older code will work even though mlpack classes now live in a flat namespace).  The file that defines this reverse-compatibility namespace is only included by `mlpack.hpp`.  So, one way around this is that you can include only the headers that you need, [as described in the first bullet point here](https://github.com/mlpack/mlpack#32-reducing-compile-time).  Then the `cv` namespace will not be defined at all.

Alternately, the StackOverflow post you found is right: to avoid ambiguity, you can avoid `using namespace` declarations and simply be explicit about the classes; e.g., `cv::Mat` instead of `Mat`.

Also, Visual Studio is not always the best compiler to use; sometimes it complains and has compilation problems where g++ or clang would not.  So, if moving to a Linux or OS X development system is a possibility, that may also save you some headaches.

**Comment by IgorWojas** [comment]
@rcurtin Thank you. I menaged to workaround the problem somehow. There must be something wrong with my opencv install/build.

**Comment by shrit** [comment]
Closing this issue since it is resolved
