### ISSUE TITLE
benchmark results

### ISSUE THREAD

**Issue by waynelapierre** [mlpack/mlpack#3590]
### What is the desired addition or change?
Benchmark mlpack against mainstream machine learning frameworks like scikit-learn.

### What is the motivation for this feature?
mlpack claims to be fast, but there seems no evidence for that in the documentation. 

### If applicable, describe how this feature would be implemented.
Keep track of the benchmark results for each mlpack release. 

### Additional information?
GPU computing has become vital for machine learning tasks nowadays. My first impression is that mlpack relies on OpenMP for multiple threading but lacks general GPU support (I am aware of GPU linear algebra support via Armadillo). As mlpack is at a stable life stage, it seems infeasible to add CUDA support. One possible enhancement is to add the GPU offloading feature of OpenMP.

**Comment by rcurtin** [comment]
I would love to have up-to-date benchmark results but at the current time there is not available bandwidth to maintain such a system.  There are very old benchmark results available on the website, but they suffer from one problem: they are very old.  Maybe someday someone will take on the task, but at least personally there is not a way I could do it.

> GPU computing has become vital for machine learning tasks nowadays. My first impression is that mlpack relies on OpenMP for multiple threading but lacks general GPU support (I am aware of GPU linear algebra support via Armadillo). As mlpack is at a stable life stage, it seems infeasible to add CUDA support. One possible enhancement is to add the GPU offloading feature of OpenMP.

Actually, there is exciting news here.  mlpack is written using generic types for the matrix type, so any matrix type that supports the Armadillo API can be used.  So, e.g., you can use `arma::mat` and `arma::fmat` for your data types (e.g. 64-bit double, 32-bit float)... but also now there is the newly-released [Bandicoot GPU linear algebra library](https://coot.sourceforge.net/), which supports the same API.  We are still internally working out a handful of bugs and testing everything, but the route to mlpack operating on GPUs is actually entirely possible and not far off.  Of course, there will need to be some amount of tuning our algorithms to work well in both places.  (That said, I think this is very exciting!)

Otherwise, we do use OpenMP in a number of places for parallelism.
