### ISSUE TITLE
Try upgrading your stb implementation (macOS)

### ISSUE THREAD

**Issue by hannesLE** [mlpack/mlpack#3650]
I am trying to build mlpack on macOS Monterey with  `cmake -B build/ -DDOWNLOAD_DEPENDENCIES=ON` but I get the following error:
CMake Error at CMakeLists.txt:329 (message):
  STB implementations's static mode cannot link across multiple translation
  units! Try upgrading your STB implementation, or using the auto-downloader
  (set DOWNLOAD_DEPENDENCIES=ON in the CMake configuration command.
  
 forcing cmake to download the dependencies anyways also caused the same issue.

**Comment by rcurtin** [comment]
Hey there @hannesLE, sorry that you encountered this issue.  I find the problem interesting, because the version of STB downloaded by the autodownloader definitely should not have the problem that that specific error message is checking for.  I suspect that CMake is trying to use the wrong version of STB, or some other issue got incorrectly hidden behind this error message.  A couple questions:

 * Do you have STB installed anywhere else on the system?  (you can search for `stb_image_write.h` or `stb_image.h`)
 * Did you run this in a clean build directory and still encounter the failure?
 * Can you post the output of `build/CMakeOutput.log` and `build/CMakeError.log`?  That should give the actual details of what failed in the STB test file.  (The files may be long...)

Thanks!
