### ISSUE TITLE
Crashes with valid test data

### ISSUE THREAD

**Issue by DougRogers** [mlpack/mlpack#3654]
Run attached .cpp file.  Modified from example.
[testApp.zip](https://github.com/mlpack/mlpack/files/14563344/testApp.zip)

crashes in Train

**Comment by shrit** [comment]
@DougRogers could you add more details, and explain what is the problem?
we are all busy and non of us has the time to debug the problem you are having without description.

**Comment by DougRogers** [comment]
@shrit I just used my data in the example.  Run the example to see the error.

**Comment by andrewfurey21** [comment]
Hello,

It's hard to know what error your specifically running into, it depends on your machine and setup.

I ran your example, and noticed that your subtracting 1 from the training and test labels. It should really be this:
```cpp 
    arma::mat trainLabels = trainData.row(trainData.n_rows - 1);
    arma::mat testLabels  = testData.row(testData.n_rows - 1);

```
This is because the default loss function is `NegativeLogLikelihood` which can't process negative numbers. I'm guessing you took this from the docs, they say in the comments that it is to get it between a range of 0 and N. Your labels are from 0-1 already, so you don't have to do the subtraction.

This is assuming that your labels are the last column in that csv you gave. You should probably elaborate a little more on that. Also, you named the csv file name "TrainingData.csv" in the archive file, but in the cpp file you called it "trainingData.csv". Just something minor.

Hope that helps.

**Comment by DougRogers** [comment]
I'm using Windows, which is not case sensitive for files.  I should have been consistent.

The example is here:
https://github.com/mlpack/mlpack/blob/master/doc/tutorials/ann.md
This source is coded the way I posted.    I thought that is was to accept a single line of data with the expected answer at the end.  The jugging is to get the answer into the trainLabels vector, I assumed.

The example works with the thyroid_train.csv, just nor my data.

**Comment by andrewfurey21** [comment]
Yes, but it works if you make the changes I suggested. You could also use a
different loss function.

**Comment by DougRogers** [comment]
@andrewfurey21 Thank you.  What loss function do you suggest?  I am using this to compare images for similarity.  The values are error function results.  The label is if the images are similar or not.

**Comment by DougRogers** [comment]
Look like a bug in the example code.

**Comment by rcurtin** [comment]
Just to follow up here, the comment in the example code you linked to and adapted specifically says:

```c++
  // Split the labels from the training set and testing set respectively.
  // Decrement the labels by 1, so they are in the range 0 to (numClasses - 1).
  arma::mat trainLabels = trainData.row(trainData.n_rows - 1) - 1;
  arma::mat testLabels = testData.row(testData.n_rows - 1) - 1;
```

So it should be clear from that that `NegativeLogLikelihood` needs labels from `0` to `numClasses - 1`.  In your case the labels were already 0/1 so that is not needed.  I don't see any bug in the documentation.  In any case, glad we could get your code working. :+1:

> @andrewfurey21 Thank you. What loss function do you suggest? I am using this to compare images for similarity. The values are error function results. The label is if the images are similar or not.

If you're not doing a classification problem but instead trying to predict continuous values, or something like this, maybe `MeanSquaredError` is a better choice.  But if you are doing classification, I think it's fine to stick with `NegativeLogLikelihood`.
