### ISSUE TITLE
Reverse Convolution?

### ISSUE THREAD

**Issue by IgorWojas** [mlpack/mlpack#3671]
Hello

There is a vae example in the examples repo (https://github.com/mlpack/examples/blob/master/mnist_vae_cnn/mnist_vae_cnn.cpp)
that introduces reverse (transposed) convolution layer. The note in the code says that it is not implemented yet and leads to PR (https://github.com/mlpack/mlpack/pull/2777). In this PR the transposed_convolution.hpp is ticked away as if it was done, I can't find it anywhere so is it done? 

Cheers

**Comment by IWNMWE** [comment]
Hey @IgorWojas it seems that the Reparametrization and TransposedConvolution layers have not yet been adapted to the mlpack 4 layer style(It is present in the non adapted directory).

**Comment by IgorWojas** [comment]
@IWNMWE Thanks for your reply. So this means its unusable in vanilla mlpack?

**Comment by IWNMWE** [comment]
Yes , currently the unadapted layers require some changes to work with the current mlpack models. You can check out the adaptation of layers pull requests like #3445 to get an idea of what should be done to adapt these layers

**Comment by rcurtin** [comment]
I don't think it would be hard to adapt `TransposedConvolution`; since the class is so related to `Convolution`, I think the changes in #2777 for the `Convolution` class could be pretty much taken as-is.  There might be some minor input/output size issues to handle, but overall it should be straightforward.  I would do it if I had the time, but at the moment I don't (sorry about that).

**Comment by IWNMWE** [comment]
Hey, If no one is having a look at it I will look into its adaptation in a day or 2
