### ISSUE TITLE
Consider disabling -Wunused-parameter in compilation

### ISSUE THREAD

**Issue by stephentu** [mlpack/mlpack#377]
I switched over from gcc to clang for my default C++ compiler, and clang is pretty verbose by default about unused parameters. 

We can either fix these warnings or compile with `-Wno-unused-parameter`. Either is fine by me, but I'm more inclined towards the latter since I think unused parameters is no big deal.

**Comment by rcurtin** [comment]
In 3ad083b I've fixed the `-Wunused-parameter` warnings.  They don't appear under gcc, but I think this may be because gcc might not issue warnings for functions it isn't actually compiling into something.  Just a guess though.  I fixed some `-Wunused-private-field` warnings in fba66e1 and 660fd96.  With those fixes, do you still see warnings?  (Maybe at the level of Armadillo?)

Personally I like fixing warnings, in case downstream projects are compiling with aggressive warning settings (I think RcppMLPACK compiles with `-pedantic`?  I'm not certain though).

**Comment by stephentu** [comment]
Ok, clang is now quiet on a clean build. Thanks! Closing this issue.
