### ISSUE TITLE
Different matrix type for kmeans::RefinedStart

### ISSUE THREAD

**Issue by lockie** [mlpack/mlpack#378]
Hi.
I'm having a problem using kmeans algorithm with `kmeans::RefinedStart` policy and input matrix of type `arma::Mat<uint8_t>` - this produces ton of template errors, which boils down to `centroids` and `sampledCentroids` variables in `kmeans::RefinedStart::Cluster()` being defined as `arma::mat`, whereas they should be of type `MatType` (I believe).
(btw is clustering of `Mat<uint8_t>` data with corresponding metric making sense?)

**Comment by rcurtin** [comment]
This is related to #290 (that ticket references #300 but should reference #288; the incorrect reference is due to a semi-failed import from Trac...).  Basically, mlpack is currently hard-coded to work with doubles, but templatizing `MatType` for every class could allow arbitrary precisions and types (within the confines of what Armadillo provides).  That would be a ton of work, though, and the additional testing required would also be difficult to provide...

For now your best bet is probably to cast your data to `arma::mat`, then cast your resulting centroids back to `arma::Mat<uint8_t>`.

As for whether or not the clustering makes sense, yeah, it makes sense.  Even if the clustering was done in the `uint8_t` space I think it would converge fine.

**Comment by lockie** [comment]
Thanks for quick reply!

I've solved issue by making copy of `kmeans::RefinedStart` policy with aforementioned type changes, so it's compiling. I'm not sure though if its working correctly, I'm trying to check it right now.

> That would be a ton of work, though, and the additional testing required would also be difficult to provide...
Can I be of any help by providing patch with type change in `RefinedStart::Cluster` and corresponding unit-test (I've quickly read kmeans_test.cpp and I'm thinking I can handle it)?

**Comment by rcurtin** [comment]
I think I'd like to propose #290 as a Google Summer of Code project, so hopefully maybe this summer we can find someone to do it.  Your patches can definitely help; you can attach them to #290 or submit a pull request referencing #290.  It may be a long time until they are touched, since we would need to find someone with sufficient interest to actually do all this work (I certainly don't have time for such a huge task), but whenever it did happen we could definitely use your patches. :)

It seems like you've solved the issue, so I'll go ahead and close this one.  Feel free to reopen if necessary.

**Comment by lockie** [comment]
Got it. Thanks!
