### ISSUE TITLE
Considering using c++ linting tools

### ISSUE THREAD

**Issue by stephentu** [mlpack/mlpack#420]
Not sure how much we care about this, but it might be nice to start running the mlpack code through a c++ linter, such as [cpplint](http://google-styleguide.googlecode.com/svn/trunk/cpplint/cpplint.py).

Here is an example of what we would get from cpplint on our codebase:  [https://gist.github.com/anonymous/7ba0015c0a527a381bb5](https://gist.github.com/anonymous/7ba0015c0a527a381bb5)

Some of the complaints are silly and can be removed by filtering them out, but I think some are reasonable. I know you guys are thinking about updating the style guidelines, so it might be nice to have some sort of automated enforcement.

**Comment by rcurtin** [comment]
I agree with this. Not sure I have time to look into the configuration too much but I am happy to help adapt code. I think we all ought to build a design document and coding standards first, and then go from there. (I know I've been saying that for a while... it's close enough to the top of the stack that I think I'll write something up within a few weeks...)

**Comment by stephentu** [comment]
Once you finalize the coding style, I can adapt cpplint to enforce as much of it as possible. Ping this bug when that's ready to go.

**Comment by theaverageguy** [comment]
Are there any auto linters existing ? Like we have autopep8 for python? Maybe I can help.

**Comment by theaverageguy** [comment]
Can I start with Uncrustify @stephentu ? It seems that it could fix a lot of it. 
I would like your help for this PR.

**Comment by stepthom** [comment]
I've had great success using [ClangFormat](http://clang.llvm.org/docs/ClangFormat.html) to stylize code and ensure coding standards. When you make it part of the testing process, code is always ensured to be consistently styled before it's committed.

**Comment by zoq** [comment]
I heard good things about Clang Format. It looks like nobody is working on the issue right now, so if you like to pick it up feel free but don't feel obligated.

**Comment by sam0410** [comment]
stephentu: the link mentioned ('cpplint') is not available

**Comment by outofnames** [comment]
@stephentu , the link you've posted isn't working, you can update it to [this link (github)](https://github.com/google/styleguide/tree/gh-pages/cpplint) 

And is someone working on it? I am kinda interested in it to start, just need a green flag

**Comment by rcurtin** [comment]
Sure, nobody is working on this now; if you wanted to do it, it would be appreciated.

**Comment by amoudgl** [comment]
@rcurtin I just went briefly through the cpplint [style guide](https://google.github.io/styleguide/cppguide.html). I observed that many style options in cpplint style guide are similar to mlpack conventions like two spaces intend, one space for `public` or `private`, maximum 80 characters in a line, function names and so on but some of them needs modification like variable names, braces style etc. We can remove unnecessary checks and modify the [cpplint.py](https://github.com/google/styleguide/blob/gh-pages/cpplint/cpplint.py) file to adapt to the mlpack conventions. What do you think?

**Comment by rcurtin** [comment]
I think that would be great and it would save a lot of time that is currently used to check style.  We could check it first on the existing mlpack codebase to see if it is working (and maybe catch small style issues there).

**Comment by amoudgl** [comment]
@rcurtin In order to find useful cpplint checks which we could directly use without modifications, I did some analysis of the cpplint [script](https://github.com/google/styleguide/blob/gh-pages/cpplint/cpplint.py) and filtered out those checks which can't be done in mlpack source code. I ran the following command to search for style errors in the directory `/src/mlpack/core`:
```bash
./cpplint.py --filter=-runtime/references,-build/header_guard,-legal/copyright,
- runtime/int,-readability/casting,-runtime/explicit,-readability/todo,-build/storage_class,
-build/namespaces,-readability/multiline_string,-build/include_what_you_use,
-readability/alt_tokens,-build/include_order,-build/c++11 $(find ~/mlpack/src/mlpack/core
 -name '*.hpp' -o -name '*.cpp') 
```
In above command, any filter like `-build/header_guard` with `-` indicates the we are omitting this check. Above command raised 6523 style errors ([log](https://gist.github.com/amoudgl/15217a11e62801d581702a0b4c2ae920)). However, most of the them are whitespace errors. Ignoring whitespace errors, I get only 58 errors ([log](https://gist.github.com/amoudgl/61f40f9200214ed31e8339d61c051384)) and most of them seems valid. 

Out of omitted checks in the above command, following checks need some modifications to adapt for mlpack (not sure about others as they don't follow mlpack design guidelines): 

- `-whitespace` - checks for redundant whitespaces in the whole code.
- `-build/include_order` - checks formatting of `include` statements. 
-  `-build/c++11` - checks for approved C++11 packages, this check can be removed I guess because only `chrono` package raises an error that it is not approved.
- Some `readability/` checks also needs modification (have to study more on this)

I am now working on modifying/removing style checks so that I am only left with valid style checks following mlpack design guidelines and conventions. Then I would test my cpplint script on the whole codebase. Let me know if I am working in the right direction.

**Comment by rcurtin** [comment]
That sounds like a fine approach to me.

The linter should ignore any code in `src/mlpack/core/arma_extend/` and `src/mlpack/core/boost_backport/`, by the way---that doesn't follow mlpack's coding conventions, just the coding conventions of either Armadillo or boost.

**Comment by tkhurana96** [comment]
@rcurtin Hi, if you don't mind I would like to run UBsan on mlpack code since no one has picked that up.

**Comment by rcurtin** [comment]
Thanks to @amoudgl and @zoq's hard work, we now have automatic style checks for PRs.

@tkhurana96: sorry for the slow response, I think I did not see this comment.  If you'd like to run UBsan, that could expose some interesting bugs.  Please feel free!
