### ISSUE TITLE
How can I compile the ANN module?

### ISSUE THREAD

**Issue by 5idaidai** [mlpack/mlpack#448]
I saw there is the ann module, but there is no CMakeFile. So can you tell me how can I compile it?

**Comment by zoq** [comment]
The lack of the CMakeList files, is the result of some unfinished work. I can send you the necessary files if you like, so that you can build mlpack with the ann modules.

In fact I'm working on a refactoring of the ann API. I've already refactored the feedforward code and now I'm working on the convolutional neural network code. If you plan to build a feedforward or convolutional neural network, maybe you like to wait for the refactored code? Let me know what you think.

**Comment by 5idaidai** [comment]
I hope you can give me a CMakeList files, I want to study with it, I like your work very much. And does it  requied c++14 features, on other word, if I need a gcc5.1 or higer version?

**Comment by zoq** [comment]
Okay, I just created a gist for each CMakeLists.txt file: https://gist.github.com/zoq. I've written the path into the description. A compiler with c++11 support is absolutely fine.

**Comment by 5idaidai** [comment]
Thank you so much! But when I compile it with the CMakeLists.txt which you provide, I got some errors. The errors are posted at https://gist.github.com/5idaidai/0c65961ba73489504ab1. Hope the help from you.

**Comment by zoq** [comment]
Patched in 98ecfbc07.
