### ISSUE TITLE
error with hmm_viterbi when using gmm hmm

### ISSUE THREAD

**Issue by kahrabji08** [mlpack/mlpack#486]
Hi, 
Am trying to use hmm_viterbi with a model i previously created using hmm train, but i keep getting this error:

terminate called after throwing an instance of 'boost::archive::archive_exception'
  what():  input stream error
Aborted (core dumped)

I used the following command :
$ hmm_viterbi -i S2Training.csv -m S2Model.xml -o S2_Trainging_labels_GHMMlikely_based_on_S2Model.csv -v

And the model was generated successfully using the following command:
$ hmm_train -i S2Training.csv -t gmm -g 3 -l S2Training_labels.csv -n 6 -v -o S2_Model.xml

**Comment by rcurtin** [comment]
Hi there,

When did you build the model, and did you update your mlpack build since you built the model?  There were recently some changes in the git master branch with how the HMMs were saved, which could make an old model incompatible with the new version of the `hmm_*` executables.  Does building a new model with `hmm_train` and then using `hmm_viterbi` with that solve the issue?

**Comment by kahrabji08** [comment]
I updated my mlpack today, though am not sure if my re-installation process is right or not. I tried to search how it should be uninstalled correctly but i couldn't figure it out. so i did the following in the build directory
$ make clean
Then i installed the new git master version in a new directory and followed the same installation steps

**Comment by rcurtin** [comment]
I'm sorry, I'm unclear on what is going on.  I think that your problem is that you built your `S2_Model.xml` file with an old version of `hmm_train` and you need to rebuild it with the new `hmm_train` version.  You can get the version of the program with the `-V` option: `hmm_train -V` or `hmm_viterbi -V`.  The two programs should be of the same version.

As a side note, the file format should not change after the next release of mlpack, but at the moment the serialization support is experimental and subject to change.

**Comment by kahrabji08** [comment]
Thanks alot for your response, I will check that. 
I was using Mlpack-1.0.12 could you please let me know how could I uninstall it and install the new master version.

**Comment by kahrabji08** [comment]
when I run $hmm_viterbi -V
I got the following
hmm_viterbi: part of mlpack 1.x.x

the same for $hmm_Train -V
I got
hmm_Train: command not found

please note that I installed the new master version.I think there may be a problem with the installation process but I couldn't figure it out.
Thanks,

**Comment by kahrabji08** [comment]
Thanks a lot. problem solved, and you were right it seems that the model was built using the older version.

**Comment by rcurtin** [comment]
Great to hear you got it figured out, please feel free to reach out again if you have further issues.
