### ISSUE TITLE
CMake Generated Visual Studio 2013 project fails to build

### ISSUE THREAD

**Issue by planetmarshall** [mlpack/mlpack#508]
CMake generated Visual Studio 2013 project requires support for 'constexpr', which is not supported by the Visual Studio 2013 C++ compiler (VC12). See

https://msdn.microsoft.com/library/hh567368.aspx

**Comment by rcurtin** [comment]
This is true.  Visual Studio compilers have been... difficult to work with, and have been slower than gcc or clang in implementing C++11 support.  So unfortunately you'll need to use VS2015 or newer.

Did CMake issue an error while configuring, or did this happen when you tried to compile?  It sounds like I should modify `CXX11.cmake` to only detect a working compiler when VC14 or newer is being used.

**Comment by stereomatchingkiss** [comment]
Please update your vc2013 with [vc2013 ctp](https://www.microsoft.com/en-us/download/details.aspx?id=41151), maybe you would be able to compile mlpack after you install this package

**Comment by stereomatchingkiss** [comment]
Bad news, even with [vc2013 ctp](https://www.microsoft.com/en-us/download/details.aspx?id=41151), vc2013 still can not compile mlpack

**Comment by rcurtin** [comment]
It looks like the right thing to do here is disable support for any Visual Studio version older than 2015; this is a straightforward task for someone who wants to start contributing.  See the file `CMake/CXX11.cmake`.

**Comment by hercky** [comment]
It looked pretty straightforward so I went ahead and made the changes and opened a pull-request ! 

#543

**Comment by rcurtin** [comment]
Two changes should fix this for good: 935e76d, which causes configuration to fail for Visual Studio 2013 since VS2013 will not compile mlpack, and 20f8bc0, which, when available, uses the newer `target_compile_features()` command from CMake to check if a compiler supports the C++11 features we need, which is a better solution in the end.  So now CMake will tell you if the compiler you are using cannot build mlpack.
