### ISSUE TITLE
RangeSearch constructor: address of '<tree object>' will always evaluate to 'true'

### ISSUE THREAD

**Issue by dongli** [mlpack/mlpack#528]
I am using `RangeSearch` in mlpack 2.0.1 as:
```
typedef metric::EuclideanDistance MetricType;
typedef tree::BinarySpaceTree<MetricType> TreeType;
typedef range::RangeSearch<> SearchType;
...
arma::mat dataset(...);
...
TreeType datasetTree(dataset);
....
SearchType a(&datasetTree, true);
```
The C++ compiler is `g++` 5.2.0, and it print warning as:
```
: warning: address of 'datasetTree' will always evaluate to 'true'
      [-Wpointer-bool-conversion]
    SearchType a(&datasetTree, true);
               ~  ^~~~~~~~~~~
1 warning generated.
```

**Comment by rcurtin** [comment]
This warning is because the type of tree passed to the RangeSearch object is not right; the RangeSearch object uses trees with the RangeSearchStat statistic.

One thing you can do is, instead of using `tree::BinarySpaceTree<MetricType>`, you can use the convenience typedef provided by the RangeSearch class:

```
RangeSearch<>::Tree datasetTree(dataset);
```

and then that should cast correctly to the right type when you call the RangeSearch constructor.

I think that the tutorial documentation for RangeSearch is incorrect, so I'll try and get this fixed later today (which will also solve #525).

**Comment by dongli** [comment]
Thanks for reply! To my knowledge, `RangeSearch` should support multiple types of trees, but in its template interface:
```
template<typename MetricType = metric::EuclideanDistance,
         typename MatType = arma::mat,
         template<typename TreeMetricType,                                          
                  typename TreeStatType,                                            
                  typename TreeMatType> class TreeType = tree::KDTree>              
class RangeSearch
```
the TreeType has been constrained to the above form, so when I used the following trees other than `KDTree`:
```
range::RangeSearch<MetricType, arma::mat, tree::CoverTree>
```
or
```
range::RangeSearch<MetricType, arma::mat, tree::BinarySpaceTree>
```
I got the following errors:
```
error: template template argument has different template parameters than its
      corresponding template template parameter
    typedef range::RangeSearch<MetricType, arma::mat, tree::CoverTree> SearchType;
```
or
```
error: template template argument has different template parameters than its
      corresponding template template parameter
    typedef range::RangeSearch<MetricType, arma::mat, tree::BinarySpaceTree> SearchType;
```

**Comment by rcurtin** [comment]
It does, but the names of those tree types have changed a little bit; for the standard cover tree use `tree::StandardCoverTree` [1], for the ball tree, use `tree::BallTree` [2], for the R tree, use `tree::RTree` [3], and for the R*-tree, use `tree::RStarTree` [4].  The basic idea was that a user shouldn't need to explicitly specify the metric for the tree or the statistic type either; instead, they could just specify the type of the tree (as a template template parameter) and then we could use the other template parameters of the class to fill in the rest.

In order to do this, we had to develop a `TreeType` policy class that takes three template parameters (metric, matrix type, and statistic) [5], then we had to refactor all of the dual-tree algorithms to use this policy class (this was done for the 2.0.0 release).  In general, template typedefs are used to turn more-general classes like `BinarySpaceTree` (which has four template parameters) into the three that are necessary for the `TreeType` policy class.  Each of the four tree types I mentioned earlier is a template typedef.

[1] http://mlpack.org/docs/mlpack-2.0.1/doxygen.php?doc=namespacemlpack_1_1tree.html#a97bb6c0e6c1be359a95c89d21b1afd42
[2] http://mlpack.org/docs/mlpack-2.0.1/doxygen.php?doc=namespacemlpack_1_1tree.html#a918273941d2d1d3999bf232280530d50
[3] http://mlpack.org/docs/mlpack-2.0.1/doxygen.php?doc=namespacemlpack_1_1tree.html#ae9e12acec37727ae9a4dbca379ba4317
[4] http://mlpack.org/docs/mlpack-2.0.1/doxygen.php?doc=namespacemlpack_1_1tree.html#adbf07e6ff61d2d7840b2c7ea88d25fb7
[5] http://mlpack.org/docs/mlpack-2.0.1/doxygen.php?doc=trees.html

**Comment by rcurtin** [comment]
I updated the documentation in 79fd639 months ago but forgot to close this issue.
