### ISSUE TITLE
How to speed up HMM training ?

### ISSUE THREAD

**Issue by wichtounet** [mlpack/mlpack#550]
Hi, 

I'm trying to use this library on handwritten documents. I have an HMM with 1 states (a GMM): 

`auto hmm = std::make_unique<HMM<GMM>>(1, GMM(64, 9));`

I'm trying to train it on a subset of my data, here are the numbers: 
- 244 sequence of observations of variable length
- => 37032 observations 
- 9 features per observation => 333288 features

I would have though these numbers to be reasonable, but it takes much longer than I expected. With 8 gaussian, it took four hours and I'm still waiting since this morning for the result with 64 gaussians. 

Does that seem OK ? I'm working on a small dataset, I cannot imagine how this will work on other datasets. 

Is there anything I can configure to speed up the training ? Can I make it parallel ? 

I have compiled armadillo and mlpack with MKL support. I used all the default options during armadillo and mlpack build (no debug cmake options). I don't have a very good processor, but still a 3.4GHz Sandy Bridge. 

Thanks

**Comment by wichtounet** [comment]
I don't know if that helps, but here is a a trace I took with perf on the currently running 64-gaussian GMM: 

    16.29%  spotter  libmkl_avx.so            [.] mkl_blas_avx_xdgemmger                                          
    14.31%  spotter  spotter                  [.] arma::eglue_core<arma::eglue_minus>::apply<arma::Mat<double>, arma::Mat<double>, arma::Glue<arma::Col<double>, arma::Gen<arma::Row<double>, arma::gen_ones>, arma::glue_times> >                  
    11.65%  spotter  libm-2.21.so             [.] __ieee754_exp_avx                                                 
    11.57%  spotter  libmkl_avx.so            [.] mkl_blas_avx_dgemm_nocopy_anbn_meq9_keq9_b0
     6.72%  spotter  spotter                  [.] arma::op_dot::direct_dot<double>                               
     5.90%  spotter  spotter                  [.] arma::eglue_core<arma::eglue_schur>::apply<arma::Mat<double>, arma::Mat<double>, arma::Glue<arma::Gen<arma::Col<double>, arma::gen_ones>, arma::Op<arma::eGlue<arma::subview_col<double>, arma::Col<double>, arma::eglue_schur>, arma::op_htrans>, arma::glue_times> > 
     4.72%  spotter  libmkl_avx.so            [.] mkl_blas_avx_dgemm_kernel_0 
     4.61%  spotter  spotter                  [.] etl::detail::Assign<float, etl::unary_expr<float, etl::p_max_pool_p_transformer<etl::binary_expr<float, etl::unary_expr<float, etl::rep_r_transformer<etl::fast_matrix_impl<float, std::array<float, 12ul>, (etl::order)0, 12ul> const&, 52ul, 12ul>, etl::transform_op>, etl::plus_binary_op<float>, etl::unary_expr<float, etl::sub_view<etl::fast_matrix_impl<float, std::vector<float, std::allocator<float> >, (etl::order)0, 2ul, 12ul, 52ul, 12ul>&>, etl::identity_op> >, 2ul, 2ul>, etl::transform_op>&>::operator()                                                               
     2.81%  spotter  libmkl_avx.so            [.] LAY16_M8_Tailgas_1
     2.39%  spotter  spotter                  [.] arma::Row<unsigned long>::operator=

**Comment by rcurtin** [comment]
Have you compiled mlpack without debugging symbols?  If you're using the git master branch, then debugging and profiling symbols are enabled by default (you can disable with `-DDEBUG=OFF -DPROFILE=OFF`), and if you're using a release (2.0.1, for instance), then debugging and profiling symbols are disabled by default so that should not be an issue.  And I assume you're compiling your program with `-O3` and without any debugging symbols or anything.

The EM algorithm may take some time to converge for a GMM.  I think maybe to figure out what is going on here, you should try removing the HMM layer and just train a GMM on its own on the data.  When you call `GMM::Train()`, you can pass in an instantiated `EMFit` object so that you can set the options, like the maximum number of iterations and the tolerance.

Based on your profile it seems like the major delay is possibly in these lines from `em_fit_impl.hpp` (lines 88--93):

```
// Calculate the new value of the covariances using the updated
// conditional probabilities and the updated means.
arma::mat tmp = observations - (dists[i].Mean() *
    arma::ones<arma::rowvec>(observations.n_cols));
arma::mat tmpB = tmp % (arma::ones<arma::vec>(observations.n_rows) *
    trans(condProb.col(i)));
```

I wonder if that expression is not being optimized well?

**Comment by wichtounet** [comment]
I just got the results this morning. It took almost 53 hours to train the GMM :(

> Have you compiled mlpack without debugging symbols? 

I'm using the release 2.0.1 built from sources with the default options, so I don't think there are debugging in it. 

> And I assume you're compiling your program with -O3 and without any debugging symbols or anything.

The program is compiled with -O2 -g -march=native with g++-4.9.3

> I think maybe to figure out what is going on here, you should try removing the HMM layer and just train a GMM on its own on the data

I haven't found out how to train a GMM with multiple sequences. Do I have to loop and call Train several times ?

**Comment by wichtounet** [comment]
There is something really weird. The GMM version trains almost instantly while the HMM takes days...

Here is the HMM version: 

```cpp
    auto hmm = std::make_unique<HMM<GMM>>(1, GMM(64, 9))
    std::vector<arma::mat> images;
    //Fill images
    hmm->Train(images);
```

Here is the GMM version: 

```cpp
    auto gmm = std::make_unique<GMM>(64, 9);
    std::vector<arma::mat> images;
    //Fill images
    gmm->Train(images[0]);
    for(std::size_t i = 1; i < images.size(); ++i){
        gmm->Train(images[i], 1, true);
    }
```

Either there is something wrong with this code and I don't use GMM/HMM correctly or there is something definitely wrong in the library.

**Comment by wichtounet** [comment]
I ended up flattening all my observations in a single matrix and calling Train with it, it takes 200 seconds to train the GMM now instead of 53 hours and it seems to work.

**Comment by rcurtin** [comment]
Hey there,

Sorry for the slow response---I have been busy with some other things this week.  It's worth noting that the GMM code you pasted where you iterate over each image and call `gmm->Train(images[i], 1, true)` is actually quite different than what `hmm->Train(images)` will do.  The HMM training process will associate each observation with a probability of coming from each state (in your case, all of these probabilities will be 1), and then flatten all the observations into a single matrix and call `GMM::Train(const arma::mat& dataset, const arma::vec& probabilities)`.  So this *should* be the exact same thing as flattening the data and calling `GMM::Train(const arma::mat& flattenedData)`, but according to what you are saying, the HMM version takes way longer than the flattened GMM version.

When I have some time, I am going to try to reproduce this by taking a flattened dataset, training an HMM with one state, and training a GMM, in the same way you've suggested, and see if the runtimes differ (also important will be setting the random seed to the same thing so that the starting point for each GMM optimization should be the same).

Another thing worth noting is that, in general, training a GMM-HMM without labeled data is a long process that may not give very good results.  It's much better to do labeled training if possible.

**Comment by wichtounet** [comment]
Thanks for your answer :)

> It's worth noting that the GMM code you pasted where you iterate over each image and call gmm->Train(images[i], 1, true) is actually quite different than what hmm->Train(images) will do.

Yes, I figured that out eventually and flattened all my sequence into one. 

> Another thing worth noting is that, in general, training a GMM-HMM without labeled data is a long process that may not give very good results. It's much better to do labeled training if possible.

Does that change anything when there is only one state ?

**Comment by rcurtin** [comment]
>> It's worth noting that the GMM code you pasted where you iterate over each image and call gmm->Train(images[i], 1, true) is actually quite different than what hmm->Train(images) will do.
> Yes, I figured that out eventually and flattened all my sequence into one.

Okay, great.  But I'm going to leave this ticket open, because it is still a problem that you needed to do this.  I think that both of those training methodologies should provide the same result, but they are taking wildly different amounts of time.  So maybe something is wrong.

>> Another thing worth noting is that, in general, training a GMM-HMM without labeled data is a long process that may not give very good results. It's much better to do labeled training if possible.
> Does that change anything when there is only one state ?

As far as results are concerned, probably not (since the inferred probability for each observation has to be 1 for the only state, which is what it would be for the labels anyway).  For this implementation, though, different methods will be called to evaluate the probability of a GMM on labeled and unlabeled data.  I wouldn't be surprised if the unlabeled approach trains a little bit slower (but I think any difference will be marginal, and I haven't tested exactly what the difference would be).
