### ISSUE TITLE
Interested in project: Dataset and experimentation tools

### ISSUE THREAD

**Issue by Jettriangle** [mlpack/mlpack#579]
I would like to participate in developing an appplication for csv-tables testing, as well as creating a series of video user manuals.
May I ask if the project is still open?

**Comment by rcurtin** [comment]
Hi there,

Yes, all projects are still open for applications and proposals.  Probably a better place to discuss this might be the mailing list:

https://lists.cc.gatech.edu/mailman/listinfo/mlpack

You could take a look at the archive and maybe find more information on the project there.

Unfortunately I don't think that video user manuals will be very useful since there is no other video documentation for mlpack; all of the documentation is in text form.  Testing CSV tables for validity would be helpful though.

**Comment by Jettriangle** [comment]
Thanks a lot for the information!

**Comment by rcurtin** [comment]
Sure, no problem!
