### ISSUE TITLE
Dataset and Experimentation Tool Ideas

### ISSUE THREAD

**Issue by keonkim** [mlpack/mlpack#582]
The Dataset and Experimentation tool project starts with a few flints of ideas:
•	checking a dataset for loading problems and printing errors
•	imputation strategies for missing variables
•	splitting a dataset into a training and test set
•	converting categorical features into binary features (or numeric features)

By analyzing the needs I felt the simple and intuitive console application that evaluates the dataset and solves some commonly faced problems can be a good solution to this problem.
I divided the prospective application into four major modules.

* Data IO - Convert to CSV, ARFF, or save into a particular format, and create dummy files. (Maybe just providing better interface using external libraries) 
* Data Transformation - Join/Split, Edit Metadata (Feature type detection & Transformation), remove target leaks, clean missing data (customize, replace with mean, mode, median or remove entire row), fix scaling issues, and etc.
* Statistical Analytics - Descriptive Statistics (Row count, unique value count, missing value count, min, max, mean, median, mode, 1st and 3rd quartile, and etc.), T-Test and etc.
* Mathematical Operators - rounding, applying math operations, extracting hours from timestamps, apply time zone, and etc.

Please let me know if I am going to the right direction. 
Also, Let me know if there is another idea or resource that might help with this project.

**Comment by rcurtin** [comment]
These definitely seem like reasonable suggestions to me.  I like the statistical analytics and mathematical operators.  Timestamps (like 12:00:00UTC or whatever) can be really hard to work with, so transforming them into something mlpack can work with (like just the number of seconds since epoch or something).

When you put together your proposal, be sure to detail two things:
 * the interface that users will use (this doesn't have to be exactly like what I wrote in the Ideas page but it should at least be similar to the rest of mlpack)
 * the basic structure of the code that will have to be implemented for the various functions you are going to have to implement (it should not all be in the main program)

That will provide a good starting place for discussion.

**Comment by keonkim** [comment]
@rcurtin what do you mean by "it should not all be in the main program"?
does it mean that I should not shove all the code into one file?

**Comment by rcurtin** [comment]
Yes, the code should definitely not be all in one file.

Any functionality that you implement that could be used by other parts of mlpack should be implemented as standalone utility functions.  Then the command-line program you write will simply process user input and use those standalone functions.  Take a look in `src/mlpack/core/` to see what I mean.
