### ISSUE TITLE
GMM Serialization function incorrectly named.

### ISSUE THREAD

**Issue by TCatshoek** [mlpack/mlpack#644]
First of all, I'm rather new to c++ so forgive me if this is a misunderstanding on my part.

When attempting to serialize mlpack::gmm::GMM both boost serialization and cereal are unable to find a serialization function. From gmm.hpp:

```
/**
   * Serialize the GMM.
   */
  template<typename Archive>
  void Serialize(Archive& ar, const unsigned int /* version */);
```

So the function is there, but it is named Serialize with a capital S while both boost and cereal expect it to start with a lowercase s. I changed the function declaration to:

```
/**
   * Serialize the GMM.
   */
  template<class Archive>
  void serialize(Archive& ar, const unsigned int version);
```

Along with the corresponding edits in gmm_impl.hpp, and now it works fine with boost serialization. I have not tested it with cereal, but i assume it should work there too.

**Comment by rcurtin** [comment]
Hi there,

This is because the mlpack code style uses capitalized function names.  So we built an adapter to use boost::serialization but at this time there is not one for cereal.  You could use it like this...

```
boost::archive::xml_oarchive oa(...);
mlpack::gmm::GMM<> gmm(...);
oa << mlpack::data::CreateNVP(gmm, "gmm");
```

So, basically, use `mlpack::data::CreateNVP()` to pass to `boost::serialization` (and maybe cereal?  I don't know if that will work) instead of passing the object directly.

If you are interested in the way this works, take a look at `src/mlpack/core/data/serialization_shim.hpp`, but be warned, that is probably the most complex C++ in the whole library.

**Comment by TCatshoek** [comment]
Thanks, that explains it.
