### ISSUE TITLE
Error during building mlpack on Fedora 23

### ISSUE THREAD

**Issue by NiharMaheshwari** [mlpack/mlpack#677]
Running **make** results in the following error which causes the compilation to terminate :
**/usr/include/armadillo_bits/include_superlu.hpp:91:53: fatal error: /usr/include/SuperLU/supermatrix.h: No such file or directory**
Installing SuperLU-devel package fixes the error and the project is built without any issues.
Shouldn't we add this package to the yum (shouldn't this be changed to dnf) command for installing dependencies as given in the docs section of the site , specifically  at :
http://www.mlpack.org/docs/mlpack-2.0.1/doxygen.php?doc=build.html
under the 'dependencies of mlpack' section

**Comment by rcurtin** [comment]
I think that this is actually an Armadillo bug; I was just discussing it with the Fedora Armadillo package maintainer.  I saw that he built the fixed version of the package: https://koji.fedoraproject.org/koji/taskinfo?taskID=14332119 , but it does not look like he has submitted the package update yet.  So it may be a couple weeks before the Armadillo package has the correct dependencies in Fedora.

I have just submitted the mlpack 2.0.1 package as a Fedora update, so you should be able to avoid compilation of mlpack too: https://bodhi.fedoraproject.org/updates/FEDORA-2016-2e2423cbe2

It should be pushed to the repos in about a week, but I think the link I gave you actually has the RPM if you want to just download and install it manually.

I also updated the documentation in in 06cae13 to mention 'dnf' instead of 'yum' (and removed some ancient documentation relating to RHEL5).  So I think each of the issues you mentioned is either fixed or is in the process of being fixed. :)

**Comment by NiharMaheshwari** [comment]
Thanks a lot !
