### ISSUE TITLE
Log::Info has incompatibility issue with some iomanip functions

### ISSUE THREAD

**Issue by keon** [mlpack/mlpack#755]
Log::Info works fine with std::setw, but I found that it has some issues with some functions in `<iomanip>`.
`std::fixed` and `std::setprecision` function is ignored when used together with Log::<any> functions.

**Comment by shikharbhardwaj** [comment]
Can I start working on this issue?

**Comment by shikharbhardwaj** [comment]
I had a look through the code in `prefixedoutstream.hpp` and `prefixedoutstream_impl.hpp`.

Converting each output to a string causes the floating-point types to lose the type information needed by the `destination` stream to output the necessary precision.

I could imagine two solutions to the problem

1. Introduce 3 inline template specialisations for `util::prefixedoutstream::BaseLogic` for `float`, `double` and `long double`, each of which directly writes the `val` to the `destination` stream.
2. Use SFINAE on `BaseLogic` to write `val` directly to the `destination` if the type satisfies `std::is_floating_point`.

Any thoughts?

**Comment by rcurtin** [comment]
Hi Shikhar,

Thanks for looking into this.  I think the second approach is the right one to use here.  Since there should never be a newline printed as a result of printing a number, you can probably simplify the overload of `BaseLogic` greatly, too.

One thing to check will be that `std::fixed` and `std::setprecision` work with Armadillo objects, like this:

```
arma::mat m;
m.randu(5, 5);
Log::Info << std::setprecision(10) << m;
```

But even if that does not, just a patch for floating-point types only will still be a great help!

Thanks,
Ryan

**Comment by shikharbhardwaj** [comment]
Thanks Ryan.

Turns out that just syncing the flags and precision between `destination` and `convert` will be enough, without needing extra overloads.

Printing Armadillo objects with set precision is not possible with this approach AFAICS, as the overloads for `operator<<` called are defined by Armadillo.

Armadillo does provide a `raw_print` method to print without modifying the stream flags but that would require an overload approach on the `baseLogic`(?)

I'll create a PR ASAP with the changes for floating-point types.

**Comment by rcurtin** [comment]
Not quite fixed yet, it would be nice to make sure Armadillo objects print with custom precision first.

**Comment by shikharbhardwaj** [comment]
Hi

An approach for printing Armadillo objects with custom precision would be to define an overload for them, and then use `arma::raw_print` to print the object, as shown [here](http://arma.sourceforge.net/docs.html#raw_print).

The problem with this approach would be misaligned output if the user decides to set incorrect flags on the stream. Also, by default, `std::cout` does not have `std::fixed` set, and `precision` set to 6.

Any suggestions?

**Comment by rcurtin** [comment]
Hi Shikhar, sorry for the slow response on this one.

Here is an idea.  We can use `std::ios` flags to detect what is set and determine whether or not these are the default parameters.  If the default parameters are set, then we can just call Armadillo's typical print() functionality.  However, if different parameters are set, then we can call raw_print().  What do you think of this approach?

**Comment by shikharbhardwaj** [comment]
I am sorry for replying so late.

How do I go about creating template specialisation for Armadillo objects? Checking if the type is from the `arma` namespace has its [quirks](http://stackoverflow.com/questions/34974844/check-if-a-type-is-from-a-particular-namespace). 

How about defining 5 specialisations for `arma::mat`, `arma::vec`, `arma::rowvec`, `arma::spmat`, `arma::cube`? This seems like a big violation of DRY.

Thanks for your time

**Comment by rcurtin** [comment]
Probably the closest we have is `is_arma_type<>`:
https://github.com/conradsnicta/armadillo-code/blob/7.800.x/include/armadillo_bits/traits.hpp#L632

Do you think that will do what you need?  I've used `is_arma_type<>` in other places too for the same reasons.

**Comment by shikharbhardwaj** [comment]
That is great. I'll create a PR with the changes.

**Comment by rcurtin** [comment]
Very nice to have this solved.  Thanks @shikharbhardwaj!
