### ISSUE TITLE
Serialize a class with "map<int, Node*>"

### ISSUE THREAD

**Issue by ThyrixYang** [mlpack/mlpack#811]
I wrote a class like this:
```
class Node
{
public:
  //Node *root;
  map<int, Node*> root;
  template<typename Archive>
  void Serialize(Archive &ar, unsigned int /**/)
  {
    ar & data::CreateNVP(root, "root");
  }
};

class Pad
{
public:
  Node *tree;
  template<typename Archive>
  void Serialize(Archive &ar, unsigned int /**/)
  {
    ar & data::CreateNVP(tree, "tree");
  }
};
```

I found that I can't use a map contains a pointer like this(but it's okay if replaced  by a "Node *")
Did I wrote something wrong or it's impossible to do that?

**Comment by kc420** [comment]
How to use stl container to hold pointers, and serialize it?

**Comment by rcurtin** [comment]
Hi there, sorry for the slow response.  This is a tricky issue...

mlpack uses template metaprogramming in `src/mlpack/core/data/serialization_shim.hpp` so that you can write a method with `Serialize()` instead of `serialize()` which meshes with the style guide (member functions should start with a capital letter).  The details of how this is done is that the `data::CreateNVP()` function essentially wraps the given type `T` in a `FirstShim<T>` object if `T::Serialize()` exists, and this `FirstShim<T>` type then does the necessary wrangling to make the whole thing work.

So this means that for any class that has `Serialize()`, for it to be properly serialized, then `data::CreateNVP()` must be called to serialize it, and not `BOOST_SERIALIZATION_NVP()`.  But the serialization code for `std::map<>` uses `BOOST_SERIALIZATION_NVP()`, so a map that holds any type with `Serialize()` cannot be serialized using the `std::map<>::serialize()` implementation.

This means that there are two choices: manually implement `std::map<>::serialize()` (i.e. don't call `ar & data::CreateNVP(root, "root")` but instead do the implementation by hand), or rename your `Serialize()` function to `serialize()` and it should all work.

Sorry for the long explanation---the topic is complex. :)  I hope this helps, and if I can clarify anything, let me know.

**Comment by kc420** [comment]
Thank you for such a detailed explanation. Changing "S" to "s" worked well.
Can mlpack support Serialize() on stl containers in the future by default?(to mesh with the style guide).:)

**Comment by rcurtin** [comment]
Sure, I am glad that it helped.

There are two options for serialization support for STL containers that hold mlpack objects: the first is to simply reimplement the STL container serialization support inside the class that uses the container (but that is a little ugly).  The second is a bit uglier:

A class template specialization can be added for each `SecondShim<std::type<...>>` object.  Inside of this  class, the `serialize()` method can be implemented in such a way that it is just the implementation of the STL container's `serialize()` function, except with `BOOST_SERIALIZATION_NVP()` replaced with `ar & data::CreateNVP(...)`.

It would be kind of complex and would require testing (although the test case would be simple... just make sure that `ar & data::CreateNVP(some STL container)` compiles).  I personally don't have any plans to implement this right now, but if you would like to the contribution would be welcome. :)

**Comment by kc420** [comment]
Thanks again. I'm glad to contribute to mlpack if I have any good idea (and be able to implement them) in the future.

**Comment by rcurtin** [comment]
I think this issue is done, so I'm going to go ahead and close it.  Feel free to reopen if needed.
