### ISSUE TITLE
EMST non-optimal for d = 2 sets of forests

### ISSUE THREAD

**Issue by peekxc** [mlpack/mlpack#823]
Consider the attached zip archive containing two csv files. I assume you change the path of where the file is downloaded too. The archive contains: 

1. A distance/dissimilarity matrix
2. 100 two-dimensional points from which the dissimilarity matrix was computed from 

I wish to compute the **euclidean minimum spanning tree** of said matrix, built from said points. 

I've attached a reproducible PDF showing several MST implementation results using the traditional MST algorithms from R, printing out the sum of the minimum edge weights for each edge from the resulting MST. 

I also attached a reproducible PDF of the python implementation I'm trying to match, which is actually the only package using the Dual Tree Boruvka approach like MLPACK. 

Finally, if I attempt to do this with MLPACK using the following code, I get a number slightly above the other MST edge weight estimates: 

```
#include <iostream>
using namespace std;

#include <mlpack/core.hpp>
#include <mlpack/methods/emst/dtb.hpp>
using namespace mlpack;
int main()
{
	arma::mat dm;
	data::Load("/Users/mpiekenbrock/Downloads/dissimilarity_matrix.csv", dm, false);

	// Make the dual tree with defaults
	mlpack::emst::DualTreeBoruvka<> dtb(dm);

	// Run the DTB algorithm.
	arma::mat results;
	dtb.ComputeMST(results);

	// Get distances of MST manually, add them up
	double cum_edge_weight = 0;
	for (int i = 0; i < results.n_cols; ++i){
		cum_edge_weight += dm(results(0, i), results(1, i));
	}
	std::cout << cum_edge_weight << std::endl; 
}
```
This outputs 34.1134, slightly above all of the previous MST results of 33.50638. 

[mst_test_case.pdf](https://github.com/mlpack/mlpack/files/623515/mst_test_case.pdf)
[test_data.zip](https://github.com/mlpack/mlpack/files/623342/test_data.zip)
[MST_example.pdf](https://github.com/mlpack/mlpack/files/623522/MST_example.pdf)

* Sidenote: Although it's not really important, the dissimilarity matrix was computed through a nontraditional means of pairwise 'distance.' Each entry represents the maximum between 3 values: the distance between points _i_ and _j_, the distance to the 5th nearest neighbor of _i_, and the distance to the 5th nearest neighbor of _j_.

**Comment by rcurtin** [comment]
To be clear, is the goal to calculate the minimum spanning tree of the dissimilarity matrix if I consider each row of the dissimilarity matrix to be a point in a dataset?  Or is the goal to calculate the minimum spanning tree of the original 100 points with the different notion of distance that you are using?

**Comment by peekxc** [comment]
The goal is to calculate the minimum spanning tree of the dissimilarity matrix, where each row represents the set of these special distances from that point (indexed by row) to every other point in the database (indexed by column), yes. The diagonal is purposefully non-zero. You shouldn't need the original 100 points, except to verify the output of SciKit's implementation, which doesn't accept a pre-built dissimilarity matrix.

**Comment by rcurtin** [comment]
Hey there,

I'm sorry for the lag in the response.  When I review what you've written and take a look, I think that the problem that you are trying to solve is actually different.  mlpack's minimum spanning tree code calculates the minimum spanning tree of the input points---it doesn't take in a dissimilarity (or distance) matrix as input.  Instead the reason that the mlpack implementation is fast is that it can avoid calculating the entire dissimilarity matrix by pruning away parts of work.

However, that strategy, which uses a dual-tree algorithm, only works if the distance used is a valid metric.  In your case, the metric appears to be

```
d(p_i, p_j) = max(d(p_i, p_j), d(p_i, N_5(p_i)), d(N_5(p_j), p_j))
```

where `N_5()` is the fifth nearest neighbor of the input point.  I am not sure if that's a valid metric.

However, if it is (i.e. if you can prove it), then what you can do is implement a new distance metric that follows the API given in this tutorial: http://www.mlpack.org/docs/mlpack-2.1.0/doxygen.php?doc=metrics.html

and then you can use a custom `TreeType` for the `DualTreeBoruvka` class (note: because this is not a Euclidean metric, you can't use typical trees like KD trees or anything.  You'll have to use cover trees or vantage point trees).  Like if your metric was called `MyMetric` you could do

```
DualTreeBoruvka<MyMetric, arma::mat, tree::StandardCoverTree>();
```

**Comment by rcurtin** [comment]
I'm going to close this for inactivity---please feel free to reopen it if necessary.
