### ISSUE TITLE
Add tests for GaussianDistribution:Train(observations,  probabilities)

### ISSUE THREAD

**Issue by yashu-seth** [mlpack/mlpack#839]
Tests exist for GaussianDistribution::Train(observations) but not for GaussianDistribution:Train(observations,  probabilities).

**Comment by Lakshya1605** [comment]
I would like to work on this please could you elaborate on what is expected .Thank You!!!

**Comment by yashu-seth** [comment]
@Lakshya1605 Currently Gaussian distribution can be trained by providing observations and the corresponding probability of those observations. But tests have not been added for this. You can have a look at #733 and #751 which deals with ```GammaDistribtuion::Train(observations, probabilities)``` to get some idea.

**Comment by Lakshya1605** [comment]
@yashu-seth I have gone through #733 and #751  as mentioned and i was thinking if the same method as @rcurtin has mentioned there would work fine.Thank You !!!.

**Comment by Lakshya1605** [comment]
@yashu-seth  I have gone through #733 and #751  as mentioned and i was thinking if the same method as @rcurtin has mentioned there would work fine.Thank You !!!!.

**Comment by rcurtin** [comment]
Hi @Lakshya1605, if you are going to implement tests for this, think about the tests you are writing and ensure that they would be good tests for the Gaussian distribution when it is trained with probabilities for each observation.  Certainly an approach similar to the Gamma distribution tests could work, but it will probably require some adaptation.

**Comment by Lakshya1605** [comment]
@rcurtin @yashu-seth I have been trying the test case as mentioned by "rcurtin" that is `Gaussian::Train(rdata, probabilties)`and `Gaussian::Train(rdata)` should give nearly same parameters( mean and covariance) when all probabilities are 1 . But it turns out that Means are coming the same but not Covariance's .

`BOOST_REQUIRE_CLOSE` in case of covariance is throwing error when "tolerance" is "1e-15" and is only working with "1e-2" .
With Mean it works fine though.Should I proceed with the tests or do you have any suggestions?
Thank You !!!

**Comment by rcurtin** [comment]
1e-2 is 1% tolerance---I think that's fine for the covariance.  Covariance estimation is typically a noisy process.  You could also probably reduce the covariance error by adding more points to the dataset.  One useful thing to check is that the test succeeds with lots of different random seeds.  So you can test that like this: add the line `math::RandomSeed(std::time(NULL))` to the start of the test.  That will set the random seed to the current time.  Then rebuild the package, and run the test many times:

```
while(true); do bin/mlpack_test -t TestSuiteName/TestName; sleep 1; done
```

and that will run the test many times with a different random seed each time.  Typically when I have a test that depends on the random seed, I'll make sure that it doesn't fail at all in 100 or more trials.  Otherwise it will almost certainly fail on some user's system somewhere and we'll get a bug report about it. :)

**Comment by Lakshya1605** [comment]
@rcurtin Do you think the method that you specified which included 

- drawing 2 different distributions with different parameters and then setting probabilities to the first as something small and the second as something large and then recovering the distribution whose parameters will resemble close to the parameters of the second one would work here ?

 When i try implementing it ,there is a problem again with covariance ,this time the error is huge though, shown below
`"GaussianDistributionTrainWithTwoDistProbabilitiesTest": difference{307.077%} between guDist.Covariance()[0]{16.28306164364059} and variance1{4} exceeds 5%`

**Comment by rcurtin** [comment]
That probably means that there is either a problem with your test implementation or a problem with the implementation itself.  Check through the test.  Either way, that strategy of testing should work.

**Comment by rcurtin** [comment]
After #860 is merged, this is fixed.
