### ISSUE TITLE
Model Zoo

### ISSUE THREAD

**Issue by zoq** [mlpack/mlpack#870]
mlpack features some fast implementations of state-of-the-art methods that can be applied to problems ranging from simple regression to large-scale classification, to speech and robotics applications. Several executables are packaged with mlpack meant to provide a simple way to use the method. However, sometimes it takes some time to evaluate a model on a large dataset or it's not that obvious how to use a specific method in a meaningful way to solve problem x. Maybe someone just likes to reuse an already trained model for another problem, etc. So maybe we could open a repository that shares some interesting models and also provide:

- Step by step instructions on how to use the trained model
- A standard and simple way to download the trained model
- References to any other applicable docs or arxiv papers the model is based on

That brings me to another issue, last year Nilay implemented the model from the "GoogLeNet: Going Deeper with Convolutions" paper. I'm using this just as an example the same would also apply for the Recurrent Visual Attention model, anyway right know there is no executable for both models if we decide to share some ready to go models, do we require an executable for each in mlpack. There are advantages and disadvantages, on the one side, I'm not sure someone is going to use e.g. the GoogleNet executable for another problem without changing some parts that the executable can barely handle. On the other side since the bindings project depends on the executables it would mean you can't use the model in a different environment.

I'm opening this issue for discussion because there are advantages and disadvantages to this. Once we reach some consensus we can make a decision. Personally, I feel that sharing some models that are ready to go would surpass the barrier to entry.

**Comment by rcurtin** [comment]
I agree, this could be a nice thing to do.  With neural networks you have the problem that there are many different ways to make them, and one command-line program (or, e.g., Python binding) isn't going to be able to handle all those types of models, since in these cases we are using type information for optimization at compile time.  We also can't include one command-line program (or binding) for each model type, because then we would have way too many programs and bindings and compilation would take forever.

One idea that crosses my mind is this: create a separate repository that holds files like, e.g., `lenet5_main.cpp` (or maybe different names), in the same format as the command-line programs, and then if someone writes one of these programs, it can be compiled to a Python binding or a command-line program or whatever other languages are supported.

You could even include some nice CMake configuration so that you could check out this repository, and say you wanted the model called 'some_model' you could run

```
$ make some_model_main
```

or

```
$ make some_model_python
```

or whatever.

I think a model zoo is definitely a good idea.  Hopefully some of the ideas I wrote here might be applicable, but maybe not, I'm not sure what is best. :)

**Comment by zoq** [comment]
I agree, having an extra executable for each model in the mlpack repository would definitely increase the build time. I wasn't sure if I could easily create bindings without much hazel and probably some huge code duplications in an extra repo. Correct me if I'm wrong, but it sounds like some CMake magic would do the job. I guess another benefit that comes with CMake is the ability to do some preprocessing e.g. download or extract the dataset or extract the compressed model file.

**Comment by rcurtin** [comment]
Yep, CMake could definitely handle that extra preprocessing.  We can host the models themselves either on mlpack.org or on Github, both work fine.

**Comment by zoq** [comment]
I think hosting the models either on GitHub or mlpack.org has its pros and cons.

If we host the models on Github, someone who is only interested in a single model has to download the complete repository, which potentially is somewhat cumbersome. On the other side, if we host the models on mlpack.org we can independently download each model, but you need internet access if you like to test it out. So you can't just clone the repo and test it you have to clone the repo and somehow download the model file and potentially the dataset.

Another point is version control if we update a model, how do we reflect that; an easy solution would be to introduce some kind of version for each model file.

What I'd also like to do see is, it should be possible to build single models just like it's the case for the mlpack repo where we can just build the allknn executable. I think for this case we could adapt the CMake files, but what if I need something that mlpack doesn't provide e.g. some image preprocessing, can I add dependencies to a single model?

**Comment by Trion129** [comment]
Instead of making a compiled version of every file, wouldn't it better to use Boost's serialization module to store the instance of class in a file and then restore that file when user wants it. We can ease this process by making a tool for abstracting this procedure.

Users can then do something like
```
Inception model = loadModel("trainedInception.ml")
```
And then they can choose to train it more on their own dataset or just continue with what we provided

More info:
http://www.boost.org/doc/libs/1_47_0/libs/serialization/doc/index.html

**Comment by zoq** [comment]
The reason why I would go with the executables like we did for the other methods in the mlpack repository is:

- We can create bindings for different languages like python.
- You quickly adapt the model to your own needs, which isn't that easy if we don't provide the model structure because it's saved in some file.
- We can provide a unified interface across all methods, you can use the same command arguments as for the other executables.

**Comment by rcurtin** [comment]
I think maybe this discussion already happened in IRC, but we can already use boost::serialization to load and save models, but a key here is that we cannot save a _type_, we can only save an instantiation of a type.  The type must be known at load time.  So we cannot do anything like

```
auto model = loadModel("filename.bin");
```

because every possible network structure may have a different type.  Therefore we need different executables for each different model type, hence this idea of a model zoo for popular model types (@zoq: correct me if I'm wrong with the motivation there).  Now if we then have some `InceptionModel` type (which is probably something like `FFN<...>`), we can serialize that with something like

```
InceptionModel m;
mlpack::data::Load("model.bin", "model", m);
```

That `Load()` function uses boost::serialization internally, but I think you mentioned in IRC today that you found that support.

**Comment by zoq** [comment]
Thanks for the clarification. To keep this idea going, I thought about the project structure and I think something easy like this would be just fine:

```
model1
    src
    CmakeLists.txt
model2
    src
    CmakeLists.txt
....
CMakeLists.txt
```

As I mentioned earlier what I like to see is that someone can build each model independently e.g. 'make model 1' or build all models. The problem I see is can we include model specific dependencies e.g. boost thread for model2 without making the dependency optional for model2?


Here is a minimal working example: https://github.com/zoq/models of the current structure. If I add ``find_package(Boost 10.49 COMPONENTS system thread REQUIRED)`` to ``CmakeLists.txt`` file of model2, and run cmake again it breaks since it's required and there is no version 10.49. I guess we could add another CMake option that so that we can do something like ``cmake  -DMODELS=model2`` but maybe there is a better solution.

**Comment by rcurtin** [comment]
Here's a quick idea:

```
$ cat model1/CMakeLists.txt
# This model requires boost.thread and boost.system.
find_package(Boost 1.49 COMPONENTS system thread)
if (FOUND_BOOST_SYSTEM and FOUND_BOOST_THREAD) # Those aren't the right variable names, this is just a sketch.
  # Add the target...
  add_target(model1 ...)
else ()
  add_custom_target(model1
    COMMAND echo "Did not find boost.system or boost.thread!  Cannot build this model.")
  # Maybe also print a line during configuration to inform the user that those weren't found.
endif ()
```

This allows us to keep configuration from failing for certain model types, so that a user can always type `make model1`, but depending on the status of the configuration, they will either get the actual build when they type that command, or they will get a message indicating that CMake could not configure that model type properly.

I agree also, we could also add some CMake option too that allows the user to specify that they are most interested in only one particular model.

**Comment by Trion129** [comment]
Can the main repo be created? agents want a new home! :yum:

**Comment by zoq** [comment]
I like the solution @rcurtin proposed, and I think once we have to link against other libraries, we have something in our pockets. Also, we may run into some other problems once we add more models, but I guess we can solve this problem along the way, so at least from my side, we can create the repo and add some models e.g. GoogLeNet, Recurrent models for visual attention, Agents, etc. Let me know what you think.

**Comment by Trion129** [comment]
Yep let's get the repo and models setup for now, other problems can be solved as more models are added, but I think just having the Cmake file in each model as in example would be enough to handle extra dependencies.

**Comment by rcurtin** [comment]
@zoq: do you want to make the repo here or should I do it?  mlpack/model-zoo (or similar) seems a fine place to put it to me.

**Comment by zoq** [comment]
I can create the model, I think ``model-zoo`` or ``models`` works just fine, I don't have a preference.

**Comment by rcurtin** [comment]
I like `models` better :)

**Comment by zoq** [comment]
Here is the new repository: https://github.com/mlpack/models, I will open a PR for the Recurrent Models of Visual Attention and GoogLeNet in the next days.

**Comment by rcurtin** [comment]
I set up a hook so that the mlpack-git list will get emails on commits, and also the mlpack-mailing-lists account is watching the repository now so PRs will also get posted to the mlpack-git list.
