### ISSUE TITLE
Standardize error handling

### ISSUE THREAD

**Issue by rcurtin** [mlpack/mlpack#891]
A long time ago, the general rule of thumb (at least that I used) was to use `Log::Fatal` to handle errors, but sometimes e.g. `Log::Debug` was used to just print the error instead and continue going.  But in other places, sometimes exceptions are being thrown (and `Log::Fatal` itself will throw an exception when a newline is encountered).

One of the most frustrating things about using a new library or tool is when it doesn't give good or consistent error handling output, so we should work to ensure that all of mlpack's output is consistent and easy to handle.  We have some nice pieces:

 * A logging system
 * A backtrace system (only available on Linux at the moment though and only in debugging mode)
 * The C++ exception infrastructure

So how should we make something that makes mlpack easy to debug?  Ideally, if a user gets an error, they should be able to quickly understand what went wrong (usually the error will probably be with their data) and maybe get some guidance on how it might be fixed, such as in the situation where the data has invalid entries, or some guidance on what to learn about to debug further, such as in the situation where some algorithm doesn't converge.

For this issue, before we close it, we should converge on some idea of what we should do, then ensure that all of the error messages in mlpack are consistent.  My current idea (which may not be the best idea!) is that we could return an exception that inherits from `std::exception` with a string field containing the backtrace and the explanation, or something like this.  I think we can also modify the backtrace code so that it works even without debugging symbols---it just doesn't have line numbers.  Using that idea instead of `Log::Fatal` offers the advantage that we can be more clear about the error using the type of the exception---`Log::Fatal` only throws `std::runtime_error`.

This is an open-ended ticket, so it is definitely open for discussion.  I've labeled the difficulty "easy", but by this I only mean that it's going to be implementationally easy, not that coming up with the right idea will be easy. :)

**Comment by zoq** [comment]
I like the idea of unifying the error handling and also your idea of using/extending the C++ exception infrastructure. The way I see it, it's basically what Log::Fatal does but extended with some useful information.

**Comment by IlievskiV** [comment]
First of all, the idea of proper exception handling and using the class Exception is a good idea. Usually, it is a well known software engineering practice, to include and plat the exception handling since the very beginnings of the development of the system, because doing that afterward might be difficult. Having said that, if I understood correctly, there is not such a feature in mlpack.

The following image neatly summarizes the exception handling:
[http://tutorials.jenkov.com/images/exception-handling-strategies/overview.png](url)

If we exclude for now, the alien exceptions, that is the exceptions thrown by the underlying libraries, and handling only the mlpack-related exceptions, it is a good idea to have a separate module for exception classes, where the base class will extend the native std::exception class. From here and so on, it is all matter to a design of the underlying structure of exception classes.

First, I would suggest to define all of the expected exceptions that have a different nature. For example, it could be **MissingValueException** to indicate that there is a missing value. There might be a lot of different classes that can be merged in one, but that is not the point of the exception handling, the name of the class itself is the first indicator and help to debug the problem.

Next is deciding what to encapsulate in the exception classes like the message to display, the relevant parameters, arguments and so on. In the end, a strategy how to inject all of this in the existing code base should be developed. Usually the injection of the code should be repeatable and to apply the same logic for most of the code in mlpack.

This is one general overview, let me dive more in details of the mlpack structure, so I might come with something more concrete.

**Comment by rcurtin** [comment]
Yes, I'd keep it pretty coarse-grained: basically mlpack failures will have one of two reasons: the data is screwed up or the algorithm failed to converge.  Honestly the `std` exceptions like `invalid_argument`, `runtime_error`, etc. can probably cover most everything here.  But the tricky bit is ensuring that the message that is included with the exception is enough for the user to have some idea of what may have happened.  And that's the tricky bit for this ticket here.

It was originally a design goal of mlpack (a long time ago: http://www.igglybob.com/mlpack_future.pdf) to use exceptions fully like this, but the goal was never fully achieved.  I hope that, for this ticket, we can work out the dangling issue of what should be displayed (e.g. backtrace, whatever) in a way that makes it easy for users who have run some mlpack program and received an exception to have some idea what is going wrong.

**Comment by pvskand** [comment]
Just as @IlievskiV had mentioned it is better to have an exceptions base class that all other modules would extend. Also the base class would contain generic exceptions like the ones you mentioned such as `invalid_argument` and `runtime_error` and when the method extends the class, it would exactly specify what the problem could be so that the user gets to know the mistake as closely as possible. 
I guess this is what @IlievskiV was mentioning and I agree to it. Also not to mention we need to write some tests (don't know if test have been previously written for such error in the modules present), and see to it that the correct message is displayed. @rcurtin if this sounds good then can you tell with which module should I start?

**Comment by rcurtin** [comment]
Like I said, I don't see the need for an mlpack exceptions base class, since any of the problems we are encountering can be described as `invalid_argument` or `runtime_error` or some similar exception type that is already in `std`.

I don't think we should start implementation yet; there is still the main issue to work out here: we need to see how we can give the user __interpretable__ exceptions that they can actually do something with.   Remember that if an exception is thrown, then typically you'll only get some short error message like `matrix of incorrect size` or `failed to converge` or something like this; that's not enough for a user to actually understand what has gone wrong.  __That__ is the bigger issue that we need to solve here.

**Comment by vikasshetty1996** [comment]
So basically we have to find a way that the user can understand why that exception was thrown and make it more easier for him/her to debug the code ?

**Comment by rcurtin** [comment]
Yes, is essence, that is the idea. The backtrace system Kirizaki wrote might be a good start at an idea but we need something that can work even without debugging symbols.  I think the backtrace code will work without dwbugging symbols but it won't give line numbers, only function names.

**Comment by nalin12345** [comment]
Hi I would like to work on this issue.

**Comment by CaperCrusader** [comment]
hey is anyone working on this issue ? I wanted to try it ...
