### ISSUE TITLE
mlpack_decision_tree memory exploded on dataset "reuters"

### ISSUE THREAD

**Issue by ThyrixYang** [mlpack/mlpack#951]
I have just finished benchmark script of mlpack_decision_tree, and I noticed that on reuters dataset the memory increases very fast and I have to drop this dataset to run benchmark on my machine. Maybe there is something wrong? (this dataset is extreme because it has so many features)

**Comment by ThyrixYang** [comment]
sklearn worked well on this dataset, used about 4Gb memory. And I think mlpack need more than 10Gb(my RAM is 12Gb)

**Comment by ThyrixYang** [comment]
This dataset has 5114 rows and 17388 columns, I think it's not appropriate to apply decision tree directly on it though, but it's in sklearn's benchmark dataset.

**Comment by rcurtin** [comment]
Definitely with 5k features, mlpack will loop over every possible split and test them all.  So I would expect it to take a long time.  But when I wrote the `Train()` function that does this looping over all dimensions, I wrote it so that it would minimize RAM usage... or so I thought.  Gains aren't cached for every dimension---we only cache the highest gain and the best split dimension.  I wonder if valgrind would reveal some memory leak somewhere?

Alternately I suppose it could be possible that the splits are making a huge, imbalanced tree... for instance, if at every level we take only one point for the left child and the rest for the right child, then we end up with a tree that's 17k levels deep.  That could cause a memory explosion.

**Comment by rcurtin** [comment]
I ran some simple tests.  First I used massif to check the memory usage.  I only have access to a terminal on the system I ran it on right now, so the CLI output from `ms_print` will have to do:

```
--------------------------------------------------------------------------------
Command:            bin/mlpack_decision_tree -t /home/ryan/datasets/reuters_train.csv -T /home/ryan/datasets/reuters_test.csv -L /home/ryan/datasets/reuters_labels.csv -e -v
Massif arguments:   (none)
ms_print arguments: massif.out.22295
--------------------------------------------------------------------------------

    GB
28.79^                                                                 ##
     |                                                                @#
     |                                                            @@@@@#
     |                                                          ::@ @ @#
     |                                                       @@@: @ @ @#
     |                                                     ::@@ : @ @ @#
     |                                                 ::::::@@ : @ @ @#
     |                                              @@@: : ::@@ : @ @ @#
     |                                            ::@@ : : ::@@ : @ @ @#
     |                                          ::::@@ : : ::@@ : @ @ @#
     |                                      @:::: ::@@ : : ::@@ : @ @ @#
     |                                    @:@:: : ::@@ : : ::@@ : @ @ @#
     |                               @@:::@:@:: : ::@@ : : ::@@ : @ @ @#
     |                              :@ :: @:@:: : ::@@ : : ::@@ : @ @ @#
     |                          @::::@ :: @:@:: : ::@@ : : ::@@ : @ @ @#
     |                        ::@:: :@ :: @:@:: : ::@@ : : ::@@ : @ @ @#
     |                     :::: @:: :@ :: @:@:: : ::@@ : : ::@@ : @ @ @#
     |                  :::: :: @:: :@ :: @:@:: : ::@@ : : ::@@ : @ @ @#
     |               @:::: : :: @:: :@ :: @:@:: : ::@@ : : ::@@ : @ @ @#
     |            :::@ ::: : :: @:: :@ :: @:@:: : ::@@ : : ::@@ : @ @ @#
   0 +----------------------------------------------------------------------->Gi
     0                                                                   864.7
```

I then serialized the tree using boost::serialization, to get an idea of the size of the tree:

```
$ bin/mlpack_decision_tree -t ~/datasets/reuters_train.csv -M tree.bin
$ ls -lh tree.bin
-rw-rw-r-- 1 ryan ryan 17K Mar 30 10:36 tree.bin
```

So clearly if the tree can be saved as only 17k, then there must be some unnecessary copying or something going on.  I also checked with valgrind and found no memory leaks.  So there must exist a bug somewhere that is causing a massive number of unnecessary copies.

**Comment by ThyrixYang** [comment]
Hi @rcurtin ,
I found that a copy of data is made for every child, 
```cpp
//line 397 in decision_tree_impl.hpp
// Now that we have the size of the matrix we need to extract, extract it.
    for (size_t i = 0; i < numChildren; ++i)
    {
      // Now that we have the size of the matrix we need to extract, extract it.
      MatType childPoints(data.n_rows, childCounts[i]);
      arma::Row<size_t> childLabels(childCounts[i]);
```
These memory are only used in this for(), but can't be freed during recursion.
So if we assume every path from root to leaf have a same length, the memory used will be O(datasize * depth), because every sample will have a copy in each level on the tree. 

So I think we can just pass the ID of sample in recursion, and we need only one copy of data.

**Comment by rcurtin** [comment]
I see, I had forgotten about that bit.  The reuters dataset is ~170MB so I guess this means that the tree has depth ~200 (let me check that and post another comment).

I think we shouldn't pass indices though because of the extra runtime cost: if we pass an index then we have to do what is effectively random access of the dataset.  Since we have to pass through every dimension when we calculate the gain, we do d passes of n elements in a random order with an additional lookup for each element access.  It is probably going to be more efficient to copy the matrix (a contiguous d x n read/write operation) and then do d contiguous passes over the n elements.

When I thought about this I realized that at the time we make this copy for children, the original data matrix is no longer necessary.  Therefore we could reuse its memory and move points like in the construction of `BinarySpaceTree` (see `src/mlpack/core/tree/perform_split.hpp`).  We would probably have to add an additional constructor that takes an rvalue reference to a dataset for this to work.

I will try to go ahead and implement this shortly, unless you would rather do it.

**Comment by ThyrixYang** [comment]
You are right, that's much better.
I've looked at perform_split, it swaps all the data in left tree to left and right to right.
But if we are using a rvalue reference, then we should new a Mat for each child, and delete the original data, then use a rvalue constructor to move them to subtrees?
Move columns or renew and move rvalue, which one is better?
@rcurtin  I'm glad to do this work if you can guide me. :)

**Comment by rcurtin** [comment]
Sure, you can go ahead and do it, and I can look over a PR and make sure it's what I was thinking.  Basically we should have two constructors.  One can take a `const MatType&` and will copy that matrix to a temporary `MatType` object that is used for construction.  The other can take a `MatType&&`, and then simply moves that object to the temporary `MatType`.

Then, since we are working with a temporary `MatType` that we can modify, we can move the columns.  When we have moved the columns of the temporary `MatType`, we can pass either a submatrix view (i.e. `new DecisionTree(temporaryMat.cols(0, leftPoints - 1), ...)`) or the indices of the columns to use like `BinarySpaceTree` (i.e. `new DecisionTree(temporaryMat, 0, leftPoints - 1, ...)`).

You can refer pretty heavily to the `BinarySpaceTree` code for this, but one caveat is that for the decision tree, we don't actually have to hold the dataset after construction---so the dataset you are using to build can be temporary.

Let me know if I can clarify anything; I'm happy to help out and explain further.

**Comment by ThyrixYang** [comment]
If we use swap and indices of the columns then we use the same mat through recursion, I think I can do this as in perform_split.
If we use a subview, I think the constructor may like this:
```cpp
template<typename MatType>
  DecisionTree(arma::subview<ElemType> data,
               const data::DatasetInfo& datasetInfo,
               arma::subview_col<size_t> labels,
               const size_t numClasses,
               const size_t minimumLeafSize = 10);
```
I think pass the subview is more consistent with original constructor.
The subview is just like passing index and we can't use "const &", otherwise the swap_cols can't be used.
Maybe there is a more elegant way to do this?
Thank you.

**Comment by rcurtin** [comment]
The only problem with a subview is that `arma::subview` is the type for dense subviews, but `arma::sp_subview` is the type for sparse subviews, so you can't catch both like that.  It might be easier to just pass the indices in that case; otherwise the strategy would have to be to templatize further to catch any type of Armadillo expression.

**Comment by ThyrixYang** [comment]
I see, I think I can write four functions and invoke them from original one.
```cpp
template<typename MatType>
  DecisionTree(const MatType& data,
               const size_t begin,
               const size_t count,
               const data::DatasetInfo& datasetInfo,
               const arma::Row<size_t>& labels,
               const size_t numClasses,
               const size_t minimumLeafSize = 10);

  template<typename MatType>
  DecisionTree(const MatType& data,
               const size_t begin,
               const size_t count,
               const arma::Row<size_t>& labels,
               const size_t numClasses,
               const size_t minimumLeafSize = 10);

  template<typename MatType>
  void Train(const MatType& data,
             const size_t begin,
             const size_t count,
             const data::DatasetInfo& datasetInfo,
             const arma::Row<size_t>& labels,
             const size_t numClasses,
             const size_t minimumLeafSize = 10);

  template<typename MatType>
  void Train(const MatType& data,
             const size_t begin,
             const size_t count,
             const arma::Row<size_t>& labels,
             const size_t numClasses,
             const size_t minimumLeafSize = 10);
```

But it's a bit tedious and there will be many copies.
Should I replace original functions with these? Or any suggestions?
Thank you.

**Comment by rcurtin** [comment]
The constructors with `begin` and `count` will only ever be used by children during building, so we can be a little more specific with those and mark them private:

```
 private:
  template<typename MatType>
  DecisionTree(MatType& data /* must be non-const since we will modify it */,
               const size_t begin,
               const size_t count,
               const arma::Row<size_t>& labels,
               const size_t numClasses,
               const size_t minimumLeafSize = 10);

  template<typename MatType>
  DecisionTree(MatType& data,
               const size_t begin,
               const size_t count,
               const data::DatasetInfo& datasetInfo,
               const arma::Row<size_t>& labels,
               const size_t numClasses,
               const size_t minimumLeafSize = 10);
```

It would probably be useful to add two similar private overloads of `Train()` too, and then have the public overloads of `Train()` call those private overloads.  But there is also one more bit.  If the user uses the constructor `DecisionTree(const arma::mat& data, ...)` to build the tree, then we have to copy the matrix `data` since it's const.  We should also offer the user a way to allow the tree-building procedure to modify the data:

```
 public:
  template<typename MatType>
  DecisionTree(MatType&& data, /* rvalue reference allows us to move the matrix into a temporary */
               const arma::Row<size_t>& labels,
               const size_t numClasses,
               const size_t minimumLeafSize = 10)
  {
    // example implementation
    MatType tmp = std::move(data);
    Train(tmp /* non-const overload */, 0, tmp.n_cols, numClasses, minimumLeafSize);
  }
```

and then probably one more overload of that for when `DatasetInfo` is passed too.

I know it is a lot of overloads but I think it is necessary to provide the flexibility the user might need.  Fortunately we are only adding two methods to the public methods, everything else will be private.

**Comment by ThyrixYang** [comment]
I see, I'll make a pr soon according to this.
I think it's a good solution to this issue.

**Comment by ThyrixYang** [comment]
Do we deal with the labels same as data or simply copy labels through recursion? I think it's better to swap labels the same as data, so the labels should also be non-const.
And I think the original Train method can simply copy data and call the non-const method like this:
```cpp
Train(const MatType& data,
                                      const arma::Row<size_t>& labels,
                                      const size_t numClasses,
                                      const size_t minimumLeafSize)
{
  MatType tmpData = data;
  arma::Row<size_t> tmpLabels = labels;
  Train(tmpData, 0, tmp.n_cols, tmpLabels, numClasses, minimumLeafSize)
}
```
So we do not copy data in constructors, and the Train method will work when users call it by a no-trained model.
And the duplicate code will be less.

**Comment by rcurtin** [comment]
Ah, yeah, I agree, we can deal with the labels in the same way.  But I think we only need one overload for rvalue-based `Train()`.

**Comment by ThyrixYang** [comment]
I think there will be one Train overload with datasetInfo and one without it?

**Comment by rcurtin** [comment]
Ah, right!  Yes, there will be two then.  Sorry for the mistake. :)

**Comment by ThyrixYang** [comment]
I encountered a problem
```
In file included from /home/thyrix/Projects/mlpack/src/mlpack/../mlpack/methods/decision_tree/decision_tree.hpp:442:0,
                 from /home/thyrix/Projects/mlpack/src/mlpack/tests/decision_tree_test.cpp:13:
/home/thyrix/Projects/mlpack/src/mlpack/../mlpack/methods/decision_tree/decision_tree_impl.hpp: In instantiation of ‘mlpack::tree::DecisionTree<FitnessFunction, NumericSplitType, CategoricalSplitType, ElemType, NoRecursion>::DecisionTree(MatType&&, arma::Row<long unsigned int>&&, size_t, size_t) [with MatType = arma::Mat<double>&; FitnessFunction = mlpack::tree::GiniGain; NumericSplitType = mlpack::tree::BestBinaryNumericSplit; CategoricalSplitType = mlpack::tree::AllCategoricalSplit; ElemType = double; bool NoRecursion = false; size_t = long unsigned int]’:
/home/thyrix/Projects/mlpack/src/mlpack/tests/decision_tree_test.cpp:432:44:   required from here
/home/thyrix/Projects/mlpack/src/mlpack/../mlpack/methods/decision_tree/decision_tree_impl.hpp:100:35: error: invalid initialization of non-const reference of type ‘arma::Mat<double>&’ from an rvalue of type ‘std::remove_reference<arma::Mat<double>&>::type {aka arma::Mat<double>}’
   MatType tmpData = std::move(data);
                                   ^
```
Maybe it's a stupid question..Why "with MatType = arma::Mat<double>&"?

my code
```cpp
template<typename FitnessFunction,
         template<typename> class NumericSplitType,
         template<typename> class CategoricalSplitType,
         typename ElemType,
         bool NoRecursion>
template<typename MatType>
DecisionTree<FitnessFunction,
             NumericSplitType,
             CategoricalSplitType,
             ElemType,
             NoRecursion>::DecisionTree(MatType&& data,
                                        arma::Row<size_t>&& labels,
                                        const size_t numClasses,
                                        const size_t minimumLeafSize)
{
  // move the data to avoid copy
  MatType tmpData = std::move(data);
  arma::Row<size_t> tmpLabels = std::move(labels);
  // Pass off work to the Train() method.
  Train(tmpData, 0, tmpData.n_cols, tmpLabels, numClasses, minimumLeafSize);
}
```
Thank you!

**Comment by rcurtin** [comment]
It looks like it's inferring `MatType = arma::mat&` not `arma::mat`.  What is the code you are using to instantiate this method?

**Comment by ThyrixYang** [comment]
According to build information, it's decision_tree_test.cpp:432:44.
Which is
```cpp
// Build decision tree.
DecisionTree<> d(inputData, labels, 3, 10); // Leaf size of 10.
```

**Comment by ThyrixYang** [comment]
I've found what is wrong:
```cpp
arma::Mat<size_t> labels;  // should be arma::Row<size_t> labels;
  if (!data::Load("vc2_labels.txt", labels))
    BOOST_FAIL("Cannot load labels for vc2_labels.txt");
```
Seems when I have added rvalue constructor and reference constructor, the compiler can't match functions correctly, so the match must be exactly.

**Comment by ThyrixYang** [comment]
I've just made a pr.
Here is my test result on reuters:
```
--------------------------------------------------------------------------------
Command:            /home/thyrix/Projects/mlpack/build/bin/mlpack_decision_tree -t /home/thyrix/Downloads/forkedSrc/benchmarks/datasets/reuters_train.csv -T /home/thyrix/Downloads/forkedSrc/benchmarks/datasets/reuters_test.csv -L /home/thyrix/Downloads/forkedSrc/benchmarks/datasets/reuters_labels.csv
Massif arguments:   --stacks=yes --detailed-freq=5 --max-snapshots=400
ms_print arguments: massif.out.31069
--------------------------------------------------------------------------------


    GB
1.329^                                                                  :     
     |         #:@@::@:@@:@::@@@@@::@@:@@@@:@@:@@:@@:@::@@:::@@:::@:@@@@@:    
     |         #:@@::@:@@:@::@@@@@::@@:@@@@:@@:@@:@@:@::@@:::@@:::@:@@@@@:    
     |         #:@@::@:@@:@::@@@@@::@@:@@@@:@@:@@:@@:@::@@:::@@:::@:@@@@@:    
     |         #:@@::@:@@:@::@@@@@::@@:@@@@:@@:@@:@@:@::@@:::@@:::@:@@@@@:    
     |         #:@@::@:@@:@::@@@@@::@@:@@@@:@@:@@:@@:@::@@:::@@:::@:@@@@@:    
     |         #:@@::@:@@:@::@@@@@::@@:@@@@:@@:@@:@@:@::@@:::@@:::@:@@@@@:    
     |         #:@@::@:@@:@::@@@@@::@@:@@@@:@@:@@:@@:@::@@:::@@:::@:@@@@@:    
     |         #:@@::@:@@:@::@@@@@::@@:@@@@:@@:@@:@@:@::@@:::@@:::@:@@@@@:    
     |         #:@@::@:@@:@::@@@@@::@@:@@@@:@@:@@:@@:@::@@:::@@:::@:@@@@@:    
     |         #:@@::@:@@:@::@@@@@::@@:@@@@:@@:@@:@@:@::@@:::@@:::@:@@@@@:    
     | @@::::@:#:@@::@:@@:@::@@@@@::@@:@@@@:@@:@@:@@:@::@@:::@@:::@:@@@@@:    
     | @@::::@:#:@@::@:@@:@::@@@@@::@@:@@@@:@@:@@:@@:@::@@:::@@:::@:@@@@@:    
     | @@::::@:#:@@::@:@@:@::@@@@@::@@:@@@@:@@:@@:@@:@::@@:::@@:::@:@@@@@:    
     | @@::::@:#:@@::@:@@:@::@@@@@::@@:@@@@:@@:@@:@@:@::@@:::@@:::@:@@@@@:    
     | @@::::@:#:@@::@:@@:@::@@@@@::@@:@@@@:@@:@@:@@:@::@@:::@@:::@:@@@@@:    
     | @@::::@:#:@@::@:@@:@::@@@@@::@@:@@@@:@@:@@:@@:@::@@:::@@:::@:@@@@@:@@@@
     | @@::::@:#:@@::@:@@:@::@@@@@::@@:@@@@:@@:@@:@@:@::@@:::@@:::@:@@@@@:@@@@
     | @@::::@:#:@@::@:@@:@::@@@@@::@@:@@@@:@@:@@:@@:@::@@:::@@:::@:@@@@@:@@@@
     | @@::::@:#:@@::@:@@:@::@@@@@::@@:@@@@:@@:@@:@@:@::@@:::@@:::@:@@@@@@@@@@
   0 +----------------------------------------------------------------------->Gi
     0                                                                   886.3
```

**Comment by rcurtin** [comment]
These results look excellent, I am excited to merge this in.  Thanks for taking the time to work this out!
